Repository openshift/openshift-azure, pull requests merged in 2018-11, with the labels that each got.

#680 Retry connection refused errors
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/S

#682 Generate during make build
  Makefile
Labels: approved, lgtm, size/XS

#684 Fix valid region check in hack/create.sh
  hack/create.sh
Labels: approved, lgtm, size/XS

#679 Remove local htpasswd auth config when not testing.
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#653 Get result from applied arm template
  pkg/fakerp/fakerp.go
  pkg/log/log.go
  pkg/util/azureclient/resources.go
Labels: approved, lgtm, size/M

#674 Return a structured error in the plugin api so the step that failed is obvious
  pkg/api/plugin.go
  pkg/api/plugin_test.go
  pkg/plugin/plugin_test.go
  pkg/upgrade/deploy.go
  pkg/upgrade/healthcheck.go
  pkg/upgrade/ready.go
  pkg/upgrade/update.go
Labels: approved, lgtm, size/L

#686 createorupdate: env checks and random region selection
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  hack/delete.sh
  hack/upgrade.sh
  pkg/util/mocks/mock_azureclient/azureclient.go
Labels: approved, lgtm, size/L

#689 Make htpasswd setup re-entrant
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#558 Clean up the upgrader interface
  pkg/api/plugin.go
  pkg/cluster/deploy.go
  pkg/cluster/drain.go
  pkg/cluster/drain_test.go
  pkg/cluster/healthcheck.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/M

#678 test struct tags of the api types
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/types_test.go
  pkg/util/structtags/structtags.go
Labels: approved, lgtm, size/L

#703 Fix createorupdate error typecast panic
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/S

#700 Move OSA request manifest out of hack/create.sh
  env.example
  hack/create.sh
  hack/upgrade.sh
  test/manifests/normal/create.yaml
Labels: approved, lgtm, size/M

#701 add additional VM flavours and increase maximum number of compute nodes
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/default.go
  pkg/api/types.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/config/derive.go
  pkg/config/derive_test.go
Labels: approved, lgtm, size/L

#706 add additional VM flavours and increase maximum number of compute nodes
  pkg/addons/bindata.go
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/default.go
  pkg/api/types.go
  pkg/arm/bindata.go
  pkg/config/derive.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#716 add published image
  pkg/config/images.go
Labels: approved, lgtm, size/XS

#722 Update create.sh env vars.
  hack/create.sh
Labels: approved, lgtm, size/XS

#724 make default storage class use xfs filesystem
  pkg/addons/bindata.go
  pkg/addons/data/StorageClass.storage.k8s.io/azure.yaml
  pkg/arm/bindata.go
Labels: approved, lgtm, size/XS

#721 Gather artifacts in createorupdate
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/L

#712 Return a PluginError instead of a plain error
  pkg/api/plugin.go
  pkg/cluster/deploy.go
  pkg/cluster/healthcheck.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/M

#699 Added a recursive struct value population function
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/types_test.go
  test/util/populate/walk.go
Labels: approved, lgtm, size/XL

#677 Adding another e2e test
  test/e2e/client_test.go
  test/e2e/conditions_test.go
  test/e2e/end_user_test.go
Labels: approved, lgtm, size/L

#715 only open :22 on master nsg
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#727 Reduce createorupdate size
  cmd/createorupdate/createorupdate.go
  pkg/addons/bindata.go
  pkg/arm/bindata.go
  pkg/fakerp/artifacts.go
  pkg/fakerp/config.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/XL

#733 remove thanasisk from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#720 bye bye logbridge
  .gitignore
  Dockerfile.logbridge
  Makefile
  cmd/logbridge/README.md
  cmd/logbridge/main.go
  env.example
  pkg/api/config.go
  pkg/api/plugin.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/fakerp/server.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/XL

#683 Re-entrant node upgrades
  pkg/api/plugin.go
  pkg/cluster/deploy.go
  pkg/cluster/deploy_test.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/log/log.go
Labels: approved, lgtm, size/L

#736 Fix generated code check in make verify
  hack/validate-generated.sh
  pkg/addons/bindata.go
  pkg/arm/bindata.go
Labels: approved, lgtm, size/XS

#621 move dns.sh to go
  hack/create.sh
  hack/delete.sh
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/L

#743 Add granularity to updateInPlace and updatePlusOne
  pkg/api/plugin.go
  pkg/cluster/update.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/L

#747 fix computer name / node name issues and tidy up
  pkg/cluster/deploy.go
  pkg/cluster/drain.go
  pkg/cluster/drain_test.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/update.go
Labels: approved, lgtm, size/L

#749 Remove quotes from bash envs to fix Go flag parsing
  test/e2e.sh
Labels: approved, lgtm, size/XS

#623 Rewrite hack/aad.sh in go
  cmd/createorupdate/createorupdate.go
  env.example
  hack/create.sh
  hack/upgrade.sh
  pkg/fakerp/aad.go
  pkg/fakerp/config.go
  pkg/fakerp/manifest.go
  pkg/util/azureclient/graphrbac.go
  test/e2e.sh
  test/manifests/normal/create.yaml
Labels: approved, lgtm, size/L

#752 Cleanup hack/create.sh
  cmd/createorupdate/createorupdate.go
  hack/create.sh
Labels: approved, lgtm, size/M

#755 Update hash fix
  pkg/cluster/deploy.go
  pkg/cluster/update.go
Labels: approved, lgtm, size/XS

#761 Remove obsolete binary cleanup
  Makefile
Labels: approved, lgtm, size/XS

#763 add AADClientSecret
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#758 manifest default was not working using envconfig
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
  pkg/fakerp/manifest.go
Labels: approved, lgtm, size/S

#764 harmonise logging, ensure that we use a *logrus.Entry wherever possible
  cmd/azure-controllers/azure-controllers.go
  cmd/createorupdate/createorupdate.go
  cmd/etcdbackup/etcdbackup.go
  cmd/sync/sync.go
  pkg/arm/arm.go
  pkg/cluster/drain.go
  pkg/cluster/drain_test.go
  pkg/cluster/healthcheck.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/etcdbackup/etcdbackup.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/log/log.go
  test/e2erp/compute.go
  test/e2erp/realrp_test.go
Labels: approved, lgtm, size/L

#760 Cleanup e2e script
  test/e2e.sh
Labels: approved, lgtm, size/M

#768 always wait for route to return 200 before proceeding
  test/e2e/end_user_test.go
Labels: approved, lgtm, size/S

#770 Allow accessing all VMs in tests
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/XS

#766 Add another spec to e2erp
  test/e2erp/client_test.go
  test/e2erp/realrp_test.go
Labels: approved, lgtm, size/M

#769 Validate pkg/util is empty
  Makefile
  hack/validate-util.sh
  pkg/addons/translate.go
  pkg/arm/arm.go
  pkg/arm/arm_test.go
  pkg/fakerp/dns.go
  pkg/util/template/template.go
Labels: approved, lgtm, size/S

#777 fix typo and missing debuglevel setting
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#746 Make it so StandardD2sV3 can only be used in test
  cmd/sync/sync.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#772 3.11.43 release
  pkg/config/images.go
Labels: approved, lgtm, size/XS

#781 add unit tests for reading and updating the update blob
  pkg/cluster/deploy_test.go
Labels: approved, lgtm, size/L

#771 Add NO_WAIT functionality for DELETEs
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/L

#784 missing package import
  pkg/addons/bindata.go
  pkg/config/util.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/XL

#787 Cleanup dummy certs from test/util/populate
  test/util/populate/walk.go
Labels: approved, lgtm, size/M

#780 e2e test refactor take 2
  Makefile
  hack/e2e.sh
  pkg/addons/client.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/types.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/config/util.go
  pkg/util/azureclient/azureclient.go
  pkg/util/randomstring/randomstring.go
  pkg/util/ready/ready.go
  pkg/util/ready/ready_test.go
  test/clients/azure/client.go
  test/clients/azure/compute.go
  test/clients/azure/osa.go
  test/clients/openshift/client.go
  test/clients/openshift/dumpinfo.go
  test/clients/openshift/login.go
  test/clients/openshift/project.go
  test/clients/openshift/template.go
  test/e2e/client_test.go
  test/e2e/conditions_test.go
  test/e2e/customer_admin_reader_test.go
  test/e2e/doc.go
  test/e2e/e2e_test.go
  test/e2e/extended_suite_test.go
  test/e2e/generator_test.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/realrp/realrp.go
  test/e2erp/client_test.go
  test/e2erp/compute.go
  test/e2erp/doc.go
  test/e2erp/e2erp_suite_test.go
  test/e2erp/fakerp_test.go
  test/e2erp/realrp_test.go
Labels: approved, lgtm, size/XXL

#789 move to networkpolicy plugin
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-node/node-config-compute.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-infra.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-master.yaml
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/S

#790 fix TestUpdateBlob flake
  pkg/cluster/deploy.go
  pkg/cluster/deploy_test.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/cluster/updateblob.go
  pkg/cluster/updateblob_test.go
Labels: approved, lgtm, size/L

#791 Enable configurable timeouts for e2e tests
  hack/e2e.sh
Labels: approved, lgtm, size/XS

#797 Fix response checks on failed cluster creations
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#783 add validate-imports.go
  Makefile
  hack/update-addons/update-addons.go
  hack/validate-imports/validate-imports.go
Labels: approved, lgtm, size/L

#750 Update external api to use pointers
  pkg/addons/clean_test.go
  pkg/api/2018-09-30-preview/api/marshal.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/convertertov20180930preview_test.go
  pkg/api/deepcopy_test.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/arm/arm_test.go
  pkg/cluster/ready_test.go
  pkg/config/derive_test.go
  pkg/config/generate_test.go
  pkg/config/images_test.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  test/util/populate/walk.go
Labels: approved, lgtm, size/XXL

#796 Avoid skipping errors in the e2e framework
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, size/M

#802 remove overrides
  test/overrides
Labels: approved, lgtm, size/XS

#805 Avoid setting region on DELETEs
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
Labels: approved, lgtm, size/M

#810 Enable partial requests to update clusters
  pkg/api/2018-09-30-preview/api/client.go
  test/manifests/normal/scaleup.yaml
Labels: approved, lgtm, size/S
