Repository openshift/openshift-azure, pull requests merged in 2018-07, with the labels that each got.

#113 change etcd image version
  pkg/config/generate.go
Labels: lgtm, size/XS

#116 Add validation script for generated code
  Makefile
  hack/validate-generated.sh
  pkg/addons/bindata.go
Labels: size/M

#115 Default to run sync locally
  env.example
Labels: lgtm, size/XS

#92 Enhance the healthcheck to provide healthz for api and check for pod status to be running.
  pkg/addons/client.go
  pkg/checks/checks.go
  pkg/healthcheck/healthcheck.go
Labels: lgtm, size/L

#111 remove v from image name
  env.example
Labels: kind/bug, lgtm, size/XS

#118 #116 follow ups
  README.md
  create.sh
  delete.sh
  hack/aad.sh
  hack/dns.sh
  hack/update-addons.go
  hack/validate-generated.sh
Labels: lgtm, size/S

#122 fix addons race condition
  pkg/addons/client.go
Labels: lgtm, size/S

#125 Avoid nil resp panic
  pkg/checks/checks.go
Labels: lgtm, size/XS

#109 add unit tests (1)
  Makefile
  pkg/addons/addons.go
  pkg/addons/clean_test.go
  pkg/addons/testdata/clean/DaemonSet.apps-in.yaml
  pkg/addons/testdata/clean/DaemonSet.apps-out.yaml
  pkg/addons/testdata/clean/Deployment.apps-in.yaml
  pkg/addons/testdata/clean/Deployment.apps-out.yaml
  pkg/addons/testdata/clean/DeploymentConfig.apps.openshift.io-in.yaml
  pkg/addons/testdata/clean/DeploymentConfig.apps.openshift.io-out.yaml
  pkg/addons/testdata/clean/ImageStream.image.openshift.io-in.yaml
  pkg/addons/testdata/clean/ImageStream.image.openshift.io-out.yaml
  pkg/addons/testdata/clean/Namespace-in.yaml
  pkg/addons/testdata/clean/Namespace-out.yaml
  pkg/addons/testdata/clean/Pod-in.yaml
  pkg/addons/testdata/clean/Pod-out.yaml
  pkg/addons/testdata/clean/Secret-in.yaml
  pkg/addons/testdata/clean/Secret-out.yaml
  pkg/addons/testdata/clean/Secret-service-account-token-in.yaml
  pkg/addons/testdata/clean/Secret-service-account-token-out.yaml
  pkg/addons/testdata/clean/Service-in.yaml
  pkg/addons/testdata/clean/Service-out.yaml
Labels: size/L

#134 Fix validation script
  hack/validate-generated.sh
Labels: lgtm, size/XS

#132 Bootstrap kubeconfig needs to exist for sync daemonset to work
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: lgtm, size/XS
