Repository openshift/openshift-azure, pull requests merged in 2018-12, with the labels that each got.

#779 Etcd cluster recovery
  .gitignore
  Makefile
  cmd/recoveretcdcluster/recoveretcdcluster.go
  hack/etcdbackup.sh
  hack/etcdrecovery.sh
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/arm/arm_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/cluster/deploy.go
  pkg/cluster/deploy_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/updateblob.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/compute.go
  pkg/util/mocks/mock_arm/arm.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/L

#820 add make target for metricsbridge
  Makefile
Labels: approved, lgtm, size/XS

#809 Handle possible errors from os.Setenv
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/S

#800 Try to get rid of e2e flake
  pkg/addons/client.go
  pkg/util/managedcluster/managedcluster.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
  test/e2e/specs/end_user.go
Labels: approved, lgtm, size/M

#818 Fix Md5Mismatch error during update in place
  pkg/cluster/updateblob.go
  pkg/cluster/updateblob_test.go
Labels: approved, lgtm, size/S

#823 update image version
  pkg/addons/bindata.go
  pkg/config/images.go
Labels: approved, lgtm, size/XL

#830 Cleanup OSA RP client code
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/artifacts.go
  test/e2e.sh
Labels: approved, lgtm, size/L

#836 Remove colons from addons
  hack/verify-code-format.sh
  pkg/addons/bindata.go
  pkg/addons/data/RoleBinding.rbac.authorization.k8s.io/kube-system/system-controller-cloud-provider.yaml
  pkg/addons/data/RoleBinding.rbac.authorization.k8s.io/kube-system/system-controller:bootstrap-signer.yaml
Labels: approved, lgtm, ok-to-test, size/M

#837 private-preview-1.1 forward port
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-customerdata-config.yaml
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/S

#827 Find core fakerp directories recursively
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
  pkg/fakerp/directory.go
  pkg/fakerp/directory_test.go
  pkg/fakerp/manifest.go
Labels: approved, kind/feature, lgtm, size/L

#838 Follow-up to https://github.com/openshift/openshift-azure/pull/818
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/types.go
  pkg/cluster/updateblob.go
  pkg/cluster/updateblob_test.go
Labels: approved, lgtm, size/M

#773 geneva metrics integration
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/geneva-cluster-reader.yaml
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/Namespace/openshift-azure-monitoring.yaml
  pkg/addons/data/Secret/openshift-azure-monitoring/azure-registry.yaml
  pkg/addons/data/Secret/openshift-azure-monitoring/mdm-cert.yaml
  pkg/addons/data/ServiceAccount/openshift-azure-monitoring/geneva.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/config.go
  pkg/api/convertfromadmin.go
  pkg/api/converttoadmin.go
  pkg/api/plugin.go
  pkg/api/types_test.go
  pkg/cluster/ready.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/fakerp/config.go
  pkg/plugin/plugin_test.go
  pkg/plugin/validate.go
Labels: approved, lgtm, size/XL

#844 Set RUNNING_UNDER_TEST only when true
  pkg/fakerp/config.go
Labels: approved, lgtm, size/XS

#845 add prometheus operator components readiness check
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/S

#848 arm move to standard lb
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/S

#846 Allow test manifest to run for prod clusters
  test/manifests/normal/create.yaml
Labels: approved, lgtm, size/XS

#856 rename values
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-customerdata-config.yaml
Labels: approved, lgtm, size/XS

#816 Catch, retry, and log the x509 exception. Small refactor.
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/addons/client.go
  pkg/addons/client_test.go
  pkg/cluster/deploy.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/util/managedcluster/managedcluster.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
  test/e2e/specs/end_user.go
Labels: approved, lgtm, size/L

#860 Use the new FindDirectory in e2e tests
  test/clients/openshift/client.go
  test/clients/openshift/login.go
Labels: approved, lgtm, size/S

#859 remove extraneous -test on dns domain
  pkg/fakerp/dns.go
Labels: approved, lgtm

#857 azureclient tidy up
  cmd/createorupdate/createorupdate.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/graphrbac.go
Labels: approved, lgtm, size/M

#861 Remove az dependency from hack/delete.sh
  hack/delete.sh
  hack/etcdrecovery.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/S

#840 logging add namespace and account
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-customerdata-config.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/config.go
  pkg/api/convertfromadmin.go
  pkg/api/converttoadmin.go
  pkg/api/plugin.go
  pkg/api/types_test.go
  pkg/config/generate.go
  pkg/fakerp/config.go
  pkg/plugin/plugin_test.go
  pkg/plugin/validate.go
Labels: approved, lgtm, size/L

#825 etcd backup and recover e2e test
  Makefile
  pkg/util/ready/ready.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, lgtm, size/L

#794 Key rotation e2e tests
  Makefile
  cmd/recoveretcdcluster/recoveretcdcluster.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  test/clients/azure/osa.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, size/L

#867 remove AzureLocations, no longer required since LogAnalytics was removed
  pkg/api/default.go
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, size/M

#874 Set region from the external manifest in e2e tests if unset
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, size/S

#877 Set prod flag correctly in hack/delete.sh
  hack/create.sh
  hack/delete.sh
  test/manifests/normal/scaleup.yaml
Labels: approved, lgtm, size/S

#813 More unit tests for cluster and move some code out to make testing easier
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/util/kubeclient/drain.go
  pkg/util/kubeclient/drain_test.go
  pkg/util/kubeclient/ready.go
  pkg/util/kubeclient/ready_test.go
  pkg/util/kubeclient/types.go
  pkg/util/mocks/mock_kubeclient/types.go
Labels: approved, lgtm, size/XXL

#885 fix stale generated code
  pkg/util/mocks/mock_kubeclient/types.go
Labels: approved, lgtm, size/XS

#880 Enable e2e to run against either fake rp or real rp.
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
  pkg/fakerp/server.go
  test/clients/azure/client.go
Labels: approved, lgtm, size/M

#883 Add go-reportcard and godoc badges
  README.md
Labels: approved, lgtm

#875 Reordered arguments to match the ctx, log, ..., bool order
  cmd/azure-controllers/azure-controllers.go
  cmd/recoveretcdcluster/recoveretcdcluster.go
  pkg/addons/addons.go
  pkg/addons/client.go
  pkg/addons/client_test.go
  pkg/arm/arm.go
  pkg/arm/arm_test.go
  pkg/controllers/customeradmin/namespace_controller.go
  pkg/controllers/customeradmin/rolebinding_controller.go
  pkg/controllers/customeradmin/shared.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_arm/arm.go
  test/clients/azure/osa.go
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, lgtm, size/M

#824 Make sure enduser can't delete any azure resources
  pkg/util/azureclient/resources.go
  test/clients/azure/client.go
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, size/M

#873 Add unit test for HealthCheck
  pkg/cluster/healthcheck.go
  pkg/cluster/healthcheck_test.go
Labels: approved, lgtm, size/L

#887 Key rotation e2e uses the OSA RP
  cmd/createorupdate/createorupdate.go
  pkg/api/2018-09-30-preview/api/client.go
  pkg/api/admin/api/client.go
  test/clients/azure/osa.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, size/M

#889 Support templated manifests in keyrotation e2e
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/manifest.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, size/M

#890 Fix rp focus selections in e2e tests needing azure client
  test/clients/azure/client.go
Labels: approved, lgtm, size/S

#896 Give some space to the cluster available msg
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#898 Remove pweil from reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#821 Support admin requests in the fake RP
  pkg/api/plugin.go
  pkg/api/validate.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#891 Relax dns variable restrictions from e2e tests
  pkg/fakerp/config.go
Labels: approved, lgtm, size/XS

#795 Scale up/down E2E tests
  Makefile
  test/e2e/specs/scaleupdown.go
  test/manifests/normal/scaledown.yaml
Labels: approved, lgtm, size/L

#903 Change the order the monitoring stack is healthchecked
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/S

#831 Add re-entrancy check e2e test
  Makefile
  pkg/fakerp/fakerp.go
  test/clients/azure/client.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/scaleupdown.go
  test/util/log/log.go
Labels: approved, lgtm, size/L

#907 Ensure correct amount of entries in the update blob
  test/clients/azure/client.go
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/S

#910 Set ttl on dns zones
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, size/S

#911 issue-745 making router profile verification fail as soon as possible
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, size/M

#892 Move kubeclient into a sub-package of cluster
  pkg/cluster/kubeclient/drain.go
  pkg/cluster/kubeclient/drain_test.go
  pkg/cluster/kubeclient/ready.go
  pkg/cluster/kubeclient/ready_test.go
  pkg/cluster/kubeclient/types.go
  pkg/cluster/ready.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/util/mocks/mock_kubeclient/types.go
Labels: approved, lgtm, size/S

#901 decrease polling interval
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/azureclient/managedapplications.go
  pkg/util/azureclient/marketplaceordering.go
  pkg/util/azureclient/resources.go
  pkg/util/azureclient/storage.go
Labels: approved, lgtm, size/M

#914 Add e2e image and make targets
  .gitignore
  Dockerfile.e2e
  Makefile
Labels: approved, lgtm, size/S

#920 Fix fakerp.FindDirectory to find folders at system root
  pkg/fakerp/directory.go
  pkg/fakerp/directory_test.go
Labels: approved, lgtm, size/S

#913 Split fake RP into its own process
  .gitignore
  cmd/createorupdate/createorupdate.go
  cmd/fakerp/main.go
  cmd/recoveretcdcluster/recoveretcdcluster.go
  hack/create.sh
  hack/delete.sh
  hack/fakerp.sh
  hack/upgrade.sh
  pkg/fakerp/client/aad.go
  pkg/fakerp/client/config.go
  pkg/fakerp/client/manifest.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/fakerp/shared/directory.go
  pkg/fakerp/shared/directory_test.go
  pkg/fakerp/shared/shared.go
  test/clients/azure/client.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, size/L

#916 Make the generation of scaleset and instance names more consistent
  pkg/api/validate.go
  pkg/arm/arm_test.go
  pkg/cluster/deploy.go
  pkg/cluster/deploy_test.go
  pkg/cluster/ready_test.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/names.go
  pkg/config/names_test.go
Labels: approved, lgtm, size/L

#886 Add support for vnet testing
  Makefile
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/util/azureclient/network.go
  pkg/util/azureclient/resources.go
  test/clients/azure/client.go
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, size/L

#931 Trap killing process on 8080
  hack/create.sh
  hack/delete.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/S

#938 Vnet peering test updates
  pkg/fakerp/client/config.go
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, size/M

#935 Preparation for upgrade rework
  pkg/api/plugin.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/arm/arm_test.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/cluster/deploy.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/update.go
  pkg/cluster/update_test.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/names.go
  pkg/config/names_test.go
  pkg/plugin/plugin_test.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/cloudprovider/cloudprovider_test.go
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/L

#928 metrics forwarding infrastructure should use unix domain socket for reliability and security
  cmd/metricsbridge/example-config.yaml
  cmd/metricsbridge/metricsbridge.go
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/td-agent.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/translate.go
  pkg/config/derive.go
  pkg/util/statsd/statsd.go
  pkg/util/statsd/statsd_test.go
Labels: approved, lgtm, size/L

#946 Extend e2e test timeout
  Makefile
Labels: approved, lgtm, size/XS

#921 Admin API bug fixes and createorupdate enhancements
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  hack/delete.sh
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types_test.go
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, size/L

#941 added a parity test between 20180930preview and internal API
  pkg/api/types_test.go
Labels: approved, lgtm, size/M

#950 Wait specifically for lsof to exit
  hack/create.sh
  hack/delete.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#940 Update production RP tests to be self-contained
  Makefile
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/client/config.go
  pkg/fakerp/client/groups.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, size/L

#960 Temporarily revert use of standard load balancer, it breaks our scale…
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/cloudprovider/cloudprovider_test.go
Labels: approved, lgtm, size/M

#948 Remove redundant script
  hack/fakerp.sh
Labels: approved, lgtm, size/S

#961 Improved error messages in createorupdate
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/client/aad.go
Labels: approved, lgtm, size/S

#962 Simplify manifest helpers
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/client/manifest.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, size/L
