Repository openshift/openshift-azure, pull requests merged in 2018-09, with the labels that each got.

#315 implement DeepCopy for OpenShiftManagedCluster
  pkg/api/deepcopy.go
  pkg/api/deepcopy_test.go
  pkg/api/marshal.go
  pkg/config/generate_test.go
  pkg/util/fixtures/fixtures.go
Labels: approved, lgtm, size/L

#318 TestDeepCopy test after mutation
  pkg/api/deepcopy_test.go
Labels: approved, lgtm, size/XS

#320 Deep copy old config before merging
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/XS

#321 enabling timestamps in sync
  cmd/sync/sync.go
Labels: approved, lgtm, size/XS

#301 Avoid in-place updates for compute/infra nodes
  cmd/createorupdate/update.go
Labels: approved, lgtm, size/M

#324 only set public IPs on masters
  hack/ssh.sh
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/M

#322 simplify nil checks
  pkg/api/marshal.go
  pkg/util/fixtures/fixtures.go
Labels: approved, lgtm, size/M

#325 Drop redundant emptyDirs from the registry
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
Labels: approved, lgtm, size/XS

#330 must use %d not %q with ints
  pkg/validate/validate.go
Labels: approved, lgtm, size/XS

#341 Avoid applying NSGs on updates
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/M

#345 Fix invalid ARM template
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/S

#326 Add PVC for Prometheus
  pkg/addons/bindata.go
  pkg/addons/data/StatefulSet.apps/openshift-metrics/prometheus.yaml
Labels: approved, lgtm, size/S

#343 make sync-image: tag sync image with commit id
  Makefile
Labels: approved, lgtm, size/XS

#258 add limits for node process
  pkg/addons/addons.go
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-node/node-config-compute.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-infra.yaml
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/config.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/convertertov20180930preview.go
  pkg/api/default.go
  pkg/api/types.go
  pkg/config/derive.go
  pkg/config/generate_test.go
  pkg/config/util.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#291 move to BYO AAD app flow
  README.md
  env.example
  hack/aad.sh
  hack/create.sh
  hack/delete.sh
Labels: approved, lgtm, size/L

#283 Enable scale up/down
  cmd/createorupdate/createorupdate.go
  cmd/createorupdate/update.go
  cmd/createorupdate/update_test.go
  hack/create.sh
  hack/upgrade.sh
  pkg/plugin/plugin.go
  pkg/validate/validate.go
Labels: approved, lgtm, size/L

#355 remove aadTenantId from cloud config
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#354 remove ServicePrincipalProfile from external api
  README.md
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/convertertov20180930preview_test.go
  pkg/api/deepcopy_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#339 Configure sync image pullspec in plugin init
  cmd/createorupdate/createorupdate.go
  pkg/config/images.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/S

#360 Add Update plugin method
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  hack/upgrade.sh
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  pkg/upgrade/deploy.go
  pkg/upgrade/drain.go
  pkg/upgrade/update.go
  pkg/upgrade/update_test.go
Labels: approved, lgtm, size/M

#363 add validation on auth provider name
  hack/create.sh
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/S

#351 add tenantId field to AADIdentityProvider
  cmd/logbridge/README.md
  hack/create.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#323 Add generated htpasswd
  hack/config.sh
  pkg/api/config.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/util.go
Labels: approved, lgtm, size/M

#373 GenerateARM signature uses a bool for indicating update
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/S

#385 remove Version field from Config struct
  pkg/api/config.go
  pkg/config/generate.go
  pkg/config/upgrade.go
Labels: approved, lgtm, size/XS

#374 Sort master VMs by health before upgrade
  pkg/upgrade/drain.go
  pkg/upgrade/ready.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
Labels: approved, do-not-merge/hold, size/L

#392 Add AuthProfile and AzProfile to MergeConfig
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/S

#397 Add missing deps
  glide.lock
  vendor/github.com/hpcloud/tail/.gitignore
  vendor/github.com/hpcloud/tail/.travis.yml
  vendor/github.com/hpcloud/tail/CHANGES.md
  vendor/github.com/hpcloud/tail/Dockerfile
  vendor/github.com/hpcloud/tail/Godeps/Godeps.json
  vendor/github.com/hpcloud/tail/Godeps/Readme
  vendor/github.com/hpcloud/tail/LICENSE.txt
  vendor/github.com/hpcloud/tail/Makefile
  vendor/github.com/hpcloud/tail/README.md
  vendor/github.com/hpcloud/tail/appveyor.yml
  vendor/github.com/hpcloud/tail/cmd/gotail/.gitignore
  vendor/github.com/hpcloud/tail/cmd/gotail/Makefile
  vendor/github.com/hpcloud/tail/cmd/gotail/gotail.go
  vendor/github.com/hpcloud/tail/ratelimiter/Licence
  vendor/github.com/hpcloud/tail/ratelimiter/leakybucket.go
  vendor/github.com/hpcloud/tail/ratelimiter/leakybucket_test.go
  vendor/github.com/hpcloud/tail/ratelimiter/memory.go
  vendor/github.com/hpcloud/tail/ratelimiter/storage.go
  vendor/github.com/hpcloud/tail/tail.go
  vendor/github.com/hpcloud/tail/tail_posix.go
  vendor/github.com/hpcloud/tail/tail_test.go
  vendor/github.com/hpcloud/tail/tail_windows.go
  vendor/github.com/hpcloud/tail/util/util.go
  vendor/github.com/hpcloud/tail/watch/filechanges.go
  vendor/github.com/hpcloud/tail/watch/inotify.go
  vendor/github.com/hpcloud/tail/watch/inotify_tracker.go
  vendor/github.com/hpcloud/tail/watch/polling.go
  vendor/github.com/hpcloud/tail/watch/watch.go
  vendor/github.com/hpcloud/tail/winfile/winfile.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/.editorconfig
  vendor/gopkg.in/fsnotify/fsnotify.v1/.github/ISSUE_TEMPLATE.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/.github/PULL_REQUEST_TEMPLATE.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify/fsnotify.v1/.travis.yml
  vendor/gopkg.in/fsnotify/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/example_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fsnotify_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_poller_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/integration_darwin_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/integration_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/windows.go
  vendor/gopkg.in/tomb.v1/LICENSE
  vendor/gopkg.in/tomb.v1/README.md
  vendor/gopkg.in/tomb.v1/tomb.go
  vendor/gopkg.in/tomb.v1/tomb_test.go
Labels: approved, lgtm, size/XXL

#389 don't use oldCs in update
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
  pkg/upgrade/update_test.go
  pkg/validate/validate.go
Labels: approved, lgtm, size/L

#406 disable audit and reduce loglevel
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
Labels: approved, lgtm, size/S

#401 added json tags to Config struct
  pkg/api/config.go
Labels: size/L

#398 add access the cluster section
  README.md
Labels: approved, lgtm, size/XS

#409 Avoid running loganalytics on CI tests
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/upgrade/update.go
  pkg/util/util.go
Labels: approved, lgtm, size/S

#416 remove prometheus from health check, but add an e2e check
  pkg/checks/checks.go
  test/e2e/osa_test.go
Labels: approved, lgtm, size/M

#417 allow ssh into arbitrary clusters, stop requiring resourcegroup on delete
  hack/config.sh
  hack/delete.sh
  hack/ssh.sh
Labels: approved, lgtm, size/M

#426 Record short commit id on every sync build
  .gitignore
  Dockerfile.sync
  Makefile
Labels: approved, lgtm, size/XS

#419 osa test blacklist
  test/overrides
Labels: approved, lgtm, size/XS

#405 add draft for test doc
  docs/testing.md
Labels: approved, lgtm, size/M

#436 add 444 as port for kubecontroller
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#442 fix daft mistake in ssh.sh
  hack/ssh.sh
Labels: approved, lgtm, size/XS

#441 use -X to store sync commit
  .gitignore
  Dockerfile.sync
  Makefile
  cmd/sync/sync.go
Labels: approved, lgtm, size/S

#444 always create StorageClasses before objects that use them
  pkg/addons/addons.go
Labels: approved, lgtm, size/S

#451 update owners file
  OWNERS
Labels: approved, size/XS

#453 clarify ssh.sh argument ordering
  hack/ssh.sh
Labels: approved, lgtm, size/XS

#415 tie deployed images to specific version, and use published images
  env.example
  pkg/config/generate.go
  pkg/config/images.go
  pkg/config/images_test.go
Labels: approved, lgtm, size/M

#449 ensure master node is ready before moving on
  pkg/upgrade/ready.go
Labels: approved, lgtm, size/XS

#457 added a make vet target
  Makefile
Labels: approved, lgtm, size/XS

#454 Replace WaitForCompletion with WaitForCompletionRef
  pkg/upgrade/deploy.go
  pkg/upgrade/update.go
Labels: approved, lgtm, size/S

#448 don't wait 3 minutes if config blob read fails
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/checks/checks.go
  pkg/upgrade/drain.go
  pkg/upgrade/ready.go
  pkg/util/wait/wait.go
Labels: approved, lgtm, size/M

#461 fix catalog port
  pkg/addons/bindata.go
  pkg/addons/data/Service/kube-service-catalog/controller-manager.yaml
Labels: approved, lgtm, size/XS

#364 Removing name,ostype field from masterpoolprofile. Do not validate compute app matches role.
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#414 Remove configurables for derived CIs:
  cmd/createorupdate/createorupdate.go
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/derive.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/config/util.go
  pkg/util/util.go
Labels: approved, lgtm, size/L

#427 add/enable kube-state metrics
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/kube-state-metrics.yaml
  pkg/addons/data/Deployment.apps/openshift-metrics/kube-state-metrics.yaml
  pkg/addons/data/Role.rbac.authorization.k8s.io/openshift-metrics/kube-state-metrics-resizer.yaml
  pkg/addons/data/RoleBinding.rbac.authorization.k8s.io/openshift-metrics/kube-state-metrics.yaml
  pkg/addons/data/Service/openshift-metrics/kube-state-metrics.yaml
  pkg/addons/data/ServiceAccount/openshift-metrics/kube-state-metrics.yaml
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/config/images.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#458 Move imageConfig to its own struct
  Makefile
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/api/marshal.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#473 don't set a slice capacity with a negative number
  pkg/api/convertertov20180930preview.go
Labels: approved, lgtm, private-preview, size/XS

#467 allow auto-accepting Azure marketplace agreement for our image
  cmd/createorupdate/createorupdate.go
  env.example
Labels: approved, lgtm, size/M

#459 disable vanity domains for private preview
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/addons/translate.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/config/derive.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/util.go
  pkg/plugin/plugin_test.go
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, private-preview, size/L

#477 Collapse vet target in verify
  Makefile
Labels: approved, lgtm, size/XS

#468 Parsing image version.
  pkg/config/generate.go
  pkg/config/images.go
  pkg/config/images_test.go
Labels: approved, lgtm, private-preview, size/M

#460 adds FQDN validation for cluster and for router
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, private-preview, size/M

#455 This is a simple move of checks/checks.go to healthcheck/wait.go
  pkg/addons/client.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/wait.go
Labels: approved, lgtm, size/S

#478 refactor config marshalling: it was not honoring the json tag names and had
  pkg/api/marshal.go
Labels: approved, lgtm, size/L

#485 fix hack/ssh.sh
  hack/ssh.sh
Labels: approved, lgtm, size/XS

#481 Add rest of OSA team in reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#480 Increase loglevel for CI runs
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
Labels: approved, lgtm, size/S

#484 Cluster access readme update
  README.md
Labels: approved, lgtm, size/S

#491 Add a make target for coverage
  Makefile
Labels: approved, lgtm, size/XS

#493 Tag resource groups with a TTL
  hack/create.sh
Labels: approved, lgtm, size/XS

#488 Allow the region to be passed in
  env.example
  hack/create.sh
Labels: approved, lgtm, size/M

#500 Stopping and disabling rsyslog
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
Labels: approved, lgtm, size/S

#502 Add OWNERS labeling
  OWNERS
Labels: approved, lgtm, size/XS

#507 Remove acsapi
  cmd/createorupdate/createorupdate.go
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/addons/translate.go
  pkg/arm/arm.go
  pkg/config/derive.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/config/upgrade.go
  pkg/upgrade/ready.go
  pkg/util/util.go
Labels: approved, lgtm, size/L

#512 ssh add ability to pass command
  hack/ssh.sh
Labels: approved, lgtm, size/XS

#456 Simple move of validate into the api package
  cmd/sync/sync.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#503 Revert ImageConfigFormat move to derived
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/derive.go
  pkg/config/generate_test.go
  pkg/config/images.go
Labels: approved, lgtm, size/M

#511 Create image with e2e tests
  .gitignore
  Dockerfile.e2e
  Makefile
  test/e2e/extended_suite_test.go
  test/e2e/osa_test.go
Labels: approved, lgtm, size/S

#514 Add gofmt, goimports and golint checks (fix existing issues)
  Makefile
  hack/verify-code-format.sh
  pkg/api/default.go
  pkg/arm/arm.go
  pkg/config/generate.go
Labels: approved, lgtm, size/M

#515 Makefile updates
  Makefile
Labels: approved, lgtm, size/S

#518 Select LogAnalytics region based on OSA region
  pkg/api/config.go
  pkg/api/default.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/config/generate.go
  pkg/config/generate_test.go
Labels: approved, lgtm, size/M

#506 Adding reserve limits to master nodes.
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-node/node-config-master.yaml
  pkg/addons/translate.go
  pkg/api/default.go
  pkg/api/types.go
  pkg/api/validate.go
  pkg/config/derive.go
Labels: approved, lgtm, size/M

#492 Add a plugin config and set the Accept-Languages header
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/healthcheck/healthcheck.go
  pkg/initialize/client.go
  pkg/initialize/initialize.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/upgrade/deploy.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
  pkg/util/azureclient/azureclient.go
Labels: approved, lgtm, size/L

#474 Add unit tests for validateUpdateContainerService
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, size/M

#490 Add unit tests for derive
  pkg/config/derive_test.go
Labels: approved, lgtm, size/L

#510 add --no-wait to az group delete in delete.sh
  env.example
  hack/delete.sh
Labels: approved, do-not-merge/hold, size/XS

#526 Start using kubeconfig in tests vs cluster config
  test/e2e/extended_suite_test.go
  test/e2e/osa_test.go
Labels: approved, lgtm, size/S
