Repository openshift/openshift-azure, pull requests merged in 2018-10, with the labels that each got.

#535 validate cloudapp hostname using location and fix validation logic error
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, private-preview, size/M

#520 Adding tests for osa container images.
  test/e2e/osa_test.go
Labels: approved, size/M

#528 Split e2e framework to run different suites based on provided kubeconfig
  Makefile
  hack/e2e.sh
  test/e2e/admin_test.go
  test/e2e/client_test.go
  test/e2e/end_user_test.go
Labels: approved, lgtm, size/L

#533 vnet configuration rework
  README.md
  hack/create.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/util/fixtures/fixtures.go
Labels: approved, lgtm, private-preview, size/XL

#542 fix missing NetworkProfile merge
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/XS

#538 Enable end user e2e tests
  hack/e2e.sh
Labels: approved, lgtm, size/XS

#428 Add PDB e2e test
  hack/e2e.sh
  test/e2e/client_test.go
  test/e2e/conditions_test.go
  test/e2e/end_user_test.go
Labels: approved, lgtm, size/L

#549 Generate project names in e2e tests
  hack/e2e.sh
  test/e2e/end_user_test.go
  test/e2e/generator_test.go
Labels: approved, lgtm, size/M

#521 Move the call to Deploy out of createOrUpdate
  cmd/createorupdate/createorupdate.go
  pkg/addons/client.go
  pkg/api/plugin.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/wait.go
  pkg/plugin/plugin.go
  pkg/upgrade/deploy.go
  pkg/upgrade/drain.go
  pkg/upgrade/healthcheck.go
  pkg/upgrade/initialize.go
  pkg/upgrade/ready.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
  pkg/util/managedcluster/managedcluster.go
  pkg/util/wait/wait.go
Labels: approved, lgtm, size/XL

#532 Updated rfc1123 to rfc952.
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, size/S

#555 Create some unit tests for ready.go
  pkg/upgrade/ready.go
  pkg/upgrade/ready_test.go
Labels: approved, lgtm, size/L

#539 client consolidation
  cmd/createorupdate/createorupdate.go
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/addons/client.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/upgrade/initialize.go
  pkg/upgrade/ready.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/marketplaceordering.go
  pkg/util/azureclient/resources.go
  pkg/util/azureclient/storage.go
  pkg/util/azureclient/storage/storage.go
Labels: approved, lgtm, size/L

#569 Disable PDB error check in e2e
  .gitignore
  hack/e2e.sh
  test/e2e/end_user_test.go
Labels: approved, size/S

#548 Define APIVersion in the api packages
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#578 add flag for delete.sh
  hack/delete.sh
Labels: approved, lgtm, size/XS

#572 Move createOrUpdate in pkg/fakerp
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, size/L

#580 add scp hack
  hack/scp.sh
Labels: approved, lgtm, size/M

#585 add logbridge promotion
  Makefile
Labels: approved, lgtm, size/XS

#565 Replace azuredeploy []byte with template map[string]interface{}
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/upgrade/deploy.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
Labels: approved, lgtm, size/M

#587 protect against state/cursor being empty and add logging
  Makefile
  cmd/logbridge/main.go
Labels: approved, lgtm, size/M

#586 Remove redundant flag from hack scripts
  hack/create.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#588 Adding new line character to htpasswd.
  pkg/config/util.go
Labels: approved, lgtm, size/XS

#590 Miscellaneous fixes necessitated by addition of prod subscription
  .gitignore
  env.example
  hack/config.sh
  hack/create.sh
  hack/delete.sh
  hack/dns.sh
  hack/scp.sh
  hack/ssh.sh
Labels: approved, lgtm, size/M

#564 Smoke test
  hack/e2e.sh
  test/e2e/admin_test.go
  test/e2e/client_test.go
  test/e2e/conditions_test.go
  test/e2e/end_user_test.go
  test/e2e/extended_suite_test.go
Labels: approved, lgtm, size/L

#593 Generate coverage profile during unit tests
  .gitignore
  Makefile
Labels: approved, lgtm, size/S

#583 Transform fake RP into an http server
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/L

#596 Import osa go sdk
  pkg/util/azureclient/helpers.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/client.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/containerservices.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/openshiftmanagedclusters.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/operations.go
  pkg/util/azureclient/osa-go-sdk/services/containerservice/mgmt/2018-09-30-preview/containerservice/version.go
Labels: approved, lgtm, size/XXL

#597 misc usability fixes
  .gitignore
  hack/config.sh
  hack/create.sh
Labels: approved, lgtm, size/XS

#563 Use gomock to unit test
  glide.lock
  glide.yaml
  hack/validate-generated.sh
  pkg/arm/arm.go
  pkg/plugin/plugin_test.go
  pkg/upgrade/initialize.go
  pkg/upgrade/initialize_test.go
  pkg/upgrade/types.go
  pkg/util/azureclient/azureclient.go
  pkg/util/mocks/mock_arm/arm.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_azureclient/mock_storage/storage.go
  pkg/util/mocks/mock_upgrade/types.go
  vendor/github.com/golang/mock/.gitignore
  vendor/github.com/golang/mock/.travis.yml
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/README.md
  vendor/github.com/golang/mock/ci/check_go_fmt.sh
  vendor/github.com/golang/mock/ci/check_go_generate.sh
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/call_test.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/callset_test.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/controller_test.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/golang/mock/gomock/matchers_test.go
  vendor/github.com/golang/mock/gomock/mock_matcher/mock_matcher.go
Labels: approved, lgtm, size/XXL

#598 Prod RP requires name to match resource group
  hack/create.sh
Labels: approved, lgtm, size/XS

#607 Create versioned logbridge images and pass it into PluginConfig
  Makefile
  cmd/createorupdate/createorupdate.go
  env.example
  pkg/api/plugin.go
  pkg/config/images.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/S

#611 Disable autoupdate
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/admin.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/edit.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/system-aggregate-to-admin.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/system-aggregate-to-edit.yaml
  test/e2e/end_user_test.go
Labels: approved, lgtm, size/S

#610 Cache storage client keys in sync
  cmd/sync/sync.go
Labels: approved, lgtm, size/M

#612 Add unittest for wait.ForHTTPStatusOk
  pkg/util/mocks/mock_wait/wait.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
Labels: approved, lgtm, size/L

#608 Add unittests for drain
  pkg/upgrade/drain.go
  pkg/upgrade/drain_test.go
  pkg/upgrade/types.go
Labels: approved, lgtm, size/L

#630 Automate splitting imports into three different groups
  hack/verify-code-format.sh
  pkg/config/util.go
  pkg/upgrade/drain_test.go
  pkg/util/mocks/mock_arm/arm.go
  pkg/util/mocks/mock_azureclient/mock_storage/storage.go
  pkg/util/mocks/mock_upgrade/types.go
Labels: approved, lgtm, size/S

#631 Change test template
  test/e2e/end_user_test.go
Labels: approved, lgtm

#633 Support DELETE in the fake RP
  cmd/createorupdate/createorupdate.go
  hack/delete.sh
Labels: approved, lgtm, size/L

#634 Fail on pipe errors and remove tee from e2e.sh
  .gitignore
  hack/e2e.sh
Labels: approved, lgtm, size/S

#619 Don't print the diff if the object kind is Secret
  pkg/addons/client.go
  pkg/addons/client_test.go
Labels: approved, lgtm, size/M

#613 real rp e2e tests - verify customer updates not possible
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/managedapplications.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  test/e2erp/client_test.go
  test/e2erp/compute.go
  test/e2erp/realrp_test.go
Labels: approved, lgtm, size/XL

#641 Allow passing resource group as an arg in upgrade.sh
  hack/delete.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#637 Delete provisioningState before an update
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#640 Separate imports in generated code
  pkg/arm/arm.go
  pkg/upgrade/types.go
  pkg/util/azureclient/azureclient.go
  pkg/util/wait/wait.go
Labels: approved, lgtm, size/S

#639 Prod cluster test cleanup and createorupdate enhancement
  Makefile
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  hack/delete.sh
  test/e2erp/client_test.go
  test/e2erp/e2erp_suite_test.go
Labels: approved, lgtm, size/L

#646 defer cleanup of the cluster if it was requested
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/S

#649 Get debug info from end-user e2e tests
  hack/e2e.sh
  test/e2e/client_test.go
  test/e2e/end_user_test.go
  test/e2e/extended_suite_test.go
Labels: approved, lgtm, size/M

#554 Replace Getenvs in the code that ends up vendored in RP
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/derive.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#570 Dedicated admin.
  env.example
  hack/e2e.sh
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-cluster.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-project.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-reconciler.yaml
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-cluster-group.yaml
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-reconciler-admin.yaml
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-reconciler-project-admin.yaml
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-reconciler-sa.yaml
  pkg/addons/data/ConfigMap/openshift-infra/reconciler-rolebindings.yaml
  pkg/addons/data/Deployment.apps/openshift-infra/customer-admin-reconciler.yaml
  pkg/addons/data/Group.user.openshift.io/customer-admins.yaml
  pkg/addons/data/Group.user.openshift.io/customer-readers.yaml
  pkg/addons/data/ServiceAccount/openshift-infra/customer-admin-reconciler.yaml
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/generate.go
  pkg/config/generate_test.go
  test/e2e/client_test.go
  test/e2e/customer_admin_cluster_test.go
  test/e2e/customer_admin_reader_test.go
  test/e2e/end_user_test.go
  test/e2e/extended_suite_test.go
Labels: approved, lgtm, size/XL

#660 fakerp timeout extended to 1 hour
  cmd/createorupdate/createorupdate.go
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#666 Adding RunningUnderTest to Config.
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/config/generate.go
  pkg/config/generate_test.go
Labels: approved, lgtm, size/S

#665 Adding clusterservicebrokers permissions to customer-admin-cluster.
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-cluster.yaml
Labels: approved, lgtm, size/S

#624 Unit test waitForNodes
  pkg/upgrade/deploy.go
  pkg/upgrade/ready.go
  pkg/upgrade/ready_test.go
  pkg/upgrade/types.go
  pkg/upgrade/update.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/mocks/mock_azureclient/azureclient.go
Labels: approved, lgtm, size/XL

#673 remove extraneous functions from external Plugin interface
  pkg/api/plugin.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/S
