Repository openshift/openshift-azure, pull requests merged in 2018-08, with the labels that each got.

#136 Pin kubernetes dependencies used directly by us
  glide.lock
  glide.yaml
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/kube-aggregator/Godeps/Godeps.json
Labels: lgtm, size/XL

#137 update readme for delete command to add resource group which is required
  README.md
Labels: size/XS

#141 Import spew library
  glide.lock
  glide.yaml
  pkg/addons/clean_test.go
  vendor/github.com/davecgh/go-spew/.gitignore
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/cov_report.sh
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/common_test.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpnocgo_test.go
  vendor/github.com/davecgh/go-spew/spew/example_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/davecgh/go-spew/spew/spew_test.go
  vendor/github.com/davecgh/go-spew/spew/testdata/dumpcgo.go
  vendor/github.com/davecgh/go-spew/test_coverage.txt
Labels: lgtm, size/XXL

#129 Addings tests for pkg/validate.
  pkg/validate/validate_test.go
Labels: lgtm, size/L

#142 Move helper scripts in hack/
  README.md
  hack/create.sh
  hack/delete.sh
  hack/ssh.sh
  hack/upgrade.sh
Labels: lgtm, size/XS

#154 Remove unused extension type
  Makefile
  pkg/api/types.go
Labels: lgtm, size/S

#153 Nest certs
  pkg/addons/translate.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/config.go
  pkg/config/generate.go
  pkg/config/marshal.go
  pkg/healthcheck/healthcheck.go
  pkg/helm/chart/templates/Secret/sync.yaml
Labels: approved, lgtm, size/L

#152 move to internal DNS name for certs and selfsign for console/external
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/config.go
  pkg/config/generate.go
  pkg/healthcheck/healthcheck.go
  pkg/tls/tls.go
Labels: lgtm, size/M

#167 Use boostrap autoapprover service account directly
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/openshift-infra/bootstrap-autoapprover.yaml
  pkg/addons/data/Namespace/openshift-azure.yaml
  pkg/addons/data/Secret/openshift-azure/bootstrap-autoapprover-kubeconfig.yaml
  pkg/addons/data/SecurityContextConstraints.security.openshift.io/privileged.yaml
  pkg/addons/translate.go
  pkg/config/config.go
  pkg/config/generate.go
Labels: lgtm, size/L

#166 move config to internal type
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/api/config.go
  pkg/api/marshal.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/arm/arm.go
  pkg/config/generate.go
  pkg/config/upgrade.go
  pkg/healthcheck/healthcheck.go
  pkg/plugin/plugin.go
  pkg/util/util.go
Labels: approved, lgtm, size/L

#177 Logrus
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  glide.lock
  glide.yaml
  pkg/addons/addons.go
  pkg/addons/client.go
  pkg/addons/translate.go
  pkg/jsonpath/jsonpath.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/alt_exit_test.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/entry_test.go
  vendor/github.com/sirupsen/logrus/example_basic_test.go
  vendor/github.com/sirupsen/logrus/example_hook_test.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/formatter_bench_test.go
  vendor/github.com/sirupsen/logrus/hook_test.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/README.md
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog_test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test_test.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter_test.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logger_bench_test.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/logrus_test.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/text_formatter_test.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: lgtm, size/XXL

#144 Enable MSI for deployments.
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
  pkg/addons/data/Secret/default/etc-origin-cloudprovider.yaml
  pkg/addons/translate.go
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/util/util.go
Labels: lgtm, size/M

#178 Add OWNERS file
  OWNERS
Labels: lgtm, size/S

#155 move all external validation to internal and remove plugin interface …
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/plugin/plugin.go
  pkg/validate/container_service.go
  pkg/validate/openshift_cluster.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/XL

#172 Separate master pool profile on external model
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/api/converterfromosaapi.go
  pkg/api/converterfromosaapi_test.go
  pkg/api/convertertoosaapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/generate.go
  pkg/healthcheck/healthcheck.go
  pkg/validate/container_service.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#183 Add shrutir25 as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#176 add cluster-reader sa and kubeconfig
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/azure-cluster-reader.yaml
  pkg/addons/data/Namespace/openshift-azure.yaml
  pkg/addons/data/ServiceAccount/openshift-azure/azure-cluster-reader.yaml
  pkg/api/config.go
  pkg/config/generate.go
Labels: approved, lgtm, size/L

#171 Check-in dep validation script
  Makefile
  hack/validate-deps.sh
Labels: approved, lgtm, size/M

#180 custom logger
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  pkg/addons/translate.go
  pkg/arm/arm.go
  pkg/config/upgrade.go
  pkg/healthcheck/healthcheck.go
  pkg/jsonpath/jsonpath.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/L

#187 DNS fix for dev
  hack/create.sh
Labels: approved, lgtm, size/XS

#191 Updating since origin sku was removed.
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#194 change from DNS to healthcheck
  hack/create.sh
Labels: approved, lgtm, size/XS

#198 Add interface for VM readiness checks
  glide.lock
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  vendor/github.com/dimchansky/utfbom/go.mod
Labels: approved, lgtm, size/L

#197 makefile default target change
  Makefile
Labels: approved, lgtm, size/XS

#195 Api cleanup
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/api/converterfromosaapi.go
  pkg/api/converterfromosaapi_test.go
  pkg/api/convertertoosaapi.go
  pkg/api/convertertoosaapi_test.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/arm/arm.go
  pkg/checks/checks.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/upgrade.go
  pkg/healthcheck/client.go
  pkg/healthcheck/healthcheck.go
  pkg/plugin/plugin.go
  pkg/util/util.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#202 Generate capacity as number
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/XS

#203 image pull policy always admission
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#205 Debug log for service catalog api wait
  pkg/addons/addons.go
Labels: approved, lgtm, size/XS

#207 Avoid regenerating self-signed cert
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#210 Add external only flag to validation
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#200 Revert "Updating since origin sku was removed."
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#214 added human readable logging level flag
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  hack/create.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/M

#218 ensure that all prerequisite packages are vendored
  Makefile
  hack/validate-vendor.sh
Labels: approved, lgtm, size/S

#216 validation unit tests
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#221 Logging cleanup
  cmd/createorupdate/createorupdate.go
  cmd/healthcheck/healthcheck.go
  cmd/sync/sync.go
  pkg/log/log.go
Labels: approved, lgtm, size/M

#181 Merge old and new config + validate updates
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  pkg/validate/validate.go
Labels: approved, lgtm, size/M

#184 update glide dep
  Makefile
  glide.lock
  glide.yaml
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/go-test/deep/.travis.yml
  vendor/github.com/go-test/deep/deep.go
  vendor/github.com/go-test/deep/deep_test.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/codec_test.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/generator_test.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/sql_test.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/github.com/satori/go.uuid/uuid_test.go
Labels: approved, lgtm, size/XXL

#227 test generation required fields and merge
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/plugin/plugin_test.go
  pkg/util/fixtures/fixtures.go
Labels: approved, lgtm, size/L

#235 Add rhel7 as an option for env var DEEPLOY_OS
  pkg/config/generate.go
Labels: approved, lgtm, size/XS

#233 remove dns check
  pkg/checks/checks.go
  pkg/healthcheck/client.go
  pkg/healthcheck/healthcheck.go
Labels: approved, lgtm, size/M

#246 add web console cert to CAs for oauth proxy (prometheus and alert man…
  pkg/addons/bindata.go
  pkg/addons/data/Secret/openshift-metrics/alertmanager-proxy.yaml
  pkg/addons/data/Secret/openshift-metrics/alerts-proxy.yaml
  pkg/addons/data/Secret/openshift-metrics/prometheus-proxy.yaml
  pkg/addons/data/StatefulSet.apps/openshift-metrics/prometheus.yaml
  pkg/addons/translate.go
Labels: approved, lgtm, size/S

#249 add tag for purge jobs
  hack/create.sh
Labels: approved, lgtm, size/XS

#263 have sync pod look in the right resource group for its SA
  cmd/sync/sync.go
Labels: approved, size/XS

#264 update checks after changes to make fake RP responsible for deploying
  env.example
  hack/create.sh
Labels: approved, lgtm, size/S

#257 split generate
  pkg/config/generate.go
  pkg/config/images.go
  pkg/config/util.go
Labels: approved, lgtm, size/L

#259 add health check logging
  pkg/checks/checks.go
  pkg/healthcheck/healthcheck.go
Labels: approved, lgtm, size/XS

#274 glide updates
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/XS

#276 Document systemd-devel dep
  cmd/logbridge/README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#279 hide var checking
  hack/create.sh
Labels: approved, lgtm, size/XS

#282 Require and hide SP creds in upgrade.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/S

#256 Property bag/Context
  cmd/createorupdate/createorupdate.go
  cmd/createorupdate/deploy.go
  cmd/createorupdate/update.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/arm/arm.go
  pkg/config/upgrade.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, size/M

#224 extend tls.go unit test coverage
  pkg/tls/testdata/known_good_cert.pem
  pkg/tls/testdata/known_good_certCA.pem
  pkg/tls/tls_test.go
Labels: approved, lgtm, size/L

#287 correct TenantID spelling
  cmd/createorupdate/createorupdate.go
  cmd/createorupdate/deploy.go
  cmd/createorupdate/update.go
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#268 Fix restarts on services that use multiple config keys
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/addons/client.go
  pkg/addons/client_test.go
  pkg/addons/testdata/secret1.yaml
  pkg/addons/testdata/secret2.yaml
  pkg/addons/testdata/secret3.yaml
  pkg/addons/testdata/service1.yaml
  pkg/addons/testdata/service2.yaml
  pkg/addons/testdata/service3.yaml
Labels: approved, lgtm, size/L

#225 Azure Authentication integration
  cmd/createorupdate/createorupdate.go
  env.example
  hack/aad.sh
  hack/create.sh
  pkg/api/converterfromosaapi.go
  pkg/api/converterfromosaapi_test.go
  pkg/api/convertertoosaapi.go
  pkg/api/marshal.go
  pkg/api/types.go
  pkg/api/v1/marshal.go
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#294 remove output
  hack/create.sh
Labels: approved, size/S

#293 use property bag for azure client in InitializeCluster
  cmd/createorupdate/deploy.go
  pkg/initialize/client.go
Labels: approved, size/XS

#296 rename v1 to 2018-09-30-preview
  cmd/createorupdate/createorupdate.go
  pkg/api/2018-09-30-preview/api/marshal.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoosaapi_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/convertertov20180930preview_test.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/L

#272 Move autoapprover to master nodes.
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/openshift-infra/bootstrap-autoapprover.yaml
Labels: approved, lgtm, size/XS

#288 Increasing infra node and infra pod replicas
  hack/create.sh
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
  pkg/addons/data/Deployment.apps/default/router.yaml
  pkg/addons/data/Deployment.apps/openshift-web-console/webconsole.yaml
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#306 Removing hardcoded storageclass location.
  pkg/addons/bindata.go
  pkg/addons/data/StorageClass.storage.k8s.io/azure.yaml
  pkg/addons/translate.go
Labels: approved, lgtm, size/S

#308 Drop pod anti-affinity in favor of SelectorSpreadPriority
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
  pkg/addons/data/Deployment.apps/default/router.yaml
  pkg/addons/data/Deployment.apps/openshift-web-console/webconsole.yaml
Labels: approved, lgtm, size/M

#300 Remove registry init container
  cmd/sync/sync.go
  pkg/addons/addons.go
  pkg/addons/bindata.go
  pkg/addons/client.go
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
  pkg/addons/data/Secret/default/registry-config.yaml
  pkg/addons/translate.go
Labels: approved, lgtm, size/M

#278 Disallow regular users to crud PDBs
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/admin.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/edit.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/system-aggregate-to-admin.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/system-aggregate-to-edit.yaml
  pkg/upgrade/drain.go
Labels: approved, lgtm, size/M

#313 Adding js to templated variables.
  pkg/arm/bindata.go
  pkg/arm/data/azuredeploy.json
Labels: approved, lgtm, size/S

#311 self-sign console bug
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/config/generate.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/M

#312 make admin kubeconfig available on master nodes
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#254 bring internal type into line with external type
  cmd/createorupdate/createorupdate.go
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertov20180930preview.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/config/util.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/fixtures/fixtures.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: approved, lgtm, size/XXL
