Repository openshift/openshift-azure, pull requests merged in 2019-11, with the labels that each got.

#2030 Validate that VM and container versions of OCP match in pluginconfig (golang)
  Makefile
  hack/verify/validate_pluginconfig.go
  hack/verify/validate_pluginconfig_test.go
Labels: approved, lgtm, release-note-none, size/L

#2001 Private cluster work items
  cmd/monitoring/monitoring.go
  cmd/monitoring/private_api.go
  cmd/monitoring/public_api.go
  cmd/monitoring/public_apps.go
  glide.yaml
  pkg/api/plugin.go
  pkg/api/validate/types.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/arm/constants/const.go
  pkg/arm/v11/bindata.go
  pkg/arm/v11/data/master-startup.sh
  pkg/arm/v11/resources.go
  pkg/cluster/healthcheck.go
  pkg/cluster/kubeclient/syncpod.go
  pkg/config/v11/generate.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/middleware.go
  pkg/fakerp/network.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/startup/v11/bindata.go
  pkg/startup/v11/data/master/etc/origin/master/master-config.yaml
  pkg/sync/v11/sync.go
  test/e2e/standard/cluster.go
  test/sanity/sanity.go
  test/util/diagnostics/ssh.go
  vendor/github.com/apparentlymart/go-cidr/.travis.yml
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr_test.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/github.com/apparentlymart/go-cidr/go.mod
Labels: approved, lgtm, release-note, size/XXL

#2053 Add pnasrat to openshift-azure OWNERS
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#2051 Fix link to VM image releasing SOP
  docs/release.md
Labels: approved, lgtm, release-note-none, size/XS

#2054 The init() in cmd/proxy is causing unit tests to fail
  cmd/proxy/main.go
Labels: approved, lgtm, release-note-none, size/XS

#2055 Prepare for Release v11.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2052 Oms agent upgrade
  pkg/sync/v12/bindata.go
  pkg/sync/v12/data/ClusterRole.rbac.authorization.k8s.io/log-analytics-agent.yaml
  pkg/sync/v12/data/ConfigMap/openshift-azure-logging/log-analytics-cluster-agent-config.yaml
  pkg/sync/v12/data/CustomResourceDefinition.apiextensions.k8s.io/healthstates.azmon.container.insights.yaml
  pkg/sync/v12/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v12/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/sync/v12/data/Service/openshift-azure-logging/healthmodel-replicaset-service.yaml
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#2057 Add ImagePullSecret back into older worker cs
  pkg/cluster/initialize.go
  pkg/startup/startup.go
  pkg/startup/v10/startup.go
  pkg/startup/v11/startup.go
  pkg/startup/v12/startup.go
  pkg/startup/v7/startup.go
  pkg/startup/v71/startup.go
  pkg/startup/v9/startup.go
  pkg/util/mocks/mock_startup/startup.go
Labels: approved, lgtm, release-note-none, size/L

#2060 Reduce journal rotation and restart fluentd once a day
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/systemd/journald.conf
  pkg/vmimage/data/etc/systemd/system/fluentd.service
Labels: approved, lgtm, release-note-none, size/S

#2062 Remove /fakerp when running make clean
  Makefile
Labels: release-note-none, size/XS

#2063 fix and extend e-mail matching in customer-admin-controller
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note, size/M

#2050 Create the Vnet only and hash the nameservers
  hack/proxy-infrastructure/setup.go
  pkg/api/2018-09-30-preview/types_test.go
  pkg/api/2019-04-30/types_test.go
  pkg/api/2019-09-30-preview/types_test.go
  pkg/api/2019-10-27-preview/converterfrominternal.go
  pkg/api/2019-10-27-preview/convertertointernal.go
  pkg/api/2019-10-27-preview/convertertointernal_test.go
  pkg/api/2019-10-27-preview/types.go
  pkg/api/2019-10-27-preview/types_test.go
  pkg/api/admin/converterfrominternal.go
  pkg/api/admin/convertertointernal.go
  pkg/api/admin/convertertointernal_test.go
  pkg/api/admin/types.go
  pkg/api/admin/types_test.go
  pkg/api/mock.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/arm/constants/const.go
  pkg/arm/v10/arm.go
  pkg/arm/v11/arm.go
  pkg/arm/v12/arm.go
  pkg/arm/v7/arm.go
  pkg/arm/v71/arm.go
  pkg/arm/v9/arm.go
  pkg/cluster/nameservers.go
  pkg/cluster/types.go
  pkg/entrypoint/startup/startup.go
  pkg/fakerp/arm/arm.go
  pkg/plugin/integration_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/startup/nameservers.go
  pkg/startup/nameservers_test.go
  pkg/startup/v12/bindata.go
  pkg/startup/v12/data/master/etc/origin/node/resolv.conf
  pkg/startup/v12/data/worker/etc/origin/node/resolv.conf
  pkg/startup/v12/startup.go
  pkg/util/arm/arm.go
  pkg/util/arm/arm_test.go
  pkg/util/azureclient/fake/cloud.go
  pkg/util/azureclient/fake/network/codecov_dummy_test.go
  pkg/util/azureclient/fake/network/virtualnetworks.go
  pkg/util/mocks/mock_cluster/types.go
  pkg/vmimage/vmimage.go
  test/manifests/fakerp/admin-update.yaml
Labels: approved, lgtm, release-note-none, size/XL

#2068 v12.0 images and changelog
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2077 Update OMS agent to ciprod11012019
  pkg/sync/v13/bindata.go
  pkg/sync/v13/data/ClusterRole.rbac.authorization.k8s.io/log-analytics-agent.yaml
  pkg/sync/v13/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v13/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/S

#2073 Updating image version to 311.153.20191113 and create 10.2
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, release-note, size/M

#2081 revert f66053121e8fd74acb6b40c0837471c3de5083f3 - it is a case study of premature optimisation
  pkg/sync/v13/sync.go
Labels: approved, lgtm, release-note-none, size/M

#2074 Updating image version to 311.153.20191113 and create 12.1
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2075 Updating to 311.153.20191113 and creating v10.2,v12.1
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/L

#2082 Fixing the pluginversion with v10.2
  pkg/cluster/hash_test.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/systemd/journald.conf
  pkg/vmimage/data/etc/systemd/system/fluentd.service
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2065 Restart a vm geneva action
  pkg/api/plugin.go
  pkg/cluster/admin_actions.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, release-note-none, size/M

#2089 Updating image release with v12.2
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#2088 Updating image for v12.2
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2093 Move GetPrivateAPIServerIPAddress into GenerateConfig
  pkg/api/plugin.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/config/v12/generate.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/enrich/enrich.go
  pkg/util/enrich/enrich_test.go
Labels: approved, lgtm, release-note, size/L

#2095 V12.2 pluginconfig and changelog
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2090 Move GetPrivateAPIServerIPAddress into GenerateConfig
  pkg/api/plugin.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/config/v12/generate.go
  pkg/config/v13/generate.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/enrich/enrich.go
  pkg/util/enrich/enrich_test.go
Labels: approved, lgtm, release-note, size/L

#2096 Adding test for restart action
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, release-note-none, size/M

#2100 update twistlock regex
  pkg/startup/v13/bindata.go
  pkg/startup/v13/data/master/etc/aro-admission-controller/aro-admission-controller.yaml
Labels: approved, release-note-none, size/XS

#2103 Prep v13 release
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2108 Update resource group and resource names in appinsights.md
  docs/e2e/appinsights.md
Labels: lgtm, release-note-none, size/XS

#2111 remove label from OWNERS
  OWNERS
Labels: release-note-none, size/XS

#2114 setup-rbac typo
  hack/setup-rbac/main.go
Labels: release-note-none
