Repository openshift/openshift-azure, pull requests merged in 2019-08, with the labels that each got.

#1831 Make sure we can update Geneva and PackageRepository Secrets
  pkg/api/plugin/convertertointernal.go
  pkg/api/plugin/convertertointernal_test.go
Labels: approved, lgtm, release-note, size/L

#1830 Fixing issues found by gosec
  cmd/monitoring/monitoring.go
  cmd/releasenotes/releasenotes.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/store/store.go
  pkg/vmimage/ssh.go
  test/clients/openshift/dumpinfo.go
  test/e2e/specs/fakerp/metricsbridge.go
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, release-note-none, size/S

#1820 Introduce gosec for security checks
  Makefile
  hack/verify/validate-sec.sh
Labels: approved, lgtm, release-note-none, size/XS

#1834 remove tenant flag and os.exit(1) from arm scripts
  hack/tests/ci-prepare.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/validate.sh
Labels: approved, lgtm, release-note-none, size/XS

#1835 Fixing scap by removing audispd failures
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/ssg-rhel7-ds-aro.xml
Labels: approved, lgtm, release-note-none, size/XS

#1837 minor fixes found while debugging hash changes
  pkg/arm/v7/arm.go
  pkg/cluster/hash.go
  pkg/plugin/integration_test.go
  pkg/startup/v7/startup.go
Labels: approved, lgtm, release-note-none, size/S

#1838 Create new VMImage with mdsd/azsecd/azsecmond
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/rc.d/rc.local
  pkg/vmimage/data/etc/yum.repos.d/kickstart.repo
  pkg/vmimage/data/script.sh
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note, size/M

#1836 Adds SCAP checks back
  hack/vmimage-validate.sh
  hack/vmimage.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/validate.sh
Labels: approved, lgtm, release-note-none, size/S

#1821 Adds a check for pending security updates
  hack/vmimage-validate.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/validate.sh
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/M

#1840 install golang 1.11 from source
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1843 Fix GOPATH for local go binaries in vmimage script
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/XS

#1817 Moving geneva logging to the host + azsecpack
  pkg/arm/v7/bindata.go
  pkg/arm/v7/data/master-startup.sh
  pkg/arm/v7/data/node-startup.sh
  pkg/cluster/initialize.go
  pkg/startup/v7/bindata.go
  pkg/startup/v7/data/common/etc/default/mdsd
  pkg/startup/v7/data/common/etc/fluentd/fluent.conf
  pkg/startup/v7/data/common/etc/mdsd.d/mdsd.xml
  pkg/startup/v7/data/common/etc/mdsd.d/secret/gcscert.pem
  pkg/startup/v7/data/common/etc/mdsd.d/secret/gcskey.pem
  pkg/startup/v7/derive.go
  pkg/startup/v7/startup.go
  pkg/sync/v7/bindata.go
  pkg/sync/v7/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/sync/v7/data/ConfigMap/openshift-azure-logging/mdsd-config.yaml
  pkg/sync/v7/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/sync/v7/data/Namespace/openshift-azure-logging.yaml
  pkg/sync/v7/data/Secret/openshift-azure-logging/azure-registry.yaml
  pkg/sync/v7/data/Secret/openshift-azure-logging/gcs-cert.yaml
  pkg/sync/v7/data/SecurityContextConstraints.security.openshift.io/privileged.yaml
  pkg/sync/v7/data/ServiceAccount/openshift-azure-logging/geneva.yaml
  pkg/sync/v7/derive.go
  pkg/sync/v7/translate.go
  pkg/util/template/template.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/XL

#1849 rename secret
  README.md
  hack/aad.sh
Labels: approved, lgtm, release-note-none, size/XS

#1851 Prepare v7.0 release
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#1842 Create dir /var/crash if it does not exist.
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/rc.d/rc.local
Labels: approved, lgtm, release-note-none, size/XS

#1850 gobindata remove pin
  hack/verify/validate-generated.sh
  pkg/arm/v5/bindata.go
  pkg/arm/v6/bindata.go
  pkg/arm/v7/bindata.go
  pkg/startup/v5/bindata.go
  pkg/startup/v6/bindata.go
  pkg/startup/v7/bindata.go
  pkg/sync/v5/bindata.go
  pkg/sync/v6/bindata.go
  pkg/sync/v7/bindata.go
  pkg/vmimage/bindata.go
Labels: approved, lgtm, release-note-none, size/L

#1845 Allows make vmimage-validate to validate published marketplace vmimages
  cmd/vmimage/vmimage.go
  hack/vmimage-validate.sh
  pkg/vmimage/resources.go
  pkg/vmimage/vmimage.go
  pkg/vmimage/vmimage_test.go
Labels: approved, lgtm, release-note-none, size/L

#1856 Fixes make verify
  hack/verify/validate-generated.sh
  pkg/arm/v8/bindata.go
  pkg/startup/v8/bindata.go
  pkg/sync/v8/bindata.go
Labels: approved, lgtm, release-note-none, size/M

#1853 Update release process documentation
  docs/release.md
Labels: approved, lgtm, release-note-none, size/L

#1861 fix tlsproxy
  pkg/entrypoint/tlsproxy/tlsproxy.go
Labels: approved, lgtm, release-note-none, size/S

#1833 Delay VM Reboot After Security Updates to Prevent Race with Kubelet
  pkg/arm/v8/bindata.go
  pkg/arm/v8/data/master-startup.sh
  pkg/arm/v8/data/node-startup.sh
Labels: approved, lgtm, release-note, size/S

#1854 add DisableOutboundSNAT for cloudconfig
  pkg/startup/v5/derive.go
  pkg/startup/v6/derive.go
  pkg/startup/v7/derive.go
  pkg/startup/v8/derive.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/derived/derived.go
  pkg/util/derived/derived_test.go
Labels: approved, lgtm, release-note, size/M

#1860 Removes unused code
  pkg/util/azureclient/managedapplications/applications.go
  pkg/util/azureclient/managedapplications/codecov_dummy_test.go
  pkg/util/azureclient/marketplaceordering/codecov_dummy_test.go
  pkg/util/azureclient/marketplaceordering/marketplaceagreements.go
  pkg/util/mocks/mock_azureclient/mock_managedapplications/managedapplications.go
  pkg/util/mocks/mock_azureclient/mock_marketplaceordering/marketplaceordering.go
  test/clients/azure/client.go
Labels: approved, lgtm, release-note-none, size/L

#1865 Additions to Customer Logging & Monitoring
  pkg/arm/v8/bindata.go
  pkg/arm/v8/data/master-startup.sh
  pkg/arm/v8/data/node-startup.sh
  pkg/sync/v8/bindata.go
  pkg/sync/v8/data/ClusterRole.rbac.authorization.k8s.io/log-analytics-agent.yaml
  pkg/sync/v8/data/ClusterRoleBinding.rbac.authorization.k8s.io/log-analytics-agent.yaml
  pkg/sync/v8/data/ConfigMap/openshift-azure-logging/container-azm-ms-agentconfig.yaml
  pkg/sync/v8/data/ConfigMap/openshift-azure-logging/log-analytics-agent-entrypoint.yaml
  pkg/sync/v8/data/ConfigMap/openshift-azure-logging/log-analytics-cluster-agent-config.yaml
  pkg/sync/v8/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v8/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/sync/v8/data/SecurityContextConstraints.security.openshift.io/privileged.yaml
  pkg/sync/v8/data/ServiceAccount/openshift-azure-logging/log-analytics-agent.yaml
  pkg/sync/v8/translate.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/L

#1844 Improve the docker pull retries in the startup script
  pkg/arm/v8/bindata.go
  pkg/arm/v8/data/master-startup.sh
  pkg/arm/v8/data/node-startup.sh
Labels: approved, lgtm, release-note-none, size/M

#1869 Updated groupadd to not fail when group exists.
  pkg/arm/v8/bindata.go
  pkg/arm/v8/data/master-startup.sh
  pkg/arm/v8/data/node-startup.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1867 Add log analytics rsyslog config file for deterministic syslog forwarding
  pkg/sync/v8/bindata.go
  pkg/sync/v8/data/ConfigMap/openshift-azure-logging/log-analytics-rsyslog-config.yaml
  pkg/sync/v8/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
Labels: approved, lgtm, release-note-none, size/M

#1863 Add some assertions to prove update reentrancy
  test/e2e/specs/fakerp/loglevel.go
  test/e2e/specs/fakerp/setcontainerimage.go
Labels: approved, lgtm, release-note-none, size/M

#1874 Rename api 2019-08-31 to 2019-09-30-preview as requested by MSFT
  cmd/createorupdate/createorupdate.go
  pkg/api/2019-09-30-preview/converterfrominternal.go
  pkg/api/2019-09-30-preview/converterfrominternal_test.go
  pkg/api/2019-09-30-preview/convertertointernal.go
  pkg/api/2019-09-30-preview/convertertointernal_test.go
  pkg/api/2019-09-30-preview/default.go
  pkg/api/2019-09-30-preview/default_test.go
  pkg/api/2019-09-30-preview/marshal.go
  pkg/api/2019-09-30-preview/types.go
  pkg/api/2019-09-30-preview/types_test.go
  pkg/fakerp/client/manifest.go
  pkg/fakerp/server.go
  pkg/fakerp/util.go
  pkg/util/azureclient/openshiftmanagedcluster/2019-09-30-preview/client.go
  pkg/util/azureclient/openshiftmanagedcluster/2019-09-30-preview/codecov_dummy_test.go
  test/clients/azure/client.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, release-note, size/L

#1876 Make sure the allowed admin config update pass through
  pkg/api/plugin/convertertointernal.go
  pkg/api/validate/admin.go
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note, size/S

#1882 Add check for checksum for downloaded golang binary
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/XS

#1878 Use RoundTripper in the sync pod
  pkg/sync/v8/sync.go
Labels: approved, lgtm

#1879 make IsMatchingSyscallError() more flexible
  pkg/util/errors/errors.go
  pkg/util/errors/errors_test.go
Labels: approved, lgtm, release-note-none, size/M

#1886 fakerp: create clients in one place and use envconfig more
  pkg/fakerp/client/config.go
  pkg/fakerp/clients.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/vault.go
Labels: approved, lgtm, release-note-none, size/L

#1872 Modifying vmimage script to use the upstream
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1885 remove unused netHTTPErrorPrefixLen
  pkg/util/errors/errors.go
Labels: approved, lgtm, release-note-none, size/XS

#1887 Avoid generating new certs in the integration tests
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note-none, size/S

#1875 Enabling boot diagnostics on all VMSS
  pkg/arm/v8/resources.go
Labels: approved, lgtm, release-note, size/XS

#1884 Fix fakerp "trap" and used azureclient.resources.Group
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  hack/delete.sh
  hack/e2e.sh
  hack/etcdrecovery.sh
  hack/upgrade.sh
  pkg/fakerp/client/groups.go
  pkg/util/azureclient/resources/groups.go
  pkg/util/mocks/mock_azureclient/mock_resources/resources.go
Labels: approved, lgtm, release-note-none, size/M

#1891 fixing small syntax error in hack/delete.sh
  hack/delete.sh
Labels: approved, lgtm, release-note-none, size/XS

#1880 Document local testing
  docs/e2e/requirements.md
  docs/testing.md
Labels: approved, lgtm, release-note-none, size/M

#1883 Add ci-notify to vmimage build.
  hack/ci-notify/codecov_dummy_test.go
  hack/ci-notify/main.go
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/L

#1899 Fix vmimage build quotes.
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/XS
