Repository openshift/openshift-azure, pull requests merged in 2019-09, with the labels that each got.

#1904 Avoid VM image build timeout
  pkg/vmimage/resources.go
  pkg/vmimage/vmimage.go
Labels: approved, release-note-none, size/XS

#1911 [v8] fix group sync
  pkg/sync/v8/bindata.go
  pkg/sync/v8/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-controller.yaml
Labels: approved, lgtm, release-note, size/XS

#1910 [master] fix groups sync rbac
  pkg/cluster/hash_test.go
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-controller.yaml
Labels: approved, lgtm, release-note, size/XS

#1912 Fix pluginconfig.pluginVersion -> v9
  pkg/cluster/hash_test.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#1902 Adds CI notifications into vmimage-validate
  hack/tests/ci-prepare.sh
  hack/vmimage-validate.sh
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/S

#1915 Update container versions for v8 release
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#1916 Update image versions in plugin config for v8/v9
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#1920 Clean up startup.writeFiles() and add tests
  pkg/startup/v9/startup.go
  pkg/startup/v9/startup_test.go
Labels: approved, lgtm, release-note-none, size/L

#1917 [master] logging fix
  pkg/arm/v9/bindata.go
  pkg/arm/v9/data/master-startup.sh
  pkg/arm/v9/data/node-startup.sh
  pkg/startup/v7/startup.go
  pkg/startup/v8/startup.go
Labels: approved, lgtm, release-note, size/S

#1929 Fix Log Analytics' scraping of Customer's Prometheus Workloads
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/ConfigMap/openshift-azure-logging/container-azm-ms-agentconfig.yaml
Labels: approved, lgtm, release-note, size/S

#1925 Move vm image building to rhel 7.7
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note, size/XS

#1926 fixing RG in the metrics-bridge
  pkg/sync/v9/sync_test.go
  pkg/sync/v9/translate.go
Labels: approved, lgtm, release-note-none, size/XS

#1930 Fix for the MDSD logging issues
  pkg/cluster/hash_test.go
  pkg/cluster/initialize.go
  pkg/startup/v9/bindata.go
  pkg/startup/v9/data/common/etc/mdsd.d/mdsd.xml
  pkg/startup/v9/derive.go
Labels: approved, lgtm, release-note, size/S

#1938 Fix Azure Monitor Cluster UX Tab
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v9/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/sync/v9/translate.go
Labels: approved, lgtm, release-note, size/S

#1941 Fix content_test.go after openshift/api update
  Makefile
  pkg/sync/v9/content_test.go
Labels: approved, lgtm, release-note-none, size/XS

#1945 Remove unused PluginSteps
  pkg/api/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1937 Support multiple AAD reply urls per AAD App
  cmd/createorupdate/createorupdate.go
  pkg/util/aadapp/aadapp.go
  pkg/util/azureclient/graphrbac/applications.go
  pkg/util/mocks/mock_azureclient/mock_graphrbac/graphrbac.go
Labels: approved, lgtm, release-note-none, size/L

#1931 Use Iptables to restrict access to Worker Kubelet read-only port
  pkg/arm/v9/bindata.go
  pkg/arm/v9/data/node-startup.sh
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
Labels: approved, lgtm, release-note, size/S

#1948 VMImage improvements
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/audit/rules.d/scap.rules
Labels: approved, lgtm, release-note-none, size/XS

#1946 Not allowing 2 infra nodes anymore. Only accepting 3.
  pkg/api/validate/admin_test.go
  pkg/api/validate/validators.go
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note, size/S

#1947 Fix multiple aad urls single-cluster case
  cmd/createorupdate/createorupdate.go
  pkg/util/aadapp/aadapp.go
Labels: approved, lgtm, release-note-none, size/M

#1943 Log Analytics workspace key should be retrieved and set by fake RP
  pkg/fakerp/clients.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v9/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/util/enrich/enrich.go
Labels: approved, lgtm, release-note, size/M

#1934 Add strimzi (AMQ Streams operator)
  pkg/sync/v9/bindata.go
  pkg/sync/v9/content_test.go
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-admin.yaml
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-cluster-operator-global.yaml
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-cluster-operator-namespaced.yaml
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-entity-operator.yaml
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-kafka-broker.yaml
  pkg/sync/v9/data/ClusterRole.rbac.authorization.k8s.io/strimzi-topic-operator.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-strimzi.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/strimzi-cluster-operator-entity-operator-delegation.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/strimzi-cluster-operator-global.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-broker-delegation.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/strimzi-cluster-operator-namespaced.yaml
  pkg/sync/v9/data/ClusterRoleBinding.rbac.authorization.k8s.io/strimzi-cluster-operator-topic-operator-delegation.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkabridges.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkaconnects.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkaconnects2is.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkamirrormakers.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkas.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io.yaml
  pkg/sync/v9/data/CustomResourceDefinition.apiextensions.k8s.io/kafkausers.kafka.strimzi.io.yaml
  pkg/sync/v9/data/Deployment.apps/openshift-infra/strimzi-cluster-operator.yaml
  pkg/sync/v9/data/ServiceAccount/openshift-infra/strimzi-cluster-operator.yaml
  pkg/sync/v9/data/Template.template.openshift.io/openshift/strimzi-connect-s2i.yaml
  pkg/sync/v9/data/Template.template.openshift.io/openshift/strimzi-connect.yaml
  pkg/sync/v9/data/Template.template.openshift.io/openshift/strimzi-ephemeral.yaml
  pkg/sync/v9/data/Template.template.openshift.io/openshift/strimzi-mirror-maker.yaml
  pkg/sync/v9/data/Template.template.openshift.io/openshift/strimzi-persistent.yaml
  test/clients/openshift/strimzi.go
  test/e2e/specs/strimzi.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
  test/manifests/kafka/ephemeral-template.yaml
Labels: approved, lgtm, release-note, size/XXL

#1953 remove unused PluginStepEnrichMonitorProfile
  pkg/api/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1954 Add unit test file for passwd in envars
  pkg/arm/v9/bindata.go
  pkg/arm/v9/data/master-startup.sh
  pkg/arm/v9/data/node-startup.sh
  pkg/sync/v9/envpass_test.go
Labels: approved, lgtm, release-note-none, size/L

#1959 Removing assignee from issue creation.
  hack/ci-notify/main.go
Labels: approved, lgtm, release-note-none, size/XS

#1914 make group mapping more robust
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
  pkg/util/mail/codecov_dummy_test.go
  pkg/util/mail/mail.go
  pkg/util/mail/mail_test.go
Labels: approved, lgtm, release-note-none, size/L

#1951 MDSD + azsec-clamav
  pkg/arm/v9/bindata.go
  pkg/arm/v9/data/master-startup.sh
  pkg/arm/v9/data/node-startup.sh
  pkg/startup/v9/bindata.go
  pkg/startup/v9/data/common/etc/azsec/azsecmon-audit.rules
  pkg/startup/v9/data/common/etc/mdsd.d/mdsd.xml
  pkg/startup/v9/startup.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1962 Revert "Use Iptables to restrict access to Worker Kubelet read-only port"
  pkg/arm/v9/bindata.go
  pkg/arm/v9/data/node-startup.sh
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
Labels: approved, lgtm, release-note-none, size/S

#1963 Fix fakerp ensure resource group flake
  pkg/fakerp/client/groups.go
Labels: approved, lgtm, release-note-none, size/S

#1957 Verify that customer-admins can update the azure monitor agents' prometheus config
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note-none, size/S

#1964 Fixes failure to cat yum_updateinfo_list_security log in make vmimage-validate
  hack/vmimage-validate.sh
Labels: approved, lgtm, release-note-none, size/XS

#1966 add enabled flag to monitorProfile (based on work by charlesakalugwu)
  pkg/api/2019-09-30-preview/converterfrominternal.go
  pkg/api/2019-09-30-preview/convertertointernal.go
  pkg/api/2019-09-30-preview/types.go
  pkg/api/2019-09-30-preview/types_test.go
  pkg/api/admin/converterfrominternal.go
  pkg/api/admin/convertertointernal.go
  pkg/api/admin/types.go
  pkg/api/admin/types_test.go
  pkg/api/mock.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/api.go
  pkg/api/validate/types.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/plugin/integration_test.go
  pkg/sync/v9/bindata.go
  pkg/sync/v9/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v9/translate.go
  test/manifests/fakerp/create.yaml
Labels: approved, lgtm, release-note, size/L

#1968 release v9.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: release-note-none

#1969 Revert "release v9.0"
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: do-not-merge/release-note-label-needed

#1970 release v9.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: release-note-none

#1971 correct warning message
  hack/upgrade.sh
Labels: approved, lgtm, release-note-none, size/XS

#1974 remove y-cote and pweil- from OWNERS
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1967 Improves make vmimage-validate locally
  pkg/vmimage/ssh.go
Labels: approved, lgtm, release-note-none, size/XS

#1973 Make the way we get the latest dev version more reliable and run "make content"
  Makefile
  hack/dev-version/codecov_dummy_test.go
  hack/dev-version/dev-version.go
  hack/dev-version/dev-version_test.go
  pkg/sync/v10/bindata.go
  pkg/sync/v10/data/ImageStream.image.openshift.io/openshift/ruby.yaml
  pkg/sync/v10/data/Template.template.openshift.io/openshift/jenkins-ephemeral-monitored.yaml
  pkg/sync/v10/data/Template.template.openshift.io/openshift/jenkins-persistent-monitored.yaml
  pkg/sync/v10/data/Template.template.openshift.io/openshift/sso-cd-x509-https.yaml
Labels: approved, lgtm, release-note-none, size/XL

#1978 Improve the validation of setcontainerimage
  test/e2e/specs/fakerp/setcontainerimage.go
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/M

#1979 Update upstream versions
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#1977 Store the workspace key in the secret
  pkg/sync/v10/bindata.go
  pkg/sync/v10/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v10/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/sync/v10/data/Secret/openshift-azure-logging/log-analytics.yaml
  pkg/sync/v10/translate.go
  test/manifests/fakerp/create.yaml
Labels: approved, lgtm, release-note, size/M
