Repository openshift/openshift-azure, pull requests merged in 2019-06, with the labels that each got.

#1691 individual artifact gathering on test failures
  test/clients/openshift/dumpinfo.go
  test/e2e/specs/osba_app.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
  test/e2e/standard/testapps.go
Labels: approved, lgtm, release-note-none, size/L

#1694 Add prometheus instrumentation to sync
  pkg/entrypoint/sync/sync.go
Labels: approved, lgtm, release-note-none, size/M

#1698 Add labels to sync's service spec
  pkg/cluster/kubeclient/syncpod.go
Labels: approved, lgtm, release-note-none, size/XS

#1682 Default timeouts in RoundTrippers' http transports
  pkg/cluster/kubeclient/roundtrip.go
  test/clients/openshift/client.go
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/M

#1705 Add remaining install config entries
  cmd/azure/azure.go
Labels: approved, lgtm, release-note-none, size/M

#1706 Openshift v4 export OPENSHIFT_INSTALL_DATA
  .gitignore
  cmd/azure/azure.go
  hack/create.sh
Labels: approved, lgtm, release-note-none, size/S

#1707 Initialise the plugins
  cmd/azure/azure.go
Labels: approved, lgtm, release-note-none, size/S

#1713 Add a role for prometheus-k8s' serviceaccount to openshift-infra
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/Role.rbac.authorization.k8s.io/openshift-infra/prometheus-k8s.yaml
  pkg/sync/v6/data/RoleBinding.rbac.authorization.k8s.io/openshift-infra/prometheus-k8s.yaml
Labels: approved, lgtm, release-note, size/M

#1712 Openshift v4 subnet fix
  .gitignore
  Makefile
  hack/verify/validate-code-format.sh
  vendor/github.com/aws/aws-sdk-go/aws/context.go
  vendor/github.com/aws/aws-sdk-go/aws/context_1_6.go
  vendor/github.com/aws/aws-sdk-go/aws/context_1_7.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
  vendor/github.com/aws/aws-sdk-go/service/sts/customizations.go
  vendor/github.com/mattn/go-isatty/isatty_appengine.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/golang.org/x/crypto/poly1305/sum_ref.go
  vendor/golang.org/x/net/idna/idna.go
  vendor/golang.org/x/net/idna/tables.go
  vendor/golang.org/x/sys/unix/openbsd_pledge.go
  vendor/golang.org/x/sys/unix/openbsd_unveil.go
  vendor/golang.org/x/text/language/common.go
  vendor/golang.org/x/text/language/gen_common.go
  vendor/golang.org/x/text/language/gen_index.go
  vendor/golang.org/x/text/language/index.go
  vendor/golang.org/x/text/language/lookup.go
  vendor/golang.org/x/time/rate/rate_go16.go
  vendor/golang.org/x/time/rate/rate_go17.go
Labels: approved, lgtm, release-note-none, size/XXL

#1716 Add myself as an approver
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1687 Add race detection to e2e tests
  hack/e2e.sh
  pkg/sync/v6/sync.go
Labels: approved, lgtm, release-note-none, size/M

#1721 Add --all flag to git add in content-update script
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note, size/XS

#1714 Label sync and azure-controllers in conformance to CMO expectations
  pkg/cluster/kubeclient/syncpod.go
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/Role.rbac.authorization.k8s.io/openshift-infra/prometheus-k8s.yaml
  pkg/sync/v6/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/azure-controllers.yaml
  pkg/sync/v6/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/sync.yaml
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, release-note, size/S

#1718 V4 - destroyer fix and backport small backports
  images/azure/Dockerfile
  pkg/api/plugin.go
  vendor/github.com/openshift/installer/pkg/destroy/aws.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/register.go
  vendor/github.com/openshift/installer/pkg/destroy/azure/azure.go
Labels: approved, lgtm, release-note-none, size/L

#1709 enabling Sync pod test on EveryPR
  test/e2e/specs/fakerp/sync.go
Labels: approved, lgtm, release-note-none, size/XS

#1724 v4 - Add housekeeping logic
  Gopkg.lock
  Gopkg.toml
  README.md
  hack/ssh.sh
  pkg/api/plugin.go
  pkg/fakerp/config/config.go
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/envconfig_1.8_test.go
  vendor/github.com/kelseyhightower/envconfig/envconfig_test.go
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/github.com/kelseyhightower/envconfig/testdata/custom.txt
  vendor/github.com/kelseyhightower/envconfig/testdata/default_list.txt
  vendor/github.com/kelseyhightower/envconfig/testdata/default_table.txt
  vendor/github.com/kelseyhightower/envconfig/testdata/fault.txt
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/github.com/kelseyhightower/envconfig/usage_test.go
Labels: approved, lgtm, release-note-none, size/XXL

#1727 Openshift v4
  vendor/github.com/openshift/installer/pkg/asset/machines/azure/machines.go
  vendor/github.com/openshift/installer/pkg/destroy/azure/azure.go
Labels: approved, lgtm, release-note-none, size/M

#1731 Release v5.2
  CHANGELOG.md
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#1725 Bumping image version to 311.104.20190617
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1735 Use separate prometheus registry for sync metrics
  pkg/entrypoint/sync/sync.go
Labels: approved, lgtm, release-note-none, size/S

#1737 Deleting docs/vmimage.md - moved to azure-sop
  docs/vmimage.md
Labels: approved, lgtm, release-note-none, size/S

#1738 Revert "Add default router profile to real rp sample manifest"
  test/manifests/realrp/create.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1697 send output from unit tests to app insights
  Makefile
  cmd/testinsights/codecov_dummy_test.go
  cmd/testinsights/testinsights.go
Labels: approved, lgtm, release-note-none, size/L

#1722 Push sync metrics to geneva
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1742 Revert docker build strategy restriction
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ClusterRoleBinding.rbac.authorization.k8s.io/system-build-strategy-docker-binding.yaml
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note, size/M

#1671 image hardening
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/audit/rules.d/scap.rules
  pkg/vmimage/data/etc/issue
  pkg/vmimage/data/etc/rc.d/rc.local
  pkg/vmimage/data/etc/ssh/sshd_config
  pkg/vmimage/data/etc/sysctl.d/99-openshift.conf
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/auditd.service
  pkg/vmimage/data/script.sh
  pkg/vmimage/data/validate.sh
  pkg/vmimage/resources.go
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note, size/L

#1670 e2e tests: implement e2e test for emptydir quotas
  pkg/arm/v6/bindata.go
  pkg/arm/v6/data/master-startup.sh
  pkg/arm/v6/data/node-startup.sh
  pkg/startup/v6/bindata.go
  pkg/startup/v6/data/worker/etc/origin/node/node-config.yaml
  pkg/startup/v6/data/worker/etc/origin/node/volume-config.yaml
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/L

#1744 v4: Misc small fixes
  Makefile
  pkg/api/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1747 gitignore: add the testinsights binary to the list
  .gitignore
Labels: approved, lgtm, release-note-none, size/XS

#1740 Entrypoint for conformance test
  hack/tests/origin-conformance.sh
Labels: approved, lgtm, release-note-none, size/M

#1749 Adding FIPS mode
  cmd/vmimage/vmimage.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note, size/L

#1751 [v4] Revendor and small fixes
  pkg/api/plugin.go
  pkg/fakerp/config/config.go
  vendor/github.com/openshift/installer/.github/ISSUE_TEMPLATE.md
  vendor/github.com/openshift/installer/cmd/openshift-install/destroy.go
  vendor/github.com/openshift/installer/cmd/openshift-install/gather.go
  vendor/github.com/openshift/installer/data/data/azure/bootstrap/main.tf
  vendor/github.com/openshift/installer/data/data/azure/bootstrap/variables.tf
  vendor/github.com/openshift/installer/data/data/azure/main.tf
  vendor/github.com/openshift/installer/data/data/azure/master/master.tf
  vendor/github.com/openshift/installer/data/data/azure/master/variables.tf
  vendor/github.com/openshift/installer/data/data/azure/vnet/nsg.tf
  vendor/github.com/openshift/installer/data/data/azure/vnet/outputs.tf
  vendor/github.com/openshift/installer/data/data/azure/vnet/public-lb.tf
  vendor/github.com/openshift/installer/data/data/azure/vnet/variables.tf
  vendor/github.com/openshift/installer/pkg/asset/cluster/tfvars.go
  vendor/github.com/openshift/installer/pkg/asset/machines/master.go
  vendor/github.com/openshift/installer/pkg/asset/machines/worker.go
  vendor/github.com/openshift/installer/pkg/destroy/aws.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/doc.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/register.go
  vendor/github.com/openshift/installer/pkg/destroy/azure/azure.go
  vendor/github.com/openshift/installer/pkg/destroy/bootstrap/doc.go
  vendor/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go
  vendor/github.com/openshift/installer/pkg/destroy/openstack/openstack.go
  vendor/github.com/openshift/installer/pkg/terraform/gather/azure/ip.go
  vendor/github.com/openshift/installer/pkg/tfvars/azure/azure.go
  vendor/github.com/openshift/installer/pkg/types/azure/defaults/machines.go
  vendor/github.com/openshift/installer/pkg/types/azure/defaults/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/defaults/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/gcp/defaults/platform.go
  vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  vendor/github.com/openshift/installer/pkg/types/gcp/validation/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/gcp/validation/machinepool_test.go
  vendor/github.com/openshift/installer/pkg/types/gcp/validation/platform.go
  vendor/github.com/openshift/installer/pkg/types/gcp/validation/platform_test.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/validation/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/validation/installconfig_test.go
Labels: approved, lgtm, release-note-none, size/XL

#1752 Make the AAD sync test more robust
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note-none, size/S

#1756 Update allowed cluster names to match ARM validation
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/S

#1757 Update allowed cluster names to match ARM validation (cherry-pick)
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note-none, size/S
