Repository openshift/openshift-azure, pull requests merged in 2019-02, with the labels that each got.

#1081 Allow the sync pod to be run locally for development
  pkg/arm/resources.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, size/M

#1083 Ignore files generated/used by cscope.
  .gitignore
Labels: approved, lgtm, size/XS

#1084 Make controllers scrapable by Prometheus and add test to ensure we don't miss this again.
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  test/clients/openshift/serviceaccount.go
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, size/L

#1088 fix ssh script
  hack/ssh.sh
Labels: approved, lgtm, size/S

#1090 ILB creation issue
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/util/cloudprovider/cloudprovider.go
Labels: approved, lgtm, size/XS

#1094 Fix var interpolation inside of awk statement
  Makefile
Labels: approved, lgtm, size/XS

#1098 Fix makefile for debian-based systems
  Makefile
Labels: approved, lgtm, size/XS

#1095 Moving docker images from centos to rhel base.
  Dockerfile.azure-controllers
  Dockerfile.e2e
  Dockerfile.etcdbackup
  Dockerfile.metricsbridge
  Dockerfile.sync
Labels: approved, lgtm, size/S

#1100 change rg format
  Makefile
Labels: approved, lgtm, size/XS

#1108 release 3.11.51
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1106 update plugin config for v1 release
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1109 move repo
  hack/upgrade-e2e.sh
Labels: approved, lgtm

#1107 remove dev namespace
  Makefile
Labels: approved, lgtm, size/S

#1079 Add AdminUpdating provisioning state
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/api/validate/validators.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/util.go
Labels: approved, lgtm, size/S

#1114 Release v1.1 preparation
  Dockerfile.azure-controllers
  Dockerfile.e2e
  Dockerfile.etcdbackup
  Dockerfile.metricsbridge
  Dockerfile.sync
  Makefile
  hack/upgrade-e2e.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/api/validate/validators.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/clusterstatus.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/rotatesecrets.go
  pkg/fakerp/routes.go
  pkg/fakerp/server.go
  pkg/fakerp/util.go
Labels: approved, lgtm, size/XL

#1119 rollback use of UpdateStatus
  pkg/fakerp/admin_handlers.go
Labels: approved, lgtm, size/XS

#1121 Specifying full path to rhel7.
  Dockerfile.azure-controllers
  Dockerfile.e2e
  Dockerfile.etcdbackup
  Dockerfile.metricsbridge
  Dockerfile.sync
Labels: approved, lgtm, size/S

#1078 DNS refactor in preparation for vanity domains.
  pkg/cluster/healthcheck.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  test/manifests/normal/create.yaml
Labels: approved, lgtm, size/L

#1113 Send audit logs to Geneva
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-config.yaml
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/S

#1105 Allow RP credentials to be used in plugin
  pkg/api/plugin.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/util/azureclient/azureclient.go
Labels: approved, lgtm, size/M

#902 Add aad to openshift group reconciler to azure-controller
  cmd/azure-controllers/azure-controllers.go
  env.example
  hack/aad.sh
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-controller.yaml
  pkg/addons/data/Deployment.apps/openshift-infra/customer-admin-controller.yaml
  pkg/addons/data/Group.user.openshift.io/osa-customer-admins.yaml
  pkg/addons/data/Group.user.openshift.io/osa-customer-readers.yaml
  pkg/addons/data/Secret/openshift-infra/aad-group-sync-config.yaml
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/deepcopy_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/validators.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/util.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
  pkg/controllers/customeradmin/group_reconcile.go
  pkg/controllers/customeradmin/shared.go
  pkg/fakerp/fakerp.go
  test/clients/openshift/login.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/manifests/normal/create.yaml
Labels: approved, lgtm, size/XL

#1082 Delete stray objects in sync pod
  cmd/sync/sync.go
  hack/update-addons/update-addons.go
  pkg/addons/addons.go
  pkg/addons/client.go
  pkg/addons/wants.go
Labels: approved, lgtm, size/L

#1096 Update azure compute api
  pkg/arm/resources.go
  pkg/cluster/hash.go
  pkg/cluster/ready_test.go
  pkg/cluster/scaler/scaler.go
  pkg/cluster/scaler/scaler_test.go
  pkg/cluster/update_master.go
  pkg/cluster/update_master_test.go
  pkg/cluster/update_worker.go
  pkg/cluster/update_worker_test.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/compute_addons.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_scaler/scaler.go
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, size/M

#1128 rename variable and add some documentation
  pkg/cluster/update_master.go
  pkg/cluster/updateblob/types.go
Labels: approved, lgtm, size/XS

#1140 remove tcp reset
  pkg/arm/resources.go
Labels: approved, lgtm, size/XS

#1030 Logging & Metrics dimensions
  cmd/metricsbridge/metricsbridge.go
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/config/derive.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/L

#1135 remove context keys that are no longer used
  pkg/api/plugin.go
  pkg/fakerp/config.go
  pkg/util/azureclient/azureclient.go
Labels: approved, lgtm, size/S

#1131 remove out-of-date configurable, causes an error in the logs
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#1143 re-enable the admin console healthcheck
  pkg/cluster/healthcheck.go
Labels: approved, lgtm, size/XS

#1138 Add geneva actions interface
  pkg/api/plugin.go
Labels: approved, lgtm, size/XS

#1142 Force azure image builds onto latest rhel7 image.
  Dockerfile.azure-controllers
  Dockerfile.e2e
  Dockerfile.etcdbackup
  Dockerfile.metricsbridge
  Dockerfile.sync
Labels: approved, lgtm, size/S

#1132 Revert config as file (cluster config back to a blob)
  README.md
  cmd/sync/sync.go
  hack/config.sh
  hack/scp.sh
  hack/ssh.sh
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/resources.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/types.go
  pkg/config/derive.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, size/L

#1136 Metrics for the dashboards.
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, size/M

#1092 Deep e2e test integration
  pkg/fakerp/shared/shared.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/scaleupdown.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
  test/e2e/standard/testapps.go
Labels: approved, lgtm, size/XXL

#1134 remove etcd probe and add tcp session config
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/cluster/kubeclient/types.go
  pkg/cluster/types.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/M

#1147 Relieve pressure on mdsd
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/config/derive.go
Labels: approved, lgtm, size/M

#1149 fix incorrect version for azure controllers in template
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/XS

#1148 update base to 3.11.69
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1155 OSA release v2.0 upgrade
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1165 add fix for dns race condition
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
Labels: approved, lgtm, size/XS

#1170 Add ILB and ELB tests
  pkg/util/ready/ready.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, size/M

#1171 update test doc
  docs/testing.md
Labels: approved, lgtm, size/S

#1168 Move writeHelpers to config generator
  pkg/fakerp/admin_handlers.go
Labels: approved, lgtm, size/XS

#1169 Release v2.1 dns fix
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1179 bump ose-cluster-monitoring-operator to v3.11.82
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/XS

#1183 Delete _data dir from make delete
  Makefile
Labels: approved, lgtm, size/XS

#1184 Fix e2e test error messages
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, size/S

#1166 sdn update policy change
  pkg/addons/bindata.go
  pkg/addons/data/DaemonSet.apps/openshift-sdn/ovs.yaml
  pkg/addons/data/DaemonSet.apps/openshift-sdn/sdn.yaml
Labels: approved, lgtm, size/XS

#1126 Security options for ssh access in NSG.
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/arm/resources.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/M

#1133 Geneva action force-rotate cluster
  Makefile
  pkg/api/plugin.go
  pkg/cluster/initialize.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_cluster/types.go
  test/e2e/specs/fakerp/forceupdate.go
Labels: approved, lgtm, size/L

#1186 bump to 3.11.82
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/S

#1189 remove stray references to v3.11 tags
  env.example
Labels: approved, lgtm, size/XS

#1190 Release v2.2
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/M

#1191 Release fixes
  Makefile
Labels: approved, lgtm, size/S

#1193 Fix 'all-image' Makefile target: metricsbridge-image.
  Makefile
Labels: approved, lgtm, size/XS

#1199 update embedded clientID to new account, will fix this properly as a …
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#1198 minor fix to env.example
  env.example
Labels: approved, lgtm, size/XS

#1200 Remove hard coded AAD application ID
  README.md
  cmd/createorupdate/createorupdate.go
  cmd/sync/sync.go
  env.example
  hack/aad.sh
  pkg/controllers/customeradmin/group_mapping.go
  pkg/fakerp/client/aad.go
  pkg/fakerp/client/config.go
  pkg/fakerp/client/groups.go
  pkg/util/azureclient/azureclient.go
  pkg/util/configblob/container.go
Labels: approved, lgtm, size/L

#1202 Even fewer metrics
  cmd/metricsbridge/example-config.yaml
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, size/L

#1203 adding startup related targets to .PHONY
  Makefile
Labels: approved, lgtm, size/XS

#1204 Specify prow variables to codecov scripts
  hack/codecov-report.sh
Labels: approved, lgtm, size/XS

#1206 Fewer metrics: backport to v2 and tag v2.4
  cmd/metricsbridge/example-config.yaml
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/L

#1091 Geneva action reimage vm
  Makefile
  pkg/api/plugin.go
  pkg/api/validate/validate_test.go
  pkg/api/validate/validators.go
  pkg/cluster/admin_actions.go
  pkg/cluster/types.go
  pkg/config/names.go
  pkg/config/names_test.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/activitylog.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_cluster/types.go
  test/clients/azure/client.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/reimagevm.go
Labels: approved, lgtm, size/XL
