Repository openshift/openshift-azure, pull requests merged in 2019-12, with the labels that each got.

#2112 don't allow upper-case domain names
  pkg/api/validate/types.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note, size/S

#2122 Move Log Analytics cluster agent to compute node
  pkg/sync/v14/bindata.go
  pkg/sync/v14/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
Labels: approved, lgtm, release-note, size/XS

#2121 Update VM image version
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/XS

#2127 Fix customer-admin-cluster role
  pkg/sync/v14/bindata.go
  pkg/sync/v14/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-cluster.yaml
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note, size/S

#2124 Fix guest user syncing with prefix and no Mail
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note, size/M

#2134 Allowing annotation openshift.io/reconcile-protect=true instead of a label
  pkg/entrypoint/admissioncontroller/scc.go
  pkg/entrypoint/admissioncontroller/scc_test.go
Labels: approved, lgtm, release-note, size/S

#2131 Update to new patched VM image
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/XS

#2128 Fix group sync for UserPrincipalName match
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note, size/L

#2139 [release-v13] Prep for release 13.1
  CHANGELOG.md
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2140 [release-v13] Update release images to 13.1
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2148 Add test for AAD group sync case 4 for non-guests
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note-none, size/M

#2141 Backport v13.1 changes to master
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2154 Update VM image and containers to OpenShift 3.11.157
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2159 sync pod: check the ClusterRoleBinding.authorization.openshift.io for…
  pkg/sync/v14/client.go
  pkg/sync/v14/sync.go
Labels: approved, lgtm, release-note-none, size/M

#2156 Adding imagestream access to customer admin project
  pkg/sync/v14/bindata.go
  pkg/sync/v14/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-project.yaml
Labels: approved, lgtm, release-note, size/S

#2155 Fix RefreshCluster validation for non-admin and fix openshift resolv.conf
  pkg/fakerp/customer_handlers.go
  pkg/plugin/integration_test.go
  pkg/plugin/plugin.go
  pkg/startup/v14/bindata.go
  pkg/startup/v14/data/master/etc/origin/node/resolv.conf
  pkg/startup/v14/data/worker/etc/origin/node/resolv.conf
  pkg/util/azureclient/fake/cloud.go
  pkg/util/azureclient/fake/network/virtualnetworks.go
Labels: approved, lgtm, release-note, size/M

#2160 add nilsanderselde to OWNERS
  OWNERS
Labels: approved, lgtm, release-note, size/XS
