Repository openshift/openshift-azure, pull requests merged in 2019-03, with the labels that each got.

#1215 standardise storage api version used
  pkg/arm/resources.go
Labels: approved, lgtm, size/XS

#1188 Cut down the valid VM types
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/api/validate/types.go
  pkg/api/validate/validate_test.go
  pkg/config/derive.go
Labels: approved, lgtm, size/L

#1214 Send codecov report based on prow job type
  hack/codecov-report.sh
Labels: approved, lgtm, size/S

#1139 Geneva action etcd backup
  docs/e2e/requirements.md
  hack/etcdbackup.sh
  pkg/addons/bindata.go
  pkg/addons/data/CronJob.batch/openshift-etcd/etcd-backup.yaml
  pkg/addons/translate.go
  pkg/api/plugin.go
  pkg/api/validate/types.go
  pkg/api/validate/validate_test.go
  pkg/api/validate/validators.go
  pkg/cluster/kubeclient/backup.go
  pkg/cluster/kubeclient/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_kubeclient/types.go
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, lgtm, size/XL

#1218 stop using td-agent:latest
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/XS

#1220 move Dockerfiles to suit ART standards
  Makefile
  images/azure-controllers/Dockerfile
  images/e2e/Dockerfile
  images/etcdbackup/Dockerfile
  images/metricsbridge/Dockerfile
  images/startup/Dockerfile
  images/sync/Dockerfile
Labels: approved, lgtm, size/S

#1210 Ignore certain files from codecov analysis
  .codecov.yml
Labels: approved, size/XS

#1223 fix group-sync
  hack/aad.sh
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_reconcile.go
Labels: approved, lgtm, size/S

#1192 Use a vault to store public certs
  cmd/createorupdate/createorupdate.go
  cmd/startup/startup.go
  cmd/sync/sync.go
  pkg/addons/bindata.go
  pkg/addons/data/Secret/default/etc-origin-cloudprovider.yaml
  pkg/addons/translate.go
  pkg/api/config.go
  pkg/api/deepcopy.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/master/named/console.crt
  pkg/arm/data/etc/origin/master/named/console.key
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/cluster/hash.go
  pkg/cluster/types.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/client/aad.go
  pkg/fakerp/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/vault.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/tls/marshal.go
  pkg/util/aadapp/aadapp.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/azureclient/keyvault.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_cluster/types.go
  pkg/util/vault/vault.go
  pkg/util/vault/vault_test.go
  test/clients/azure/client.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, release-note, size/XXL

#1231 Add labels to sync pod
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/node/pods/sync.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1229 Check for etcd backup blob in the plugin, not the fakerp
  pkg/api/plugin.go
  pkg/cluster/etcdrestore.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, release-note-none, size/M

#1230 Move client creates into one place for the delete
  pkg/fakerp/customer_handlers.go
Labels: approved, lgtm, release-note-none, size/XS

#1232 Revert "Add labels to sync pod"
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/node/pods/sync.yaml
Labels: approved, release-note-none, size/XS

#1234 rename PluginStepBlobDoesNotExist->PluginStepBlobEtcdBlobExists
  pkg/api/plugin.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1235 metricsbridge - adding an option to calculate rate of a metric
  cmd/metricsbridge/metricsbridge.go
Labels: approved, lgtm, release-note, size/S

#1240 Revert "metricsbridge - adding an option to calculate rate of a metric"
  cmd/metricsbridge/metricsbridge.go
Labels: approved, lgtm, release-note-none, size/S

#1242 remove customer-reader capability, will pursue alternative arrangement post-GA
  env.example
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/validators.go
  pkg/config/derive_test.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_reconcile.go
  pkg/controllers/customeradmin/shared.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/manifests/normal/create.yaml
Labels: approved, lgtm, release-note, size/L

#1221 Adding egress ability for customer admin. labeling default namespace with default.
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-project.yaml
  pkg/addons/data/Namespace/default.yaml
  test/clients/openshift/client.go
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note, size/L

#1244 Release v2.5
  env.example
  hack/aad.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/validators.go
  pkg/config/derive_test.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_reconcile.go
  pkg/controllers/customeradmin/shared.go
  pluginconfig/pluginconfig-311.yaml
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/customer_reader.go
  test/manifests/normal/create.yaml
Labels: approved, lgtm, release-note, size/L

#1245 remove TCP Reset
  pkg/arm/resources.go
Labels: approved, lgtm, release-note-none, size/XS

#1246 increase infra node count 3
  README.md
  pkg/api/validate/validate_test.go
  pkg/api/validate/validators.go
Labels: approved, lgtm, release-note, size/XS

#1178 secrets and x.509 fixes (review carefully)
  Makefile
  cmd/startup/startup.go
  docs/e2e/README.md
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/blackboxmonitor.yaml
  pkg/addons/data/Route.route.openshift.io/default/docker-registry.yaml
  pkg/addons/data/Route.route.openshift.io/default/registry-console.yaml
  pkg/addons/data/Route.route.openshift.io/kube-service-catalog/apiserver.yaml
  pkg/addons/data/Route.route.openshift.io/openshift-ansible-service-broker/asb-1338.yaml
  pkg/addons/data/ServiceAccount/openshift-azure/blackboxmonitor.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/convertertoadmin.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/util/structtags/structtags.go
  test/clients/openshift/client.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/clusterstatus.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/standard/cluster.go
Labels: approved, lgtm, size/L

#1252 fix quota flake due to azure-controller not having created rolebinding yet
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note-none, size/S

#1243 Validate updates
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/api/validate/update_validators.go
  pkg/api/validate/update_validators_test.go
  pkg/api/validate/validators.go
  pkg/config/derive.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/vault.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, release-note, size/XXL

#1251 DNS updates for TLS work
  README.md
  cmd/createorupdate/createorupdate.go
  cmd/sync/sync.go
  env.example
  hack/aad.sh
  pkg/addons/translate.go
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/api/validate/api_test.go
  pkg/api/validate/validators.go
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/master/master-config.yaml
  pkg/cluster/healthcheck.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/generate.go
  pkg/config/util.go
  pkg/fakerp/client/config.go
  pkg/fakerp/client/manifest.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/vault.go
  pkg/util/aadapp/aadapp.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/dns.go
  pkg/util/azureclient/dns_addons.go
  pkg/util/azureclient/keyvault.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/random/random.go
  pkg/util/randomstring/randomstring.go
  pkg/util/vault/vault.go
  pkg/util/vault/vault_test.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
  test/e2e/standard/sanitychecker.go
  test/manifests/fakerp/create.yaml
  test/manifests/normal/create.yaml
  test/manifests/realrp/create.yaml
Labels: approved, lgtm, release-note, size/XXL

#1239 Move pluginConfig to "master" and enable more granular base image versioning
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/config/derive.go
  pkg/config/generate_test.go
  pkg/util/template/template.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1253 create aad apps with different identifier uris, otherwise they clash
  hack/aad.sh
Labels: approved, do-not-merge/release-note-label-needed, size/XS

#1254 switching _total metrics to rate() over the previous 1 minute
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, release-note-none, size/M

#1255 only set customerAdminGroupId field in create manifest when it is actually set
  test/manifests/fakerp/create.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1248 Adding two new dimensions in metrics-bridge: hostname and agentRole
  cmd/metricsbridge/metricsbridge.go
  pkg/config/names.go
  pkg/config/names_test.go
Labels: approved, lgtm, release-note-none, size/M

#1250 Adding customer admin sync test.
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note-none, size/S, ¯\_(ツ)_/¯

#1236 run command geneva action
  pkg/api/plugin.go
  pkg/cluster/admin_actions.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/util/azureclient/compute_addons.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/azureclient/resources.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_cluster/types.go
  test/e2e/specs/fakerp/command.go
Labels: approved, lgtm, release-note, size/L

#1257 Rename ClusterVersion -> PluginVersion, add ClusterVersion
  Makefile
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/plugin/api/config.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/admin_api.go
Labels: approved, lgtm, release-note, size/M

#1259 Simple makefile improvements
  .gitignore
  Makefile
  images/e2e-tests/Dockerfile
Labels: approved, lgtm, release-note, size/M

#1219 Serve Azure Red Hat OpenShift CSS logo.
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-branding/branding.yaml
  pkg/addons/data/ConfigMap/openshift-web-console/webconsole-config.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-branding/branding.yaml
  pkg/addons/data/Namespace/openshift-azure-branding.yaml
  pkg/addons/data/Route.route.openshift.io/openshift-azure-branding/branding.yaml
  pkg/addons/data/Service/openshift-azure-branding/branding.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/cluster/kubeclient/ready.go
  pkg/config/generate_test.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1266 remove go build ./... from all target
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#1267 fixing metric naming mistake
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, release-note, size/XS

#1263 Console fixes after TLS work
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-console/console-config.yaml
  pkg/addons/data/Deployment.apps/default/registry-console.yaml
  pkg/addons/data/Deployment.apps/openshift-console/console.yaml
  pkg/addons/data/Secret/default/registry-console.yaml
  pkg/addons/data/Secret/openshift-console/apiserver-cert.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/convertertoadmin.go
  pkg/api/types_test.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/fakerp/reimagevm.go
  test/e2e/specs/scaleupdown.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/L

#1261 Geneva action get rp plugin versions
  Makefile
  cmd/createorupdate/createorupdate.go
  pkg/addons/bindata.go
  pkg/addons/data/DaemonSet.apps/default/docker-registry.yaml
  pkg/addons/data/DaemonSet.apps/default/router.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/addons/data/DaemonSet.apps/openshift-sdn/ovs.yaml
  pkg/addons/data/DaemonSet.apps/openshift-sdn/sdn.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-branding/branding.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/Deployment.apps/openshift-console/console.yaml
  pkg/addons/data/Deployment.apps/openshift-web-console/webconsole.yaml
  pkg/api/admin/api/types.go
  pkg/api/plugin.go
  pkg/arm/arm.go
  pkg/arm/resources.go
  pkg/arm/resources_test.go
  pkg/cluster/hash.go
  pkg/cluster/kubeclient/roundtrip.go
  pkg/cluster/kubeclient/types.go
  pkg/cluster/types.go
  pkg/cluster/update_worker.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/middleware.go
  pkg/fakerp/middleware_test.go
  pkg/fakerp/routes.go
  pkg/fakerp/server.go
  pkg/fakerp/shared/shared.go
  pkg/fakerp/util.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  test/clients/azure/client.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/clusterstatus.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/reimagevm.go
Labels: approved, lgtm, release-note, size/XXL

#1264 native vm image building!
  .gitignore
  Makefile
  cmd/vmimage/vmimage.go
  docs/vmimage.md
  hack/build-archive.sh
  hack/vmimage-cloudpartner.sh
  hack/vmimage.sh
  pkg/arm/arm.go
  pkg/arm/resources.go
  pkg/arm/resources_test.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/NetworkManager/dispatcher.d/99-origin-dns.sh
  pkg/vmimage/data/etc/dnsmasq.d/origin-dns.conf
  pkg/vmimage/data/etc/docker/certs.d/docker-registry.default.svc-5000/node-client-ca.crt
  pkg/vmimage/data/etc/modules-load.d/glusterfs.conf
  pkg/vmimage/data/etc/multipath.conf
  pkg/vmimage/data/etc/origin/node/bootstrap-node-config.yaml
  pkg/vmimage/data/etc/sysconfig/atomic-openshift-node
  pkg/vmimage/data/etc/sysconfig/iptables
  pkg/vmimage/data/etc/sysctl.d/99-openshift.conf
  pkg/vmimage/data/etc/systemd/journald.conf
  pkg/vmimage/data/etc/systemd/system/atomic-openshift-node.service
  pkg/vmimage/data/etc/systemd/system/basic.target.wants/iptables.service
  pkg/vmimage/data/etc/systemd/system/dnsmasq.service.d/override.conf
  pkg/vmimage/data/etc/systemd/system/docker.service.d/custom.conf
  pkg/vmimage/data/etc/systemd/system/firewalld.service
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/dnsmasq.service
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/docker.service
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/iscsid.service
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/waagent.service
  pkg/vmimage/data/etc/systemd/system/waagent.service.d/custom.conf
  pkg/vmimage/data/etc/tuned/active_profile
  pkg/vmimage/data/etc/tuned/openshift-control-plane/tuned.conf
  pkg/vmimage/data/etc/tuned/openshift-node/tuned.conf
  pkg/vmimage/data/etc/tuned/openshift/tuned.conf
  pkg/vmimage/data/etc/tuned/profile_mode
  pkg/vmimage/data/etc/tuned/recommend.conf
  pkg/vmimage/data/etc/yum.repos.d/kickstart.repo
  pkg/vmimage/data/script.sh
  pkg/vmimage/data/usr/local/bin/get-node-logs
  pkg/vmimage/data/usr/local/bin/master-exec
  pkg/vmimage/data/usr/local/bin/master-logs
  pkg/vmimage/data/usr/local/bin/master-restart
  pkg/vmimage/data/usr/local/bin/openshift-node
  pkg/vmimage/resources.go
  pkg/vmimage/ssh.go
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/XXL

#1269 stop referring to graphrbac client directly in azure-controllers
  cmd/azure-controllers/azure-controllers.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_reconcile.go
  pkg/controllers/customeradmin/shared.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/azureclient/graphrbac_addons.go
  pkg/util/mocks/mock_azureclient/azureclient.go
Labels: approved, lgtm, release-note-none, size/XXL

#1271 Configurable openshift component logging
  Makefile
  cmd/startup/startup.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/plugin/api/config_test.go
  pkg/api/types_test.go
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/update_validators.go
  pkg/api/validate/update_validators_test.go
  pkg/api/validate/validators_test.go
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/node/pods/apiserver.yaml
  pkg/arm/data/etc/origin/node/pods/controllers.yaml
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/config/generate.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/loglevel.go
Labels: approved, lgtm, release-note-none, size/XXL

#1226 use new master and worker service principals
  env.example
  hack/setup-rbac/main.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/vault.go
Labels: approved, lgtm, release-note, size/L

#1277 update to 311.82.20190311
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/XS

#1262 Azure file support
  Makefile
  pkg/addons/addons.go
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/system-controller-persistent-volume-binder.yaml
  pkg/addons/data/StorageClass.storage.k8s.io/azure-disk.yaml
  pkg/addons/data/StorageClass.storage.k8s.io/azure-file.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/arm/arm.go
  pkg/arm/resources.go
  pkg/config/generate.go
  pkg/plugin/plugin.go
  pkg/util/ready/ready.go
  test/e2e/specs/end_user.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note, size/L

#1270 CA Bundle for certs
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/marshal.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/json/marshal.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/etc/origin/master/ca-bundle.crt
  pkg/arm/data/etc/origin/master/master-config.yaml
  pkg/arm/data/etc/origin/master/named/console.crt
  pkg/cluster/hash.go
  pkg/cluster/healthcheck.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/fakerp/vault.go
  pkg/tls/marshal.go
  pkg/util/template/template.go
  pkg/util/vault/vault.go
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note, size/L

#1276 Add podAntiAffinity spec to Branding Deployment.
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/openshift-azure-branding/branding.yaml
Labels: approved, lgtm, release-note-none, size/S

#1283 increase deployment template timeout to 30 minutes, for when eastus is busy
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/XS

#1285 Bubbling up errors properly
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/XS

#1176 etcd metrics shim
  .gitignore
  Makefile
  cmd/tlsproxy/tlsproxy.go
  hack/upgrade-e2e.sh
  images/tlsproxy/Dockerfile
  pkg/addons/addons.go
  pkg/addons/bindata.go
  pkg/addons/client.go
  pkg/addons/data/DaemonSet.apps/openshift-azure-monitoring/etcd-metrics.yaml
  pkg/addons/data/RoleBinding.rbac.authorization.k8s.io/openshift-azure-monitoring/etcd-metrics.yaml
  pkg/addons/data/Secret/openshift-azure-monitoring/etcd-metrics.yaml
  pkg/addons/data/Secret/openshift-monitoring/etcd-metrics.yaml
  pkg/addons/data/SecurityContextConstraints.security.openshift.io/hostmount-anyuid.yaml
  pkg/addons/data/Service/openshift-azure-monitoring/etcd-metrics.yaml
  pkg/addons/data/ServiceAccount/openshift-azure-monitoring/etcd-metrics.yaml
  pkg/addons/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/etcd-metrics.yaml
  pkg/addons/translate.go
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/cluster/kubeclient/ready.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/fakerp/config.go
  pkg/util/ready/ready.go
  pkg/util/structtags/structtags.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/XL

#1287 etcd - move to path for checks
  cmd/tlsproxy/tlsproxy.go
Labels: approved, lgtm, release-note, size/XS

#1286 add a convention for how we name storage accounts
  pkg/config/generate.go
  pkg/fakerp/fakerp.go
  pkg/util/random/random.go
Labels: approved, lgtm, release-note-none, size/S

#1294 logging level validation fix
  pkg/api/validate/plugin.go
Labels: approved, lgtm, release-note, size/XS

#1158 add release docs
  docs/release.md
Labels: approved, lgtm, size/L

#1292 tackle codecov test coverage inflation
  Makefile
  cmd/azure-controllers/codecov_dummy_test.go
  cmd/createorupdate/codecov_dummy_test.go
  cmd/etcdbackup/codecov_dummy_test.go
  cmd/fakerp/codecov_dummy_test.go
  cmd/metricsbridge/codecov_dummy_test.go
  cmd/startup/codecov_dummy_test.go
  cmd/sync/codecov_dummy_test.go
  cmd/tlsproxy/codecov_dummy_test.go
  cmd/vmimage/codecov_dummy_test.go
  hack/lint-addons/codecov_dummy_test.go
  hack/setup-rbac/codecov_dummy_test.go
  hack/update-addons/codecov_dummy_test.go
  hack/validate-codecov.sh
  hack/validate-imports/codecov_dummy_test.go
  pkg/api/json/codecov_dummy_test.go
  pkg/etcdbackup/codecov_dummy_test.go
  pkg/fakerp/client/codecov_dummy_test.go
  pkg/fakerp/codecov_dummy_test.go
  pkg/util/aadapp/codecov_dummy_test.go
  pkg/util/azureclient/codecov_dummy_test.go
  pkg/util/azureclient/openshiftmanagedcluster/2018-09-30-preview/codecov_dummy_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/codecov_dummy_test.go
  pkg/util/azureclient/storage/codecov_dummy_test.go
  pkg/util/configblob/codecov_dummy_test.go
  pkg/util/jsonpath/codecov_dummy_test.go
  pkg/util/log/codecov_dummy_test.go
  pkg/util/managedcluster/codecov_dummy_test.go
  pkg/util/random/codecov_dummy_test.go
  pkg/util/resourceid/codecov_dummy_test.go
  pkg/util/structtags/codecov_dummy_test.go
  pkg/util/template/codecov_dummy_test.go
  pkg/vmimage/codecov_dummy_test.go
Labels: approved, lgtm, release-note-none, size/L

#1296 tlsproxy fix
  pkg/addons/translate.go
Labels: approved, lgtm, release-note, size/XS

#1290 add tree
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note, size/XS

#1301 add missing role, needed for ILBs
  hack/setup-rbac/main.go
Labels: approved, lgtm, release-note, size/XS

#1303 disable docker build strategy
  pkg/addons/bindata.go
  pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/system-build-strategy-docker-binding.yaml
  test/clients/openshift/client.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/M

#1302 write _data/containerservice.yaml after cluster is created so that vnet id is persisted
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/fakerp/shared/codecov_dummy_test.go
  pkg/fakerp/shared/directory.go
  pkg/fakerp/shared/directory_test.go
  pkg/fakerp/shared/shared.go
  pkg/plugin/plugin.go
  pkg/util/managedcluster/managedcluster.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/loglevel.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/fakerp/reimagevm.go
  test/e2e/specs/scaleupdown.go
  test/e2e/standard/sanitychecker.go
  test/sanity/sanity.go
Labels: approved, lgtm, release-note, size/XL

#1274 Improve CI operator integrations
  Makefile
  hack/ci-operator-prepare.sh
  hack/delete.sh
  hack/upgrade-e2e.sh
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/L

#1306 Release v3.0
  RELEASE_NOTES.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1307 check ksm in e2e
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/XS

#1309 move helpers persistence before creation
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/M

#1316 remove deepcopy otherwise sas uri not available when vmss are rotated
  pkg/arm/arm.go
Labels: approved, lgtm, release-note, size/XS

#1319 prevent update from succeeding unless cluster version matches v2.5
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, release-note, size/M

#1320 prevent update from succeeding unless cluster version matches plugin version
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, release-note, size/M

#1321 release v3.1
  RELEASE_NOTES.md
  pkg/arm/arm.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, release-note-none, size/M

#1315 Update release docs to include CHANGELOG.md.
  docs/release.md
Labels: approved, lgtm, release-note-none, size/S

#1324 fix upgrade script ordering and secret name
  hack/upgrade-e2e.sh
Labels: approved, lgtm, release-note-none, size/S

#1327 handle service unavailable condition before pod has even started
  pkg/api/plugin.go
  pkg/cluster/kubeclient/ready.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1323 add runningUnderTest exclusion for upgrades
  pkg/plugin/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1329 make hash invariant of SAS URIs
  Makefile
  cmd/createorupdate/createorupdate.go
  pkg/cluster/hash.go
  pkg/cluster/hash_test.go
  pkg/fakerp/client/manifest.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/admin_api.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, release-note, size/L

#1330 Release v3.2
  Makefile
  RELEASE_NOTES.md
  pkg/cluster/hash.go
  pkg/cluster/hash_test.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, release-note-none, size/L

#1333 add /vmimage to .gitignore
  .gitignore
Labels: do-not-merge/release-note-label-needed

#1328 Blob read unit tests
  pkg/cluster/updateblob/updateblob_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/M

#1335 vmimage: remove .Extras, missed out by previous refactor
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1337 update to 311.88.20190322
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#1344 Ci fixes
  test/e2e/specs/realrp/realrp.go
  test/manifests/realrp/create.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1341 refactor upgrade and create script locations
  Makefile
  cmd/monitoring/monitoring.go
  hack/artifacts.sh
  hack/tests/ci-operator-prepare.sh
  hack/tests/create-e2e.sh
  hack/tests/upgrade-e2e.sh
  hack/upgrade-e2e.sh
  hack/upgrade-local.sh
  hack/verify/validate-code-format.sh
  hack/verify/validate-codecov.sh
  hack/verify/validate-deps.sh
  hack/verify/validate-generated.sh
  hack/verify/validate-util.sh
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/L

#1353 some fixes
  hack/config.sh
  hack/tests/create-e2e.sh
  hack/tests/upgrade-e2e.sh
Labels: approved, do-not-merge/release-note-label-needed, size/S

#1349 Fix vmimage build commits being tagged as dirty in CI
  .gitignore
Labels: approved, lgtm, release-note-none, size/XS

#1355 re-add runningUnderTest to config blob for v3 compatibility
  cmd/monitoring/monitoring.go
  hack/tests/upgrade-e2e.sh
  pkg/api/config.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/types_test.go
  pkg/config/config.go
  pkg/config/v3/generate.go
  pkg/config/v3/generate_test.go
  pkg/config/v3/types.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/structtags/structtags.go
Labels: approved, release-note-none, size/M

#1354 label resource groups more clearly
  hack/tests/create-e2e.sh
  hack/tests/upgrade-e2e.sh
Labels: approved, release-note-none, size/XS

#1361 clean up e2e scripts
  hack/tests/ci-operator-prepare.sh
  hack/tests/create-e2e.sh
  hack/tests/e2e-create.sh
  hack/tests/e2e-upgrade.sh
  hack/tests/upgrade-e2e.sh
Labels: approved, lgtm, release-note-none, size/L

#1368 always call az group delete at end of CI run (extra protection)
  hack/artifacts.sh
  hack/tests/e2e-create.sh
  hack/tests/e2e-upgrade.sh
  hack/vmimage.sh
Labels: approved, release-note-none, size/S

#1359 Warn about bad 'glide' tool.
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#1342 Use secret key refs instead of plain secret values
  pkg/sync/v4/bindata.go
  pkg/sync/v4/data/DaemonSet.apps/default/docker-registry.yaml
  pkg/sync/v4/data/DaemonSet.apps/default/router.yaml
  pkg/sync/v4/data/Secret/default/docker-registry-http.yaml
  pkg/sync/v4/data/Secret/default/router-stats.yaml
  pkg/sync/v4/data/Service/default/router-stats.yaml
  pkg/sync/v4/translate.go
Labels: do-not-merge/hold, release-note-none, size/L

#1369 require https traffic to storage accounts
  hack/tests/e2e-upgrade.sh
  pkg/arm/v4/resources.go
  pkg/cluster/initialize.go
Labels: approved, lgtm, release-note-none, size/S

#1366 scriptfix - provide config file config
  hack/tests/ci-operator-prepare.sh
  hack/tests/e2e-upgrade.sh
Labels: approved, lgtm, release-note-none, size/S

#1372 log operations when deployment fails
  hack/monitoring.sh
  hack/tests/ci-operator-prepare.sh
  hack/tests/e2e-create.sh
  hack/tests/e2e-upgrade.sh
  hack/vmimage.sh
  pkg/cluster/kubeclient/roundtrip.go
  pkg/fakerp/fakerp.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/resources.go
  pkg/util/azureclient/resources_addons.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/vmimage/vmimage.go
Labels: approved, release-note-none, size/L

#1370 Slow the polling of WaitForReadySyncPod to 10 seconds
  pkg/cluster/kubeclient/ready.go
Labels: approved, lgtm, release-note-none, size/XS

#1357 hash stability tests
  cmd/sync/sync.go
  pkg/arm/v3/arm.go
  pkg/cluster/hash.go
  pkg/cluster/hash_test.go
  pkg/startup/v3/startup.go
  pkg/sync/sync.go
  pkg/sync/v3/sync.go
  pkg/sync/v4/sync.go
  test/util/populate/dummycerts.go
Labels: approved, lgtm, release-note-none, size/L

#1360 add code to allow debugging of hash functions
  cmd/startup/startup.go
  pkg/api/plugin.go
  pkg/arm/v3/arm.go
  pkg/arm/v4/arm.go
  pkg/cluster/hash.go
  pkg/fakerp/config.go
  pkg/startup/startup.go
  pkg/startup/v3/startup.go
  pkg/startup/v4/startup.go
Labels: approved, lgtm, release-note-none, size/M

#1385 Fix networking flake caused by exuberant monitoring
  cmd/monitoring/monitoring.go
Labels: approved, release-note-none, size/M

#1382 fetch kubelet goroutines to artifacts
  cmd/monitoring/monitoring.go
  hack/artifacts.sh
  hack/monitoring.sh
  hack/tests/ci-operator-prepare.sh
  hack/tests/e2e-create.sh
  hack/tests/e2e-upgrade.sh
  hack/vmimage.sh
  pkg/cluster/hash_test.go
  pkg/startup/v4/bindata.go
  pkg/startup/v4/data/master/etc/origin/master/admin.crt
  pkg/startup/v4/data/master/etc/origin/master/admin.key
  pkg/util/blackbox/types.go
Labels: approved, lgtm, release-note-none, size/L
