Repository openshift/openshift-azure, pull requests merged in 2019-07, with the labels that each got.

#1755 Azure-controllers metrics
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/metrics.go
  pkg/controllers/customeradmin/namespace_controller.go
  pkg/controllers/customeradmin/rolebinding_controller.go
  pkg/controllers/customeradmin/shared.go
  pkg/entrypoint/azure-controllers/azure-controllers.go
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
Labels: approved, lgtm, release-note-none, size/L

#1679 Add support for etcd ca rotation
  pkg/api/plugin.go
  pkg/cluster/types.go
  pkg/cluster/update_master.go
  pkg/config/config.go
  pkg/config/v4/generate.go
  pkg/config/v5/generate.go
  pkg/config/v6/generate.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_cluster/types.go
  pkg/util/mocks/mock_config/config.go
  test/e2e/specs/fakerp/carotation.go
Labels: approved, lgtm, release-note, size/L

#1770 Adds m1kola as a reviewer
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1723 Defining sane garbage collection thresholds
  pkg/startup/v6/bindata.go
  pkg/startup/v6/data/master/etc/origin/node/node-config.yaml
  pkg/startup/v6/data/worker/etc/origin/node/node-config.yaml
Labels: approved, lgtm, release-note-none, size/S

#1769 Add some more ca to rotate
  pkg/config/v6/generate.go
  test/e2e/specs/fakerp/carotation.go
Labels: approved, lgtm, release-note-none, size/S

#1773 Removing FIPS
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1760 Metrics-bridge metrics
  pkg/entrypoint/metricsbridge/cmd.go
  pkg/entrypoint/metricsbridge/metricsbridge.go
  pkg/entrypoint/metricsbridge/telemetry.go
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/sync/v6/data/Deployment.apps/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/sync/v6/data/Service/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/sync/v6/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/metrics-bridge.yaml
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, release-note-none, size/L

#1768 group sync fix to include external users
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
  pkg/controllers/customeradmin/group_reconcile.go
Labels: approved, lgtm, release-note, size/M

#1776 adding permissions to the customer-admin-cluster and cusomer-admin-project roles
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-cluster.yaml
  pkg/sync/v6/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-project.yaml
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note, size/L

#1765 adding alert definitions for the sync pod, router and api server
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/PrometheusRule.monitoring.coreos.com/openshift-monitoring/prometheus-k8s-arorules.yaml
  testfile
Labels: approved, lgtm, release-note-none, size/L

#1782 Add a note on GNU utils for macOS
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#1785 disable-legacy-registry for docker daemon
  pkg/arm/v6/bindata.go
  pkg/arm/v6/data/master-startup.sh
  pkg/arm/v6/data/node-startup.sh
Labels: approved, lgtm, release-note-none, size/S

#1788 Disable debug mode in conformance test script
  hack/tests/origin-conformance.sh
Labels: approved, lgtm, release-note, size/XS

#1790 Avoid accidentally exposing secrets
  hack/tests/ci-prepare.sh
Labels: approved, lgtm, release-note-none, size/S

#1791 Pin master configs to local api-servers
  pkg/arm/v6/bindata.go
  pkg/arm/v6/data/master-startup.sh
Labels: approved, lgtm, release-note-none, size/S

#1793 Remove the last of the v3 code paths
  pkg/api/admin/types_test.go
  pkg/api/config.go
  pkg/api/types_test.go
  pkg/cluster/hash.go
  pkg/fakerp/util.go
  pkg/startup/v5/derive.go
  pkg/startup/v6/derive.go
  pkg/util/derived/derived.go
  pkg/util/derived/derived_test.go
Labels: approved, lgtm, release-note-none, size/M

#1750 Adding vm image validate shell.
  Makefile
  cmd/vmimage/vmimage.go
  hack/vmimage-validate.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/audit/rules.d/scap.rules
  pkg/vmimage/data/etc/modprobe.d/no-usb-storage.conf
  pkg/vmimage/data/etc/pam.d/password-auth
  pkg/vmimage/data/etc/pam.d/system-auth
  pkg/vmimage/data/etc/rc.d/rc.local
  pkg/vmimage/data/etc/security/pwquality.conf
  pkg/vmimage/data/script.sh
  pkg/vmimage/data/ssg-rhel7-ds-aro.xml
  pkg/vmimage/data/validate.sh
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/XL

#1787 Rapid mitigation of CVEs with local yum updates
  pkg/api/admin/config.go
  pkg/api/admin/converterfrominternal.go
  pkg/api/admin/convertertointernal.go
  pkg/api/admin/types_test.go
  pkg/api/config.go
  pkg/api/plugin/config.go
  pkg/api/plugin/convertertointernal.go
  pkg/api/plugin/convertertointernal_test.go
  pkg/api/types_test.go
  pkg/api/validate/admin.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/arm/v6/bindata.go
  pkg/arm/v6/data/master-startup.sh
  pkg/arm/v6/data/node-startup.sh
  pkg/config/v6/generate.go
  pkg/config/v6/generate_test.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/ssh.go
  pkg/plugin/integration_test.go
  pkg/util/template/template.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/yum.repos.d/kickstart.repo
  pkg/vmimage/data/script.sh
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/securityupdates.go
Labels: approved, lgtm, release-note, size/L

#1783 Add project-request, self-provisioner, managed-resource capabilities
  pkg/startup/v6/bindata.go
  pkg/startup/v6/data/master/etc/origin/master/master-config.yaml
  pkg/sync/v6/bindata.go
  pkg/sync/v6/client.go
  pkg/sync/v6/client_test.go
  pkg/sync/v6/data/Role.rbac.authorization.k8s.io/openshift/shared-resource-editor.yaml
  pkg/sync/v6/data/RoleBinding.rbac.authorization.k8s.io/openshift/shared-resource-editors.yaml
  pkg/sync/v6/data/Template.template.openshift.io/openshift/project-request.yaml
  pkg/sync/v6/sync.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/fakerp/sync.go
Labels: approved, lgtm, release-note, size/L

#1800 Content update fix
  pkg/sync/v6/bindata.go
  pkg/sync/v6/content_test.go
  pkg/sync/v6/data/ImageStream.image.openshift.io/openshift/dotnet-runtime.yaml
  pkg/sync/v6/data/ImageStream.image.openshift.io/openshift/dotnet.yaml
Labels: approved, lgtm, release-note-none, size/M

#1805 Create release v6.0 with pluginconfig and changelog
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1810 remove legacy aad credentials
  hack/tests/ci-prepare.sh
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
Labels: approved, lgtm, release-note-none, size/S

#1799 Lost this directory along the way
  hack/tests/origin-conformance.sh
Labels: approved, lgtm, release-note-none, size/XS

#1802 Remove RealRP tests
  Makefile
  cmd/createorupdate/createorupdate.go
  docs/e2e/README.md
  docs/e2e/requirements.md
  hack/e2e.sh
  hack/tests/ci-prepare.sh
  hack/tests/e2e-prod.sh
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
  test/clients/azure/client.go
  test/clients/azure/osa.go
  test/e2e/e2e_test.go
  test/e2e/specs/beforesuite.go
  test/e2e/specs/customer_admin.go
  test/e2e/specs/end_user.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/carotation.go
  test/e2e/specs/fakerp/clusterstatus.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdbackuprecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/loglevel.go
  test/e2e/specs/fakerp/metricsbridge.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/fakerp/reimagevm.go
  test/e2e/specs/fakerp/securityupdates.go
  test/e2e/specs/fakerp/setcontainerimage.go
  test/e2e/specs/fakerp/sync.go
  test/e2e/specs/osba_app.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
  test/sanity/sanity.go
Labels: approved, lgtm, release-note-none, size/XL

#1781 Normalise vmimage archive
  hack/build-archive.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
Labels: approved, lgtm, release-note-none, size/S

#1801 add \r to content-update script, think it's needed for the release note tooling
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/XS

#1807 Run validate on vmimage build
  hack/vmimage-validate.sh
  hack/vmimage.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/validate.sh
Labels: approved, lgtm, release-note-none, size/S

#1796 ETCD Backup before update
  pkg/api/plugin.go
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/cluster/kubeclient/backup.go
  pkg/entrypoint/etcdbackup/etcdbackup.go
  pkg/plugin/integration_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, lgtm, release-note, size/L

#1819 Moving the vhd-footer and azureblobupload to upstream repo
  cmd/azureblobupload/azureblobupload.go
  cmd/azureblobupload/codecov_dummy_test.go
  cmd/vhdfooter/codecov_dummy_test.go
  cmd/vhdfooter/vhdfooter.go
Labels: approved, lgtm, release-note-none, size/L

#1811 move to use dedicated aad sync application
  hack/tests/ci-prepare.sh
  pkg/fakerp/aad.go
  pkg/fakerp/client/config.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/M

#1825 Update vmimage-validate.sh to use the $IMAGE_RESOURCEGROUP instead of hard coded value
  hack/vmimage-validate.sh
Labels: approved, lgtm, release-note-none, size/S

#1826 Add troy0820 to OWNERS file
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS
