Repository openshift/openshift-azure, pull requests merged in 2019-10, with the labels that each got.

#1980 scale up debug: log the status of the scaleset and the activitylogs
  pkg/cluster/scaler/scaler.go
  pkg/util/azureclient/compute/virtualmachinescalesets.go
  pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
  pkg/util/mocks/mock_azureclient/mock_compute/compute.go
Labels: approved, lgtm, release-note-none, size/M

#1985 fix content script
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/XS

#1988 remove overrride
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/XS

#1981 Refactor fakeRP to support APIVersion
  cmd/createorupdate/createorupdate.go
  hack/create.sh
  pkg/fakerp/client/manifest.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/server.go
  test/manifests/realrp/create.yaml
Labels: approved, lgtm, release-note-none, size/L

#1987 move diagnostics to test/util/diagnostics
  pkg/cluster/scaler/scaler.go
  pkg/cluster/update_worker.go
  pkg/cluster/update_worker_test.go
  pkg/fakerp/fakerp.go
  pkg/util/mocks/mock_scaler/scaler.go
  test/e2e/specs/fakerp/securityupdates.go
  test/util/diagnostics/codecov_dummy_test.go
  test/util/diagnostics/scaleset.go
  test/util/diagnostics/ssh.go
  test/util/log/codecov_dummy_test.go
  test/util/populate/codecov_dummy_test.go
Labels: approved, lgtm, release-note-none, size/L

#1989 Updates imports to use specific versions
  hack/setup-management/main.go
  pkg/util/azureclient/fake/compute/virtualmachinescalesetvms.go
  pkg/util/azureclient/network/privatelink/privateendpoint.go
  pkg/util/azureclient/network/privatelink/privatelinkservice.go
Labels: approved, lgtm, release-note-none, size/S

#1956 CI test driver script for Verification tests
  hack/tests/verification-tests.sh
Labels: approved, lgtm, release-note-none, size/M

#1994 Correct the clusterId for monitoring
  pkg/sync/v10/bindata.go
  pkg/sync/v10/data/DaemonSet.apps/openshift-azure-logging/log-analytics-node-agent.yaml
  pkg/sync/v10/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml
  pkg/sync/v10/translate.go
Labels: approved, lgtm, release-note, size/S

#1949 move ImagePullSecret to ARM
  docs/alias.md
  docs/e2e/requirements.md
  docs/release.md
  pkg/arm/v10/arm_test.go
  pkg/arm/v10/bindata.go
  pkg/arm/v10/data/master-startup.sh
  pkg/arm/v10/data/node-startup.sh
  pkg/arm/v10/derive.go
  pkg/arm/v10/derive_test.go
  pkg/arm/v10/resources.go
  pkg/cluster/initialize.go
  pkg/fakerp/config.go
  pkg/plugin/integration_test.go
  pkg/startup/v10/bindata.go
  pkg/startup/v10/data/master/var/lib/origin/.docker/config.json
  pkg/startup/v10/data/worker/var/lib/origin/.docker/config.json
  test/util/populate/images.go
Labels: approved, lgtm, release-note, size/L

#1997 Release v10 images and changelog
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2000 Updates VM image for v11
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/XS

#2002 Add olga as a reviewer
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#2004 Add PrivateAPIServer to the public API
  env.example
  pkg/api/2019-10-27-preview/converterfrominternal.go
  pkg/api/2019-10-27-preview/convertertointernal.go
  pkg/api/2019-10-27-preview/types.go
  pkg/api/2019-10-27-preview/types_test.go
  pkg/api/mock.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/fakerp/client/config.go
  test/manifests/fakerp/create.yaml
Labels: approved, lgtm, release-note, size/M

#2009 Fixes cluster deletion via cmd/createorupdate/createorupdate.go
  cmd/createorupdate/createorupdate.go
Labels: approved, lgtm, size/XS

#1982 enable RoundTripper for PrivateEndpoint
  cmd/createorupdate/createorupdate.go
  cmd/proxy-infrastructure/codecov_dummy_test.go
  cmd/proxy-infrastructure/proxy-infrastructure.go
  cmd/proxy/codecov_dummy_test.go
  cmd/proxy/main.go
  docs/proxy.md
  docs/vpn.md
  hack/proxy-certs/codecov_dummy_test.go
  hack/proxy-certs/proxy-certs.go
  hack/proxy-infrastructure/bindata.go
  hack/proxy-infrastructure/codecov_dummy_test.go
  hack/proxy-infrastructure/data/start.sh
  hack/proxy-infrastructure/resources.go
  hack/proxy-infrastructure/setup.go
  hack/setup-management/main.go
  pkg/arm/v10/arm.go
  pkg/arm/v11/arm.go
  pkg/cluster/healthcheck.go
  pkg/cluster/kubeclient/roundtrip.go
  pkg/cluster/types.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/proxy.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
  pkg/sync/v10/sync.go
  pkg/sync/v11/sync.go
  pkg/sync/v7/sync.go
  pkg/sync/v71/sync.go
  pkg/sync/v9/sync.go
  pkg/util/roundtrippers/authorizing.go
  pkg/util/roundtrippers/healthcheck.go
  pkg/util/roundtrippers/retrying.go
  test/clients/openshift/client.go
  test/e2e/e2e_test.go
  test/e2e/standard/cluster.go
  testfile
Labels: approved, lgtm, release-note, size/XXL

#2012 Release v10.1
  CHANGELOG.md
  Makefile
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2015 return after deployment errors
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/XS

#2018 fix proxy infra template
  hack/proxy-infrastructure/bindata.go
  hack/proxy-infrastructure/data/start.sh
Labels: approved, release-note-none, size/XS

#2010 Updates vm image for v11
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/XS

#2016 Slight improvement to secret loading
  pkg/fakerp/proxy.go
Labels: approved, lgtm, release-note-none, size/M

#1991 auto-generated docs
  Makefile
  docs/commands.md
  docs/testing.md
  hack/generate-test-commands/codecov_dummy_test.go
  hack/generate-test-commands/commands.md
  hack/generate-test-commands/generate-test-commands.go
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/L

#2019 Update container images for v10.1
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2014 Fix the latest dev-version for minor releases that don't have a direcory
  hack/dev-version/dev-version.go
  hack/dev-version/dev-version_test.go
Labels: approved, lgtm, release-note-none, size/M

#2017 Make sure both managementSubnetCIDR and PrivateAPIServer are provided together
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/S

#2022 Update to OpenShift 3.11.153
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2036 fix master-e2e-create-20190430
  cmd/createorupdate/createorupdate.go
Labels: approved, release-note-none, size/XS

#2037 don't set PrivateAPIServer on in v10 fakerp
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/XS

#2038 Support upgrading from v10.1
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2026 Change the API for Private Cluster as per new agreed model
  pkg/api/2019-10-27-preview/converterfrominternal.go
  pkg/api/2019-10-27-preview/convertertointernal.go
  pkg/api/2019-10-27-preview/types.go
  pkg/api/2019-10-27-preview/types_test.go
  test/manifests/fakerp/create.yaml
Labels: approved, lgtm, release-note, size/M

#2021 Allow validation of an existing built image
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/XS

#2049 fix typo
  pkg/fakerp/config.go
Labels: approved, lgtm, release-note-none, size/XS

#2048 use latest azure image from ci-azure:latest in pluginconfig
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2042 Pin image location in vmimage test
  hack/vmimage-validate.sh
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/XS

#2047 condense OPENSHIFT_AZURE_ROBOT_TOKEN and GITHUB_TOKEN
  hack/ci-notify/main.go
Labels: approved, lgtm, release-note-none, size/XS, ¯\_(ツ)_/¯

#2044 Remove PeerVnetID from 2019-10-27-preview API
  pkg/api/2019-10-27-preview/converterfrominternal.go
  pkg/api/2019-10-27-preview/convertertointernal.go
  pkg/api/2019-10-27-preview/types.go
  pkg/api/2019-10-27-preview/types_test.go
Labels: approved, lgtm, release-note, size/S
