Repository openshift/openshift-azure, pull requests merged in 2019-01, with the labels that each got.

#964 typo Openshift -> OpenShift
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromadmin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/generate.go
  pkg/config/generate_test.go
Labels: approved, lgtm, size/M

#965 add make delete create
  Makefile
Labels: approved, lgtm, size/XS

#970 reimplement worker update to use a new scaleset and migrate VMs to it
  hack/validate-generated.sh
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/converterfromadmin_test.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate_test.go
  pkg/arm/arm.go
  pkg/arm/arm_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/resources.go
  pkg/cluster/deploy.go
  pkg/cluster/deploy_test.go
  pkg/cluster/hash.go
  pkg/cluster/hash_test.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/kubeclient/ready.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_master.go
  pkg/cluster/update_master_test.go
  pkg/cluster/update_test.go
  pkg/cluster/update_worker.go
  pkg/cluster/update_worker_scaler.go
  pkg/cluster/updateblob.go
  pkg/cluster/updateblob/blobservice.go
  pkg/cluster/updateblob/marshal.go
  pkg/cluster/updateblob/types.go
  pkg/cluster/updateblob/updateblob_test.go
  pkg/config/derive.go
  pkg/config/derive_test.go
  pkg/config/names.go
  pkg/config/names_test.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/compute_addons.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/cloudprovider/cloudprovider_test.go
  pkg/util/mocks/mock_arm/arm.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  pkg/util/mocks/mock_cluster/hash.go
  pkg/util/mocks/mock_cluster/types.go
  pkg/util/mocks/mock_updateblob/blobservice.go
  test/clients/azure/compute.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, size/XXL

#882 Add documentation on e2e inputs and running with container image
  .gitignore
  docs/e2e/README.md
  docs/e2e/requirements.md
  docs/testing.md
  hack/e2e.sh
Labels: approved, kind/documentation, lgtm, size/L

#951 add console and node-exporter checks
  pkg/cluster/healthcheck.go
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/S

#976 Fixes to etcd restore
  cmd/etcdbackup/etcdbackup.go
  cmd/recoveretcdcluster/recoveretcdcluster.go
  hack/etcdrecovery.sh
  pkg/addons/bindata.go
  pkg/addons/data/DaemonSet.apps/kube-service-catalog/apiserver.yaml
  pkg/arm/arm.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/resources.go
  pkg/cluster/deploy.go
  pkg/cluster/etcdrestore.go
  pkg/cluster/etcdrestore_test.go
  pkg/cluster/hash_test.go
  pkg/cluster/healthcheck.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready.go
  pkg/cluster/types.go
  pkg/etcdbackup/etcdbackup.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/storage/storage.go
  pkg/util/managedcluster/managedcluster.go
  pkg/util/mocks/mock_azureclient/mock_storage/storage.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/XL

#979 add lint-addons.go, this broadly checks that pkg/addons/data files are in a canonical format (2)
  Makefile
  hack/lint-addons/lint-addons.go
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/addons/bindata.go
  pkg/addons/clean.go
  pkg/addons/clean_test.go
  pkg/addons/client.go
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-controller.yaml
  pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/customer-admin-project.yaml
  pkg/addons/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-customerdata-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/CronJob.batch/openshift-etcd/etcd-backup-hourly.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/td-agent.yaml
  pkg/addons/data/DaemonSet.apps/openshift-node/sync.yaml
  pkg/addons/data/Deployment.apps/default/docker-registry.yaml
  pkg/addons/data/Deployment.apps/default/registry-console.yaml
  pkg/addons/data/Deployment.apps/default/router.yaml
  pkg/addons/data/Deployment.apps/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/data/Deployment.apps/openshift-console/console.yaml
  pkg/addons/data/Deployment.apps/openshift-infra/customer-admin-controller.yaml
  pkg/addons/data/Deployment.apps/openshift-monitoring/cluster-monitoring-operator.yaml
  pkg/addons/data/Deployment.apps/openshift-web-console/webconsole.yaml
  pkg/addons/data/Group.user.openshift.io/osa-customer-admins.yaml
  pkg/addons/data/Group.user.openshift.io/osa-customer-readers.yaml
  pkg/addons/data/Secret/openshift-azure-logging/azure-registry.yaml
  pkg/addons/data/Secret/openshift-azure-monitoring/azure-registry.yaml
  pkg/addons/data/Secret/openshift-azure-monitoring/mdm-cert.yaml
  pkg/addons/data/Service/default/router-stats.yaml
  pkg/addons/default.go
  pkg/addons/translate.go
  pkg/jsonpath/jsonpath.go
Labels: approved, lgtm, size/XL

#936 replacing strings in internal representation ResourcePurchasePlan with pointers
  pkg/api/converterfromadmin.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
Labels: approved, lgtm, size/L

#932 adding VnetID field to APIs and code to populate it after deploy
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/2018-09-30-preview/api/types_test.go
  pkg/api/admin/api/types.go
  pkg/api/admin/api/types_test.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/arm/resources.go
  pkg/plugin/plugin.go
  pkg/util/resourceid/resourceid.go
Labels: approved, lgtm, size/L

#983 clean up TestUpdateMasterAgentPool, hopefully it can be used as a mod…
  pkg/cluster/update_master.go
  pkg/cluster/update_master_test.go
Labels: approved, lgtm, size/L

#984 Add y-cote to reviewers list.
  OWNERS
Labels: approved, lgtm, size/XS

#981 Fix key rotation test
  cmd/createorupdate/createorupdate.go
  hack/ssh.sh
  pkg/fakerp/fakerp.go
  pkg/fakerp/shared/shared.go
  test/clients/azure/client.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, size/M

#985 Enable fake RP GETs to work ootb
  pkg/fakerp/server.go
Labels: approved, lgtm, size/S

#989 Set node selector in customer admin controller
  pkg/addons/bindata.go
  pkg/addons/data/Deployment.apps/openshift-infra/customer-admin-controller.yaml
Labels: approved, lgtm, size/XS

#992 Use the RP instead of local file to get cluster state
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/S

#1002 Fixes to metrics
  cmd/metricsbridge/example-config.yaml
  cmd/metricsbridge/metricsbridge.go
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pkg/addons/translate.go
  pkg/config/derive.go
  pkg/util/statsd/statsd.go
Labels: approved, lgtm, size/L

#987 Return no content response on no content
  cmd/createorupdate/createorupdate.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/M

#922 pluginConfigAPI refactor
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/plugin.go
  pkg/api/plugin/api/config.go
  pkg/api/plugin/api/marshal.go
  pkg/api/types_test.go
  pkg/api/validate_plugin.go
  pkg/api/validate_plugin_test.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/config/types.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/validate.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, size/XXL

#955 make logging pods guaranteed
  pkg/addons/bindata.go
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
Labels: approved, lgtm, size/S

#995 Update scale test to be self-contained
  docs/e2e/requirements.md
  test/e2e/specs/scaleupdown.go
  test/manifests/normal/scaledown.yaml
  test/manifests/normal/scaleup.yaml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#999 Restore endpoint in the fake RP
  Makefile
  cmd/createorupdate/createorupdate.go
  cmd/recoveretcdcluster/recoveretcdcluster.go
  hack/etcdrecovery.sh
  pkg/api/admin/api/client.go
  pkg/fakerp/restore.go
  pkg/fakerp/server.go
  pkg/fakerp/util.go
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, size/XL

#1017 Require RESOURCEGROUP to be set before running reentrancy test
  test/e2e/specs/fakerp/admin.go
Labels: approved, lgtm, size/XS

#1021 make PeerVnetID a pointer in the internal model again
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/converterfromadmin.go
  pkg/api/converterfromv20180930preview.go
  pkg/api/converterfromv20180930preview_test.go
  pkg/api/convertertoadmin.go
  pkg/api/convertertov20180930preview.go
  pkg/api/types.go
  pkg/api/validate.go
  pkg/api/validate_test.go
Labels: approved, lgtm, size/M

#1020 enable r/o cache on etcd disk
  pkg/arm/resources.go
Labels: approved, lgtm, size/XS

#1015 Remove etcd restore e2e test requirement
  docs/e2e/requirements.md
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, lgtm, size/S

#1022 Move router and docker-registry from deployments to daemonsets
  pkg/addons/bindata.go
  pkg/addons/data/DaemonSet.apps/default/docker-registry.yaml
  pkg/addons/data/DaemonSet.apps/default/router.yaml
  pkg/addons/translate.go
  pkg/cluster/kubeclient/ready.go
Labels: approved, lgtm, size/L

#1010 logging consolidation
  docs/logging.md
  pkg/addons/addons.go
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/addons/data/ConfigMap/openshift-azure-logging/mdsd-config.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/mdsd.yaml
  pkg/addons/data/DaemonSet.apps/openshift-azure-logging/td-agent.yaml
  pkg/addons/translate.go
  pkg/cluster/kubeclient/ready.go
Labels: approved, lgtm, size/L

#1019 Move OSA clients out of pkg/api
  cmd/createorupdate/createorupdate.go
  pkg/util/azureclient/openshiftmanagedcluster/2018-09-30-preview/client.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  test/clients/azure/client.go
Labels: approved, lgtm, size/M

#1018 populate cluster id
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, size/XS

#1037 update bindata.go
  pkg/addons/bindata.go
Labels: approved, lgtm, size/XS

#1040 Add unittests for fixupDepends
  pkg/arm/resources_test.go
Labels: approved, lgtm, size/M

#1032 Update location headers set in fakerp delete handler
  pkg/fakerp/server.go
Labels: approved, lgtm, size/XS

#1041 Set the VMSS singlePlacementGroup=false
  pkg/arm/resources.go
Labels: approved, lgtm, size/XS

#990 Setup codecov integration
  Makefile
  README.md
  codecov.yaml
  hack/codecov-report.sh
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#1012 Move deploy and update into the plugin for ease of unittesting
  pkg/cluster/deploy.go
  pkg/cluster/etcdrestore.go
  pkg/cluster/etcdrestore_test.go
  pkg/cluster/healthcheck.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/ready.go
  pkg/cluster/ready_test.go
  pkg/cluster/types.go
  pkg/cluster/update.go
  pkg/cluster/update_master.go
  pkg/cluster/update_master_test.go
  pkg/cluster/update_worker.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_cluster/types.go
Labels: approved, lgtm, size/XL

#1046 enable AttachVolumeLimit=true feature gate
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-node/node-config-compute.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-infra.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-master.yaml
Labels: approved, lgtm, size/S

#1047 Remove reliance on lsof
  hack/create.sh
  hack/delete.sh
  hack/e2e.sh
  hack/etcdrecovery.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/M

#895 Geneva key rotation action
  docs/e2e/requirements.md
  hack/e2e.sh
  pkg/api/plugin.go
  pkg/config/generate.go
  pkg/config/generate_test.go
  pkg/config/types.go
  pkg/fakerp/middleware.go
  pkg/fakerp/restore.go
  pkg/fakerp/rotatesecrets.go
  pkg/fakerp/server.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_config/types.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, size/XL

#1048 add MaxDataDisksPerVM to prevent trying to mount too many disks on a single node
  pkg/addons/bindata.go
  pkg/addons/data/ConfigMap/openshift-node/node-config-compute.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-infra.yaml
  pkg/addons/data/ConfigMap/openshift-node/node-config-master.yaml
  pkg/api/2018-09-30-preview/api/types.go
  pkg/api/admin/api/types.go
  pkg/api/types.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/config/derive.go
Labels: approved, lgtm, size/L

#1043 set hardcoded tuned profile during provisioning
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
Labels: approved, lgtm, size/S

#1033 Add a Root docker config.json
  pkg/api/config.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/data/node-startup.sh
  pkg/fakerp/config.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/end_user.go
Labels: approved, lgtm, size/M

#1052 Updating README
  README.md
Labels: approved, lgtm, size/XS

#1050 update lb rules
  pkg/arm/arm.go
  pkg/arm/resources.go
  pkg/arm/resources_test.go
Labels: approved, lgtm, size/L

#1056 Revert "Remove reliance on lsof"
  hack/create.sh
  hack/delete.sh
  hack/e2e.sh
  hack/etcdrecovery.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/M

#1004 Validators split
  cmd/sync/sync.go
  pkg/api/validate/admin.go
  pkg/api/validate/api.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/api/validate/types.go
  pkg/api/validate/update_validators.go
  pkg/api/validate/validate_test.go
  pkg/api/validate/validators.go
  pkg/plugin/plugin.go
Labels: approved, lgtm, size/XL

#1055 Add link to OSA CI doc
  README.md
Labels: approved, lgtm, size/S

#1008 move AcceptLanguage to context
  cmd/createorupdate/createorupdate.go
  cmd/sync/sync.go
  pkg/api/plugin.go
  pkg/cluster/types.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/server.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/azureclient/managedapplications.go
  pkg/util/azureclient/marketplaceordering.go
  pkg/util/azureclient/network.go
  pkg/util/azureclient/resources.go
  pkg/util/azureclient/storage.go
  pkg/util/configblob/container.go
  test/clients/azure/client.go
Labels: approved, lgtm, size/L

#1060 Refactor fakerp http handlers
  pkg/fakerp/restore.go
  pkg/fakerp/rotatesecrets.go
  pkg/fakerp/server.go
Labels: approved, lgtm, size/M

#1063 Add CI babysitting doc
  docs/ci_babysitting.md
Labels: approved, lgtm, size/M

#1066 Increasing size of etcd disks to 256G
  pkg/arm/resources.go
Labels: approved, lgtm, size/XS

#1070 Avoid setting VMScaleSetVMReimageInput during master VM reimaging
  pkg/cluster/update_master.go
  pkg/cluster/update_master_test.go
Labels: approved, lgtm, size/XS

#1073 remove timeout flag
  hack/etcdrecovery.sh
  hack/upgrade.sh
Labels: approved, lgtm, size/XS

#1072 move codecov.yaml to .codecov.yml
  .codecov.yml
Labels: approved, lgtm, size/XS

#1076 Remove kargakis from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1051 add clusterVersion field to tracking
  pkg/api/admin/api/config.go
  pkg/api/admin/api/types_test.go
  pkg/api/config.go
  pkg/api/converterfromplugin.go
  pkg/api/converterfromplugin_test.go
  pkg/api/convertertoadmin.go
  pkg/api/plugin/api/config.go
  pkg/api/types_test.go
  pkg/api/validate/plugin.go
  pkg/api/validate/plugin_test.go
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/admin_api.go
Labels: approved, lgtm, size/L

#1075 Config blob as file
  README.md
  cmd/sync/sync.go
  hack/config.sh
  hack/scp.sh
  hack/ssh.sh
  pkg/arm/bindata.go
  pkg/arm/data/master-startup.sh
  pkg/arm/resources.go
  pkg/cluster/initialize.go
  pkg/cluster/initialize_test.go
  pkg/cluster/types.go
  pkg/config/derive.go
Labels: approved, lgtm, size/L
