Repository openshift/openshift-azure, pull requests merged in 2019-05, with the labels that each got.

#1588 Add some default settings for AgentPoolProfiles
  pkg/api/2018-09-30-preview/default.go
  pkg/api/2018-09-30-preview/default_test.go
  pkg/api/2019-04-30/default.go
  pkg/api/2019-04-30/default_test.go
Labels: approved, lgtm, release-note, size/L

#1601 add generate to content update script
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/XS

#1604 prevent "Job for docker.service canceled" error on startup
  pkg/arm/arm.go
  pkg/arm/v4/bindata.go
  pkg/arm/v4/data/master-startup.sh
  pkg/arm/v4/data/node-startup.sh
  pkg/arm/v5/bindata.go
  pkg/arm/v5/data/master-startup.sh
  pkg/arm/v5/data/node-startup.sh
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1593 Retry Azure "GET" requests on connection reset by peer
  pkg/util/azureclient/retry.go
  pkg/util/errors/errors.go
  pkg/util/errors/errors_test.go
Labels: release-note-none, size/M

#1605 prevent "Job for docker.service canceled" error on startup - v4.3
  CHANGELOG.md
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
  pkg/arm/arm.go
  pkg/arm/v4/bindata.go
  pkg/arm/v4/data/master-startup.sh
  pkg/arm/v4/data/node-startup.sh
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1610 v5.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, release-note-none, size/L

#1615 remove scale logging
  pkg/cluster/scaler/scaler.go
Labels: release-note-none, size/S

#1602 Simplify create config by removing default values
  test/manifests/fakerp/create.yaml
Labels: lgtm, release-note-none, size/XS

#1613 Unwrap "net/http: HTTP/1.x transport connection broken" error
  pkg/util/errors/errors.go
  pkg/util/errors/errors_test.go
Labels: approved, lgtm, release-note-none, size/M

#1623 Add default router profile to real rp sample manifest
  test/manifests/realrp/create.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1589 Add more integration tests
  pkg/plugin/integration_test.go
  pkg/util/azureclient/fake/cloud.go
  pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
  pkg/util/azureclient/fake/compute/virtualmachinescalesetvms.go
  pkg/util/azureclient/fake/keyvault/keyvault.go
  pkg/util/azureclient/fake/storage/accounts.go
  pkg/util/azureclient/fake/storage/blob.go
Labels: approved, lgtm, release-note-none, size/L

#1627 Limit length of ci-generated resource groups for prod e2e tests
  hack/tests/e2e-prod.sh
Labels: approved, lgtm, release-note-none, size/XS

#1625 Fix the e2e prod script to avoid double creates and fakerp-esque deletes
  hack/tests/e2e-prod.sh
  test/sanity/sanity.go
Labels: approved, lgtm, release-note-none, size/M

#1634 add git status for clarity
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/XS

#1471 moved azure client init to BeforeSuite for reuse.
  test/clients/azure/client.go
  test/e2e/specs/beforesuite.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/clusterstatus.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdbackuprecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/loglevel.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/fakerp/reimagevm.go
  test/e2e/specs/fakerp/setcontainerimage.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, release-note-none, size/L

#1635 Fix realrp test to check for new status code if resource deletes are attempted
  test/e2e/specs/realrp/realrp.go
Labels: approved, lgtm, release-note-none, size/XS

#1636 Fix VirtualNetworkPeeringState check in real rp vnet test
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, release-note-none, size/XS

#1638 Pin go-bindata in validate-generated.sh
  hack/verify/validate-generated.sh
Labels: approved, lgtm, release-note-none, size/XS

#1642 Cleanup imports in metricsbridge e2e test
  test/e2e/specs/fakerp/metricsbridge.go
Labels: approved, lgtm, release-note-none, size/S

#1633 Add ARO documentation and oc download links to console
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ConfigMap/openshift-azure-branding/branding.yaml
  pkg/sync/v6/data/ConfigMap/openshift-web-console/webconsole-config.yaml
  pkg/sync/v6/translate.go
Labels: approved, lgtm, release-note-none, size/M

#1647 release 20190514 Security fix
  CHANGELOG.md
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#1646 release 20190514 Security fix
  CHANGELOG.md
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1645 Release prep (4.4, 5.1)
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/L

#1656 Properly clean up cluster NS records from osadev.cloud dns zone
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/L

#1603 VM image content verify
  cmd/vmimage/vmimage.go
  hack/periodic/vm-content-validate.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/validate.sh
  pkg/vmimage/resources.go
  pkg/vmimage/ssh.go
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/L

#1664 Reject vault names that contain MS reserved words
  pkg/util/random/random.go
Labels: approved, lgtm, release-note-none, size/S

#1669 non-updateable objects are deleted and re-created
  pkg/sync/v6/client.go
Labels: approved, lgtm, release-note-none, size/S

#1629 Make some api properties updatable
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note, size/L

#1673 fixing etcdbackup test
  test/e2e/specs/fakerp/etcdbackuprecovery.go
Labels: approved, lgtm, release-note-none, size/XS

#1676 Add Angus to the approvers list
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1675 fixing issues causing updates on every run of sync pod
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/StatefulSet.apps/openshift-azure-monitoring/canary.yaml
  pkg/sync/v6/default.go
Labels: approved, lgtm, release-note-none, size/XS

#1685 Configurable sync http port and metrics endpoint
  pkg/entrypoint/sync/cmd.go
  pkg/entrypoint/sync/sync.go
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/sync.yaml
Labels: approved, lgtm, release-note-none, size/M

#1686 Embedded http server for azure-controllers
  pkg/entrypoint/azure-controllers/azure-controllers.go
  pkg/entrypoint/azure-controllers/cmd.go
  pkg/sync/v6/bindata.go
  pkg/sync/v6/data/Deployment.apps/openshift-infra/customer-admin-controller.yaml
  pkg/sync/v6/data/Service/openshift-infra/azure-controllers.yaml
  pkg/sync/v6/data/ServiceMonitor.monitoring.coreos.com/openshift-monitoring/azure-controllers.yaml
Labels: approved, lgtm, release-note-none, size/L
