Repository openshift/openshift-azure, pull requests merged in 2019-04, with the labels that each got.

#1374 Scale v3 on v4 plugin test
  hack/tests/ci-operator-prepare.sh
  hack/tests/e2e-scale-on-lower-version.sh
Labels: approved, lgtm, release-note-none, size/M

#1383 restrict #pods/node to 50 for now
  .github/pull_request_template.md
  pkg/cluster/hash_test.go
  pkg/startup/v4/bindata.go
  pkg/startup/v4/data/master/etc/origin/node/node-config.yaml
  pkg/startup/v4/data/worker/etc/origin/node/node-config.yaml
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/origin/node/bootstrap-node-config.yaml
Labels: approved, lgtm, release-note, size/M

#1386 wait for each lb to be ready before creating the next
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note, size/S

#1388 rebase fixes to hack/tests/e2e-scale-on-lower-version.sh and rename
  hack/tests/e2e-scale-previous.sh
Labels: approved, release-note-none, size/S

#1389 rename endpoint again
  hack/tests/e2e-scaleupdown-previous.sh
Labels: release-note-none

#1387 canary app metrics
  cmd/monitoring/monitoring.go
Labels: approved, release-note-none, size/M

#1393 make TestConfig optional in NewPlugin
  pkg/plugin/plugin.go
Labels: approved, release-note, size/XS

#1390 Revert "wait for each lb to be ready before creating the next"
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/S

#1394 make TestConfig optional in NewPlugin
  pkg/plugin/plugin.go
Labels: approved, lgtm, release-note, size/XS

#1401 release v4.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, release-note-none, size/L

#1403 fix makefile tagging
  Makefile
Labels: approved, release-note-none, size/XS

#1404 fix makefile tagging
  Makefile
Labels: approved, release-note-none, size/XS

#1379 Adding template tests
  pkg/startup/startup.go
  pkg/startup/v3/startup.go
  pkg/startup/v4/startup.go
  pkg/vmimage/codecov_dummy_test.go
  pkg/vmimage/vmimage.go
  pkg/vmimage/vmimage_test.go
Labels: approved, lgtm, release-note-none, size/M

#1412 fix flake caused by app crashlooping while database goes away
  test/e2e/standard/testapps.go
Labels: approved, lgtm, release-note-none, size/XS

#1376 ginko custom reporter to azure app insights
  cmd/monitoring/monitoring.go
  docs/e2e/appinsights.md
  pkg/util/blackbox/types.go
  test/e2e/e2e_test.go
  test/reporters/appinsights.go
Labels: approved, lgtm, release-note-none, size/L

#1391 Use ci credentials in ci
  env.example
  hack/tests/ci-operator-prepare.sh
  hack/tests/create-e2e.sh
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
  hack/tests/upgrade-e2e.sh
Labels: approved, lgtm, release-note-none, size/M

#1423 fix minor issue in pluginconfig
  docs/release.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#1407 latch all configurables that come from the plugin config
  pkg/api/plugin/convertertointernal.go
  pkg/api/plugin/convertertointernal_test.go
  pkg/config/config.go
  pkg/config/v3/generate.go
  pkg/config/v3/generate_test.go
  pkg/config/v4/generate.go
  pkg/config/v4/generate_test.go
  pkg/config/v5/generate.go
  pkg/config/v5/generate_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/mocks/mock_config/config.go
  test/e2e/specs/fakerp/keyrotation.go
Labels: approved, lgtm, release-note, size/XL

#1414 increase debugging to understand ongoing storage issue
  pluginconfig/pluginconfig-311.yaml
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/M

#1422 Export 'Log' from the SanityChecker struct.
  test/e2e/standard/sanitychecker.go
  test/e2e/standard/testapps.go
Labels: approved, lgtm, release-note, size/M

#1405 monitoring remove chattiness and race condition waits
  cmd/monitoring/monitoring.go
Labels: approved, lgtm, release-note-none, size/M

#1411 more arm failure logging
  pkg/api/plugin.go
  pkg/cluster/kubeclient/roundtrip.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/config.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/ssh.go
Labels: approved, lgtm, release-note-none, size/L

#1421 Enabling kdump at kernel boot time
  env.example
  hack/vmimage.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/systemd/system/multi-user.target.wants/kdump.service
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#1392 some test reworks with a view to improving testability
  pkg/api/plugin/convertertointernal_test.go
  pkg/arm/v3/arm_test.go
  pkg/arm/v4/arm_test.go
  pkg/arm/v5/arm_test.go
  pkg/cluster/healthcheck.go
  pkg/cluster/types.go
  pkg/config/v3/generate_test.go
  pkg/config/v4/generate_test.go
  pkg/config/v5/generate_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/startup/v3/derive_test.go
  pkg/startup/v4/derive_test.go
  pkg/startup/v5/derive_test.go
  pkg/sync/v3/sync.go
  pkg/sync/v4/sync.go
  pkg/sync/v5/sync.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
  pkg/vmimage/vmimage_test.go
  test/e2e/standard/testapps.go
  test/util/populate/dummycerts.go
  test/util/populate/walk.go
  test/util/tls/tls.go
Labels: approved, lgtm, release-note-none, size/L

#1426 delete geneva-cluster-reader clusterrolebinding
  pkg/cluster/hash_test.go
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ClusterRoleBinding.rbac.authorization.k8s.io/geneva-cluster-reader.yaml
Labels: approved, lgtm, release-note-none, size/M

#1428 Add myself to the OWNERS file
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1431 Update README and env.example
  README.md
  env.example
  pkg/fakerp/fakerp.go
Labels: approved, lgtm, release-note-none, size/L

#1432 add geneva action to list backup blobs
  hack/validate-imports/validate-imports.go
  pkg/api/plugin.go
  pkg/api/types.go
  pkg/cluster/etcdrestore.go
  pkg/cluster/types.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/routes.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
  pkg/util/mocks/mock_cluster/types.go
  test/e2e/specs/fakerp/etcdrecovery.go
Labels: approved, lgtm, release-note, size/L

#1440 re-add nil check which I should not have removed
  cmd/monitoring/monitoring.go
Labels: approved, lgtm, release-note-none, size/XS

#1434 relax the hash test for the version under development otherwise we'll go mad
  pkg/cluster/hash_test.go
Labels: approved, lgtm, release-note-none, size/S

#1437 fixing 2 e2e tests
  test/e2e/specs/fakerp/admin_api.go
  test/e2e/specs/fakerp/clusterstatus.go
Labels: approved, lgtm, release-note-none, size/S

#1451 switch on UseInstanceMetadata
  pkg/fakerp/fakerp.go
  pkg/startup/v3/derive.go
  pkg/startup/v4/derive.go
  pkg/startup/v5/derive.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/cloudprovider/cloudprovider_test.go
  pkg/util/derived/derived.go
  pkg/util/derived/derived_test.go
Labels: approved, release-note-none, size/M

#1397 Prepare for northeurope
  cmd/createorupdate/createorupdate.go
  hack/setup-rbac/main.go
  pkg/fakerp/client/config.go
  pkg/fakerp/client/groups.go
  pkg/fakerp/client/manifest.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/manifests/fakerp/create.yaml
  test/manifests/realrp/create.yaml
Labels: approved, release-note-none, size/L

#1453 use a unique service principal per cluster
  Makefile
  README.md
  env.example
  hack/setup-rbac/main.go
  hack/tests/ci-operator-prepare.sh
  hack/vmimage.sh
  pkg/fakerp/aad.go
  pkg/fakerp/client/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/fakerp.go
  pkg/util/azureclient/authorization.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/mocks/mock_azureclient/azureclient.go
  test/clients/azure/client.go
Labels: approved, lgtm, release-note-none, size/L

#1459 Added grant to owners file
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#1456 allow admin API to change image versions
  hack/tests/e2e-upgrade.sh
  pkg/api/validate/admin.go
Labels: approved, lgtm, release-note, size/S

#1415 new metrics from etcd monitoring tlsproxy
  cmd/metricsbridge/example-config.yaml
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, release-note-none, size/M

#1470 fix upgrade tests
  hack/tests/ci-operator-prepare.sh
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
Labels: approved, lgtm, release-note-none, size/S

#1465 Fix secrets generation command
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#1474 update env.example
  env.example
Labels: release-note-none

#1475 fix tags in Makefile
  Makefile
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/S

#1476 fix tags in Makefile
  Makefile
  hack/vmimage.sh
Labels: release-note-none

#1478 validate canary image empty on v3.2
  CHANGELOG.md
  pkg/api/validate/plugin.go
  pkg/fakerp/server.go
Labels: approved, release-note-none, size/S

#1479 update master for v4.1
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/startup/startup.go
  pkg/startup/v4/derive.go
  pkg/startup/v4/startup.go
  pkg/sync/sync.go
  pkg/sync/v4/bindata.go
  pkg/sync/v4/data/ClusterRoleBinding.rbac.authorization.k8s.io/cluster-monitoring-view.yaml
  pkg/sync/v4/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/sync/v4/data/ConfigMap/openshift-azure-monitoring/metrics-bridge.yaml
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1484 fluentd rollback and cluster upgrade integration fixes - v4
  CHANGELOG.md
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/arm/arm.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/fakerp/fakerp.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pkg/sync/v4/bindata.go
  pkg/sync/v4/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/admin_api.go
  test/manifests/fakerp/admin-update.yaml
Labels: approved, lgtm, release-note-none, size/L

#1483 fluentd rollback and cluster upgrade integration fixes
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/fakerp/client/config.go
  pkg/fakerp/fakerp.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pkg/sync/v4/bindata.go
  pkg/sync/v4/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/fakerp/admin_api.go
  test/manifests/fakerp/admin-update.yaml
Labels: approved, lgtm, release-note, size/L

#1485 Update OWNERS
  OWNERS
Labels: approved, lgtm, release-note, size/XS

#1425 New fake azure client
  pkg/cluster/kubeclient/roundtrip.go
  pkg/cluster/types.go
  pkg/plugin/integration_test.go
  pkg/util/azureclient/fake/accounts.go
  pkg/util/azureclient/fake/cloud.go
  pkg/util/azureclient/fake/codecov_dummy_test.go
  pkg/util/azureclient/fake/compute.go
  pkg/util/azureclient/fake/deployments.go
  pkg/util/azureclient/fake/keyvault.go
  pkg/util/azureclient/fake/storage.go
  pkg/util/wait/wait.go
Labels: approved, lgtm, release-note-none, size/XL

#1488 fix ssh: rejected: administratively prohibited (open failed) error
  pkg/fakerp/fakerp.go
Labels: release-note-none

#1469 convert webconsole image change test to go
  hack/tests/e2e-upgrade.sh
  test/e2e/specs/fakerp/setcontainerimage.go
Labels: approved, lgtm, release-note-none, size/M

#1477 validate canary image empty on v3.2
  pkg/api/validate/plugin.go
  pkg/fakerp/server.go
  pkg/util/ready/ready.go
  test/clients/openshift/template.go
  test/e2e/standard/testapps.go
Labels: approved, lgtm, release-note, size/S

#1487 add note about jq to readme
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#1489 use -w option on iptables to avoid "Another app is currently holding the xtables lock" error
  pkg/arm/v5/bindata.go
  pkg/arm/v5/data/master-startup.sh
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/usr/local/bin/get-node-logs
Labels: approved, lgtm, release-note-none, size/XS

#1455 Logging fixes
  Makefile
  hack/artifacts.sh
  hack/scp.sh
  hack/ssh.sh
  pkg/startup/v5/bindata.go
  pkg/startup/v5/data/master/etc/origin/master/master-config.yaml
  pkg/startup/v5/data/master/etc/origin/node/pods/apiserver.yaml
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/rc.d/rc.local
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/L

#1486 fluentd log split - update with nil check
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ConfigMap/openshift-azure-logging/fluentd-config.yaml
Labels: approved, lgtm, release-note, size/XS

#1375 Provide an E2E test for the OSBA.
  pkg/util/ready/ready.go
  test/clients/openshift/client.go
  test/clients/openshift/login.go
  test/clients/openshift/template.go
  test/e2e/specs/osba_app.go
  test/manifests/osba/osba-os-template.yaml
Labels: approved, lgtm, release-note-none, size/XL

#1495 add missing hyphen
  pkg/fakerp/fakerp.go
Labels: release-note-none

#1493 use mail attribute instead of userPrincipalName to map groups and users
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note-none, size/S

#1502 don't output secret if validation fails
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/S

#1492 Enable cloud API rate limiting for nodes
  pkg/fakerp/fakerp.go
  pkg/startup/v3/derive.go
  pkg/startup/v4/derive.go
  pkg/startup/v5/derive.go
  pkg/util/cloudprovider/cloudprovider.go
  pkg/util/cloudprovider/cloudprovider_test.go
  pkg/util/derived/derived.go
  pkg/util/derived/derived_test.go
Labels: approved, lgtm, release-note, size/L

#1497 Increase how long we wait for the loadbalancer to come up to 10s
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/XS

#1496 bump v5 to 3.11.98
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#1512 Forgot to reflect current config
  pkg/entrypoint/metricsbridge/metrics-bridge-example-config.yaml
Labels: release-note-none, size/M

#1510 added [EveryPR] to Prometheus test, [LongRunning] to admin e2e test
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/prometheus.go
Labels: release-note-none, size/S

#1513 Use shell-agnostic command for checking git tree
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#1514 fix NPE in customeradmin
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_mapping_test.go
Labels: approved, lgtm, release-note-none, size/S

#1519 revert logging validation
  pkg/api/validate/plugin.go
Labels: approved, lgtm, release-note-none, size/XS

#1503 Adding a unit test to check resource's data
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/Role.rbac.authorization.k8s.io/kube-system/system--leader-locking-kube-controller-manager.yaml
  pkg/sync/v5/data/Role.rbac.authorization.k8s.io/kube-system/system--leader-locking-kube-scheduler.yaml
  pkg/sync/v5/data/RoleBinding.rbac.authorization.k8s.io/kube-system/system--leader-locking-kube-controller-manager.yaml
  pkg/sync/v5/data/RoleBinding.rbac.authorization.k8s.io/kube-system/system--leader-locking-kube-scheduler.yaml
  pkg/sync/v5/data/RoleBinding.rbac.authorization.k8s.io/openshift-azure-monitoring/etcd-metrics-viewer.yaml
  pkg/sync/v5/translate_test.go
Labels: lgtm, release-note-none, size/L

#1511 Add disclaimer to README for non aos-azure team members
  README.md
Labels: approved, release-note-none, size/XS

#1509 document around dealing with occuring test flakes.
  docs/ci_babysitting.md
  docs/testing-flakes.md
Labels: approved, lgtm, release-note-none, size/M

#1516 add build logs to e2e DumpInfo
  test/clients/openshift/dumpinfo.go
Labels: lgtm, release-note-none, size/M

#1528 increase maximum nodes to 30
  pkg/api/validate/validators.go
Labels: approved, lgtm, release-note, size/XS

#1527 increase scaleset timeout to 30 minutes
  pkg/fakerp/fakerp.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/resources.go
Labels: approved, lgtm, release-note-none, size/S

#1529 don't return 500s in the fakerp, only 400s - otherwise the client will retry
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/middleware.go
  pkg/fakerp/util.go
Labels: approved, lgtm, release-note-none, size/M

#1520 enable retrying roundtripper in E2E openshift clients
  pkg/cluster/kubeclient/roundtrip.go
  test/clients/openshift/client.go
  test/e2e/standard/cluster.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/L

#1499 Add retry logic to fakerp
  cmd/createorupdate/createorupdate.go
  cmd/monitoring/monitoring.go
  cmd/vmimage/vmimage.go
  hack/setup-rbac/main.go
  pkg/cluster/scaler/scaler.go
  pkg/cluster/types.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/entrypoint/etcdbackup/etcdbackup.go
  pkg/entrypoint/sync/sync.go
  pkg/fakerp/aad.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/dns.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/ssh.go
  pkg/fakerp/vault.go
  pkg/startup/v3/startup.go
  pkg/startup/v4/startup.go
  pkg/startup/v5/startup.go
  pkg/util/azureclient/authorization.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/compute.go
  pkg/util/azureclient/dns.go
  pkg/util/azureclient/graphrbac.go
  pkg/util/azureclient/insights.go
  pkg/util/azureclient/keyvault.go
  pkg/util/azureclient/managedapplications.go
  pkg/util/azureclient/marketplaceordering.go
  pkg/util/azureclient/network.go
  pkg/util/azureclient/resources.go
  pkg/util/azureclient/retry.go
  pkg/util/azureclient/storage.go
  pkg/util/configblob/container.go
  test/clients/azure/client.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/clusterstatus.go
  test/e2e/specs/fakerp/command.go
  test/e2e/specs/fakerp/etcdrecovery.go
  test/e2e/specs/fakerp/forceupdate.go
  test/e2e/specs/fakerp/keyrotation.go
  test/e2e/specs/fakerp/loglevel.go
  test/e2e/specs/fakerp/prometheus.go
  test/e2e/specs/fakerp/reimagevm.go
  test/e2e/specs/fakerp/setcontainerimage.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
  test/e2e/specs/scaleupdown.go
  test/e2e/standard/sanitychecker.go
Labels: approved, lgtm, release-note-none, size/L

#1531 Increase the timeout for the redis redhat.io deployment
  test/e2e/standard/cluster.go
Labels: release-note-none, size/XS

#1500 [wip] test logs into Appinsights
  docs/e2e/appinsights.md
  test/e2e/e2e_test.go
  test/reporters/appinsights.go
  test/reporters/capture.go
Labels: approved, do-not-merge/work-in-progress, release-note-none, size/L

#1525 Add validation for cluster names and locations
  pkg/api/validate/types.go
  pkg/api/validate/types_test.go
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/M

#1536 retry on NoBackingApplicationObject error
  pkg/fakerp/aad.go
Labels: approved, lgtm, release-note-none, size/S

#1537 Check for sync pod readiness correctly
  pkg/cluster/kubeclient/ready.go
  pkg/plugin/integration_test.go
Labels: approved, lgtm, release-note-none, size/M

#1501 fix customeradmin test
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note-none, size/S

#1541 Branding: select 'azure' branding option for cluster console.
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/ConfigMap/openshift-console/console-config.yaml
Labels: lgtm, release-note, size/XS

#1554 add secrets to vmimage
  hack/vmimage.sh
Labels: approved, lgtm, release-note-none, size/XS

#1552 get all controller logs not just the leader
  hack/artifacts.sh
Labels: lgtm, release-note-none, size/XS

#1553 Add DumpInfo to help with Flake debugging.
  test/e2e/specs/osba_app.go
Labels: release-note-none, size/XS

#1556 increase redis deploy timeout to 20 minutes
  test/e2e/standard/cluster.go
Labels: release-note-none

#1551 fix image building rbac error
  hack/setup-rbac/main.go
  hack/vmimage.sh
  pkg/fakerp/aad.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/fakerp.go
Labels: approved, release-note-none, size/M

#1538 removing ansible repo
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/etc/yum.repos.d/kickstart.repo
Labels: approved, do-not-merge/hold, lgtm, release-note-none, size/S

#1559 Adding kube-controllers to e2e fakerp prometheus
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, release-note-none, size/S

#1557 wait for SCC annotation at project creation to avoid "no providers available to validate pod request" flake
  test/clients/openshift/project.go
Labels: approved, lgtm, release-note-none, size/S

#1562 removed [EveryPR] from Prometheus test, fixed admin.go test
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/fakerp/prometheus.go
Labels: approved, lgtm, release-note-none, size/XS

#1567 queries and links
  docs/e2e/appinsights.md
Labels: approved, lgtm, release-note-none, size/S

#1572 changing default e2e timeout to 60m
  hack/e2e.sh
Labels: approved, lgtm, release-note-none, size/XS

#1560 Adding geneva command to restart docker and tests
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  test/e2e/specs/fakerp/command.go
Labels: approved, lgtm, release-note, size/S

#1573 Set Makefile SHELL to bash
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#1548 Add default values to external APIs
  pkg/api/2018-09-30-preview/convertertointernal.go
  pkg/api/2018-09-30-preview/default.go
  pkg/api/2018-09-30-preview/default_test.go
  pkg/api/2019-04-30/convertertointernal.go
  pkg/api/2019-04-30/default.go
  pkg/api/2019-04-30/default_test.go
  pkg/fakerp/fakerp.go
Labels: release-note, size/L

#1576 adding EndUser and ScaleUpDown to EveryPR
  test/e2e/specs/customer_admin.go
  test/e2e/specs/end_user.go
  test/e2e/specs/osba_app.go
  test/e2e/specs/scaleupdown.go
Labels: lgtm, release-note-none, size/XS

#1558 Adding session affinity to router service loadbalancer.
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/Service/default/router.yaml
Labels: approved, lgtm, release-note, size/XS

#1585 work around broken v3.2 build
  hack/tests/e2e-scaleupdown-previous.sh
  hack/tests/e2e-upgrade.sh
Labels: approved, lgtm, release-note-none, size/XS

#1579 Default MasterProfilePool count to 3
  pkg/api/2018-09-30-preview/default.go
  pkg/api/2018-09-30-preview/default_test.go
  pkg/api/2019-04-30/default.go
  pkg/api/2019-04-30/default_test.go
Labels: release-note, size/L

#1580 check for role equality in admin update validation
  pkg/api/validate/admin.go
Labels: approved, lgtm, release-note, size/XS

#1530 retry when we get network errors
  cmd/createorupdate/createorupdate.go
  pkg/cluster/initialize.go
  pkg/cluster/kubeclient/ready.go
  pkg/util/azureclient/storage/storage.go
  pkg/util/configblob/container.go
  pkg/util/errors/errors.go
  pkg/util/errors/errors_test.go
  pkg/util/wait/wait.go
Labels: approved, lgtm, release-note-none, size/L

#1574 Fix the call to etcdbackup
  pkg/arm/v5/bindata.go
  pkg/arm/v5/data/master-startup.sh
  pkg/cluster/kubeclient/backup.go
  pkg/entrypoint/azure-controllers/azure-controllers.go
  pkg/entrypoint/azure-controllers/cmd.go
  pkg/entrypoint/canary/canary.go
  pkg/entrypoint/canary/cmd.go
  pkg/entrypoint/etcdbackup/cmd.go
  pkg/entrypoint/etcdbackup/etcdbackup.go
  pkg/entrypoint/metricsbridge/cmd.go
  pkg/entrypoint/metricsbridge/metricsbridge.go
  pkg/entrypoint/startup/cmd.go
  pkg/entrypoint/startup/startup.go
  pkg/entrypoint/sync/cmd.go
  pkg/entrypoint/sync/sync.go
  pkg/entrypoint/tlsproxy/cmd.go
  pkg/entrypoint/tlsproxy/tlsproxy.go
  pkg/sync/v5/bindata.go
  pkg/sync/v5/data/CronJob.batch/openshift-etcd/etcd-backup.yaml
  test/e2e/specs/fakerp/etcdbackuprecovery.go
Labels: approved, lgtm, release-note-none, size/M

#1584 Automatic content regeneration script
  Makefile
  hack/periodic/content-update.sh
Labels: approved, lgtm, release-note-none, size/S

#1429 fakerp refactor
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/fakerp.go
  pkg/fakerp/middleware.go
  pkg/fakerp/routes.go
  pkg/fakerp/server.go
  pkg/fakerp/store/codecov_dummy_test.go
  pkg/fakerp/store/store.go
  pkg/fakerp/util.go
  test/e2e/specs/fakerp/admin.go
  test/e2e/specs/scaleupdown.go
Labels: approved, lgtm, release-note-none, size/XL

#1594 Master config fixups
  pkg/cluster/kubeclient/roundtrip.go
  pkg/entrypoint/metricsbridge/metricsbridge.go
  pkg/startup/v5/bindata.go
  pkg/startup/v5/data/master/etc/origin/master/client.secret
  pkg/startup/v5/data/master/etc/origin/master/master-config.yaml
  pkg/startup/v5/data/master/etc/origin/node/node-config.yaml
  pkg/startup/v5/data/worker/etc/origin/node/node-config.yaml
  pkg/startup/v5/startup.go
Labels: approved, lgtm, release-note, size/M

#1595 try not to use microsoft reserved names
  pkg/util/random/random.go
Labels: approved, lgtm, release-note-none, size/M

#1591 misc further tidying, mostly fakerp
  cmd/createorupdate/createorupdate.go
  pkg/api/plugin.go
  pkg/api/validate/admin.go
  pkg/api/validate/admin_test.go
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/controllers/customeradmin/group_controller.go
  pkg/controllers/customeradmin/group_mapping.go
  pkg/controllers/customeradmin/group_reconcile.go
  pkg/fakerp/aad.go
  pkg/fakerp/admin_handlers.go
  pkg/fakerp/config.go
  pkg/fakerp/customer_handlers.go
  pkg/fakerp/middleware.go
  pkg/fakerp/server.go
  pkg/fakerp/store/store.go
  pkg/fakerp/util.go
  pkg/fakerp/vault.go
  pkg/util/aadapp/aadapp.go
  pkg/util/azureclient/azureclient.go
  pkg/util/azureclient/graphrbac/applications.go
  pkg/util/azureclient/graphrbac/groups.go
  pkg/util/azureclient/graphrbac/groups_addons.go
  pkg/util/azureclient/resources/groups.go
  pkg/util/azureclient/resources/groups_addons.go
  pkg/util/mocks/mock_azureclient/mock_graphrbac/graphrbac.go
  pkg/util/mocks/mock_azureclient/mock_resources/resources.go
  test/e2e/specs/realrp/realrp.go
  test/e2e/specs/realrp/vnetpeering.go
Labels: approved, lgtm, release-note-none, size/L

#1596 add debugging on scale failure
  pkg/cluster/scaler/scaler.go
  pkg/cluster/update_worker.go
  pkg/cluster/update_worker_test.go
  pkg/util/azureclient/compute/virtualmachinescalesets.go
  pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
  pkg/util/mocks/mock_azureclient/mock_compute/compute.go
  pkg/util/mocks/mock_scaler/scaler.go
Labels: approved, lgtm, release-note-none, size/M
