Repository openshift/openshift-azure, pull requests merged in 2020-03, with the labels that each got.

#2249 Ignore new security warnings after upstream changes
  hack/verify/validate-sec.sh
Labels: approved, lgtm, release-note-none, size/XS

#2244 Bump Azure Monitor stack to ciprod03022020
  pkg/sync/v16/bindata.go
  pkg/sync/v16/data/ClusterRole.rbac.authorization.k8s.io/omsagent-reader.yaml
  pkg/sync/v16/data/ConfigMap/openshift-azure-logging/omsagent-rs-config.yaml
  pkg/sync/v16/data/DaemonSet.apps/openshift-azure-logging/omsagent.yaml
  pkg/sync/v16/data/Deployment.apps/openshift-azure-logging/omsagent-rs.yaml
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2257 Improve release instructions
  docs/release.md
Labels: approved, lgtm, release-note-none, size/M

#2255 [release-v16] Release v16.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2263 Bump OpenShift version to 3.11.188
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note

#2237 Disable old TLS versions
  pkg/sync/v17/bindata.go
  pkg/sync/v17/data/DaemonSet.apps/default/router.yaml
  test/e2e/specs/old_tls.go
Labels: approved, lgtm, release-note, size/M

#2217 update image version
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/S

#2253 Adding cluster installer script
  installer/install_openshift.sh
Labels: approved, lgtm, release-note-none, size/M
