Repository openshift/openshift-azure, pull requests merged in 2020-02, with the labels that each got.

#2206 Revert "Merge pull request #2204 from mjudeikis/node.count"
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note-none, size/S

#2209 Add Ci notes
  docs/ci.md
Labels: approved, lgtm, release-note-none, size/S

#2197 Add localresourceaccessreviews to shared-resource-editor role
  pkg/sync/v15/bindata.go
  pkg/sync/v15/data/Role.rbac.authorization.k8s.io/openshift/shared-resource-editor.yaml
Labels: approved, lgtm, release-note, size/XS

#2210 Backend scripts for geneva actions
  pkg/api/plugin.go
  pkg/plugin/plugin.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/usr/local/bin/get-live-net-status
  pkg/vmimage/data/usr/local/bin/get-node-logs
  pkg/vmimage/data/usr/local/bin/oc-get-all
Labels: approved, lgtm, release-note-none, size/M

#1990 Product manifest for our VM Images
  cmd/vmimage/vmimage.go
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/S

#2213 Adding init-network to startup container.
  pkg/arm/v15/bindata.go
  pkg/arm/v15/data/master-startup.sh
  pkg/arm/v15/data/node-startup.sh
  pkg/entrypoint/startup/cmd.go
  pkg/entrypoint/startup/startup.go
  pkg/startup/startup.go
  pkg/startup/v10/startup.go
  pkg/startup/v12/startup.go
  pkg/startup/v14/startup.go
  pkg/startup/v15/startup.go
  pkg/startup/v71/startup.go
  pkg/util/azureclient/network/networkinterface.go
  pkg/util/mocks/mock_startup/startup.go
Labels: approved, lgtm, release-note, size/L

#2224 Release v15.0
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/S

#2219 Would be nice to know when the etcdbackup finishes
  pkg/entrypoint/etcdbackup/etcdbackup.go
Labels: approved, lgtm, release-note-none, size/XS

#2221 removing references to docker from vmimage command
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/XS

#2228 Add myself to reviewers
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#2223 Adding cronjobs/jobs/daemonsets to the output
  pkg/vmimage/bindata.go
  pkg/vmimage/data/archive.tgz
  pkg/vmimage/data/usr/local/bin/oc-get-all
Labels: approved, lgtm, release-note-none, size/XS

#2229 Include private api server inside of worker properties.
  pkg/startup/v15/startup.go
  pkg/startup/v16/startup.go
Labels: approved, lgtm, release-note, size/XS

#2230 Include private api server inside of worker properties.
  pkg/startup/v15/startup.go
Labels: approved, lgtm, release-note, size/XS

#2231 Add missing changelog note for oc binary builds
  CHANGELOG.md
Labels: approved, lgtm, release-note-none, size/XS

#2233 Bump VM image version
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/XS

#2235 Provide proper certificate path to admin console
  pkg/sync/v16/bindata.go
  pkg/sync/v16/data/ConfigMap/openshift-console/console-config.yaml
  pkg/sync/v16/data/Deployment.apps/openshift-console/console.yaml
  pkg/sync/v16/data/Secret/openshift-console/apiserver-cert.yaml
  pkg/sync/v16/translate.go
Labels: approved, lgtm, release-note, size/M

#2241 Upgrade to OpenShift 3.11.170
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2240 Retry on AAD propagation failures
  pkg/api/validate/serviceprincipal.go
Labels: approved, lgtm, release-note, size/S
