Repository openshift/openshift-azure, pull requests merged in 2020-01, with the labels that each got.

#2167 [release-v14] Prepare v14 release
  CHANGELOG.md
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2166 Adds privateApiServer field into the admin API
  pkg/api/admin/converterfrominternal.go
  pkg/api/admin/convertertointernal.go
  pkg/api/admin/convertertointernal_test.go
  pkg/api/admin/types.go
  pkg/api/admin/types_test.go
Labels: approved, lgtm, release-note-none, size/S

#2133 Rename Log Analytics to omsagent
  pkg/sync/v14/bindata.go
  pkg/sync/v14/data/ClusterRole.rbac.authorization.k8s.io/omsagent-reader.yaml
  pkg/sync/v14/data/ClusterRoleBinding.rbac.authorization.k8s.io/omsagentclusterrolebinding.yaml
  pkg/sync/v14/data/ConfigMap/openshift-azure-logging/log-analytics-cluster-agent-config.yaml
  pkg/sync/v14/data/ConfigMap/openshift-azure-logging/omsagent-entrypoint.yaml
  pkg/sync/v14/data/ConfigMap/openshift-azure-logging/omsagent-rs-config.yaml
  pkg/sync/v14/data/ConfigMap/openshift-azure-logging/omsagent-rsyslog-config.yaml
  pkg/sync/v14/data/DaemonSet.apps/openshift-azure-logging/omsagent.yaml
  pkg/sync/v14/data/Deployment.apps/openshift-azure-logging/omsagent-rs.yaml
  pkg/sync/v14/data/Role.rbac.authorization.k8s.io/openshift-azure-logging/customer-admin-omsagent.yaml
  pkg/sync/v14/data/RoleBinding.rbac.authorization.k8s.io/openshift-azure-logging/customer-admin-omsagent.yaml
  pkg/sync/v14/data/Secret/openshift-azure-logging/omsagent-secret.yaml
  pkg/sync/v14/data/SecurityContextConstraints.security.openshift.io/privileged.yaml
  pkg/sync/v14/data/Service/openshift-azure-logging/healthmodel-replicaset-service.yaml
  pkg/sync/v14/data/ServiceAccount/openshift-azure-logging/omsagent.yaml
  pkg/sync/v14/envpass_test.go
  pkg/sync/v14/translate.go
  pluginconfig/pluginconfig-311.yaml
  test/e2e/specs/customer_admin.go
Labels: approved, lgtm, release-note, size/XL

#2158 Fix Template() usage so bugs are not hidden
  pkg/arm/v14/resources.go
  pkg/fakerp/container_insights.go
  pkg/startup/v14/startup.go
  pkg/vmimage/vmimage.go
Labels: approved, lgtm, release-note-none, size/L

#2162 Remove dead code in e2e tests
  test/e2e/standard/cluster.go
Labels: approved, lgtm, release-note-none, size/XS

#2177 Bump go version to 1.12.5
  pkg/vmimage/bindata.go
  pkg/vmimage/data/script.sh
Labels: approved, lgtm, release-note-none, size/S

#2172 [release-v14] Freeze v14.0 hashes, bump plugin config to 14.1
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note-none, size/M

#2189 Fix verify-sec after upstream changes
  hack/verify/validate-sec.sh
Labels: approved, lgtm, release-note-none, size/XS

#2129 Enable enduser to manage Kafka clusters
  pkg/sync/v15/bindata.go
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/admin.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/cluster-reader.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/edit.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/strimzi-aggregate-to-admin.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/strimzi-aggregate-to-edit.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/strimzi-aggregate-to-view.yaml
  pkg/sync/v15/data/ClusterRole.rbac.authorization.k8s.io/view.yaml
  pkg/sync/v15/data/ClusterRoleBinding.rbac.authorization.k8s.io/customer-admin-strimzi.yaml
  test/e2e/specs/strimzi.go
Labels: approved, lgtm, release-note, size/L

#2170 E2E test for working binary builds
  pkg/startup/v15/bindata.go
  pkg/startup/v15/data/master/etc/origin/master/master-config.yaml
  test/e2e/specs/builds.go
Labels: approved, lgtm, release-note-none, size/L

#2188 add client id for use in unit tests which disables roleLister
  pkg/api/validate/api.go
Labels: approved, lgtm, release-note, size/XS

#2187 add client id for use in unit tests which disables roleLister
  pkg/api/validate/api.go
Labels: approved, lgtm, release-note, size/XS

#2192 Release v14.config.fix
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/S

#2191 make config struct invisible for update
  pkg/api/validate/api.go
  pkg/api/validate/api_test.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/S

#2194 Updating v14.0 images to v14.1
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/S

#2193 Preparing v14.1 release
  docs/commands.md
  pkg/arm/arm.go
  pkg/cluster/hash_test.go
  pkg/config/config.go
  pkg/startup/startup.go
  pkg/sync/sync.go
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2199 align cloud-config values
  pkg/fakerp/util.go
  pkg/startup/v10/derive.go
  pkg/startup/v12/derive.go
  pkg/startup/v14/derive.go
  pkg/startup/v15/derive.go
  pkg/startup/v71/derive.go
  pkg/util/derived/derived.go
  pkg/util/derived/derived_test.go
Labels: approved, lgtm, release-note, size/M

#2202 remove reviewers
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#2185 Updating v15 with latest image build.
  pluginconfig/pluginconfig-311.yaml
Labels: approved, lgtm, release-note, size/M

#2198 Testing private cluster rotation
  cmd/createorupdate/createorupdate.go
  hack/upgrade.sh
  pkg/plugin/integration_test.go
  test/manifests/fakerp/refresh-cluster.yaml
Labels: approved, lgtm, release-note-none, size/M

#2201 Fix ILB controller panic
  hack/setup-rbac/main.go
Labels: approved, lgtm, release-note, size/XS

#2204 node count increase
  pkg/api/validate/validators.go
  pkg/api/validate/validators_test.go
Labels: approved, lgtm, release-note, size/S
